/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.protokol.dlja.zakljuchenija.kontrakta.model.impl;

import aQute.bnd.annotation.ProviderType;

import tj.protokol.dlja.zakljuchenija.kontrakta.model.protokol_dlja_zakljuchenija_kontrakta;
import tj.protokol.dlja.zakljuchenija.kontrakta.service.protokol_dlja_zakljuchenija_kontraktaLocalServiceUtil;

/**
 * The extended model base implementation for the protokol_dlja_zakljuchenija_kontrakta service. Represents a row in the &quot;sapp.protokol_dlja_zakljuchenija_kontrakta&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link protokol_dlja_zakljuchenija_kontraktaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see protokol_dlja_zakljuchenija_kontraktaImpl
 * @see protokol_dlja_zakljuchenija_kontrakta
 * @generated
 */
@ProviderType
public abstract class protokol_dlja_zakljuchenija_kontraktaBaseImpl
	extends protokol_dlja_zakljuchenija_kontraktaModelImpl
	implements protokol_dlja_zakljuchenija_kontrakta {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a protokol_dlja_zakljuchenija_kontrakta model instance should use the {@link protokol_dlja_zakljuchenija_kontrakta} interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			protokol_dlja_zakljuchenija_kontraktaLocalServiceUtil.addprotokol_dlja_zakljuchenija_kontrakta(this);
		}
		else {
			protokol_dlja_zakljuchenija_kontraktaLocalServiceUtil.updateprotokol_dlja_zakljuchenija_kontrakta(this);
		}
	}
}