/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.protokol.vskrytija.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the protokol_vskrytija service. Represents a row in the &quot;sapp.protokol_vskrytija&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link tj.protokol.vskrytija.model.impl.protokol_vskrytijaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link tj.protokol.vskrytija.model.impl.protokol_vskrytijaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see protokol_vskrytija
 * @see tj.protokol.vskrytija.model.impl.protokol_vskrytijaImpl
 * @see tj.protokol.vskrytija.model.impl.protokol_vskrytijaModelImpl
 * @generated
 */
@ProviderType
public interface protokol_vskrytijaModel extends BaseModel<protokol_vskrytija> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a protokol_vskrytija model instance should use the {@link protokol_vskrytija} interface instead.
	 */

	/**
	 * Returns the primary key of this protokol_vskrytija.
	 *
	 * @return the primary key of this protokol_vskrytija
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this protokol_vskrytija.
	 *
	 * @param primaryKey the primary key of this protokol_vskrytija
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the data_vskrytija of this protokol_vskrytija.
	 *
	 * @return the data_vskrytija of this protokol_vskrytija
	 */
	public Date getData_vskrytija();

	/**
	 * Sets the data_vskrytija of this protokol_vskrytija.
	 *
	 * @param data_vskrytija the data_vskrytija of this protokol_vskrytija
	 */
	public void setData_vskrytija(Date data_vskrytija);

	/**
	 * Returns the izvewenie_id of this protokol_vskrytija.
	 *
	 * @return the izvewenie_id of this protokol_vskrytija
	 */
	public long getIzvewenie_id();

	/**
	 * Sets the izvewenie_id of this protokol_vskrytija.
	 *
	 * @param izvewenie_id the izvewenie_id of this protokol_vskrytija
	 */
	public void setIzvewenie_id(long izvewenie_id);

	/**
	 * Returns the protokol_vskrytija_id of this protokol_vskrytija.
	 *
	 * @return the protokol_vskrytija_id of this protokol_vskrytija
	 */
	public long getProtokol_vskrytija_id();

	/**
	 * Sets the protokol_vskrytija_id of this protokol_vskrytija.
	 *
	 * @param protokol_vskrytija_id the protokol_vskrytija_id of this protokol_vskrytija
	 */
	public void setProtokol_vskrytija_id(long protokol_vskrytija_id);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		tj.protokol.vskrytija.model.protokol_vskrytija protokol_vskrytija);

	@Override
	public int hashCode();

	@Override
	public CacheModel<tj.protokol.vskrytija.model.protokol_vskrytija> toCacheModel();

	@Override
	public tj.protokol.vskrytija.model.protokol_vskrytija toEscapedModel();

	@Override
	public tj.protokol.vskrytija.model.protokol_vskrytija toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}