/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.rezultat.opredelenija.sootvetstvija.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the rezultat_opredelenija_sootvetstvija service. Represents a row in the &quot;rezultat_opredelenija_sootvetstvija_rezultat_opredelenija_sootvetstvija&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link tj.rezultat.opredelenija.sootvetstvija.model.impl.rezultat_opredelenija_sootvetstvijaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link tj.rezultat.opredelenija.sootvetstvija.model.impl.rezultat_opredelenija_sootvetstvijaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see rezultat_opredelenija_sootvetstvija
 * @see tj.rezultat.opredelenija.sootvetstvija.model.impl.rezultat_opredelenija_sootvetstvijaImpl
 * @see tj.rezultat.opredelenija.sootvetstvija.model.impl.rezultat_opredelenija_sootvetstvijaModelImpl
 * @generated
 */
@ProviderType
public interface rezultat_opredelenija_sootvetstvijaModel extends BaseModel<rezultat_opredelenija_sootvetstvija> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a rezultat_opredelenija_sootvetstvija model instance should use the {@link rezultat_opredelenija_sootvetstvija} interface instead.
	 */

	/**
	 * Returns the primary key of this rezultat_opredelenija_sootvetstvija.
	 *
	 * @return the primary key of this rezultat_opredelenija_sootvetstvija
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this rezultat_opredelenija_sootvetstvija.
	 *
	 * @param primaryKey the primary key of this rezultat_opredelenija_sootvetstvija
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the data_sozdanija of this rezultat_opredelenija_sootvetstvija.
	 *
	 * @return the data_sozdanija of this rezultat_opredelenija_sootvetstvija
	 */
	public Date getData_sozdanija();

	/**
	 * Sets the data_sozdanija of this rezultat_opredelenija_sootvetstvija.
	 *
	 * @param data_sozdanija the data_sozdanija of this rezultat_opredelenija_sootvetstvija
	 */
	public void setData_sozdanija(Date data_sozdanija);

	/**
	 * Returns the izvewenie_id of this rezultat_opredelenija_sootvetstvija.
	 *
	 * @return the izvewenie_id of this rezultat_opredelenija_sootvetstvija
	 */
	public long getIzvewenie_id();

	/**
	 * Sets the izvewenie_id of this rezultat_opredelenija_sootvetstvija.
	 *
	 * @param izvewenie_id the izvewenie_id of this rezultat_opredelenija_sootvetstvija
	 */
	public void setIzvewenie_id(long izvewenie_id);

	/**
	 * Returns the rezultat_opredelenija_sootvetstvija_id of this rezultat_opredelenija_sootvetstvija.
	 *
	 * @return the rezultat_opredelenija_sootvetstvija_id of this rezultat_opredelenija_sootvetstvija
	 */
	public long getRezultat_opredelenija_sootvetstvija_id();

	/**
	 * Sets the rezultat_opredelenija_sootvetstvija_id of this rezultat_opredelenija_sootvetstvija.
	 *
	 * @param rezultat_opredelenija_sootvetstvija_id the rezultat_opredelenija_sootvetstvija_id of this rezultat_opredelenija_sootvetstvija
	 */
	public void setRezultat_opredelenija_sootvetstvija_id(
		long rezultat_opredelenija_sootvetstvija_id);

	/**
	 * Returns the sozdal of this rezultat_opredelenija_sootvetstvija.
	 *
	 * @return the sozdal of this rezultat_opredelenija_sootvetstvija
	 */
	public long getSozdal();

	/**
	 * Sets the sozdal of this rezultat_opredelenija_sootvetstvija.
	 *
	 * @param sozdal the sozdal of this rezultat_opredelenija_sootvetstvija
	 */
	public void setSozdal(long sozdal);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		tj.rezultat.opredelenija.sootvetstvija.model.rezultat_opredelenija_sootvetstvija rezultat_opredelenija_sootvetstvija);

	@Override
	public int hashCode();

	@Override
	public CacheModel<tj.rezultat.opredelenija.sootvetstvija.model.rezultat_opredelenija_sootvetstvija> toCacheModel();

	@Override
	public tj.rezultat.opredelenija.sootvetstvija.model.rezultat_opredelenija_sootvetstvija toEscapedModel();

	@Override
	public tj.rezultat.opredelenija.sootvetstvija.model.rezultat_opredelenija_sootvetstvija toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}