/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.ocenka.uchastnikam.v.moment.vskrytija.model.impl;

import aQute.bnd.annotation.ProviderType;

import tj.ocenka.uchastnikam.v.moment.vskrytija.model.ocenka_uchastnikam_v_moment_vskrytija;
import tj.ocenka.uchastnikam.v.moment.vskrytija.service.ocenka_uchastnikam_v_moment_vskrytijaLocalServiceUtil;

/**
 * The extended model base implementation for the ocenka_uchastnikam_v_moment_vskrytija service. Represents a row in the &quot;sapp.ocenka_uchastnikam_v_moment_vskrytija&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ocenka_uchastnikam_v_moment_vskrytijaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ocenka_uchastnikam_v_moment_vskrytijaImpl
 * @see ocenka_uchastnikam_v_moment_vskrytija
 * @generated
 */
@ProviderType
public abstract class ocenka_uchastnikam_v_moment_vskrytijaBaseImpl
	extends ocenka_uchastnikam_v_moment_vskrytijaModelImpl
	implements ocenka_uchastnikam_v_moment_vskrytija {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a ocenka_uchastnikam_v_moment_vskrytija model instance should use the {@link ocenka_uchastnikam_v_moment_vskrytija} interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			ocenka_uchastnikam_v_moment_vskrytijaLocalServiceUtil.addocenka_uchastnikam_v_moment_vskrytija(this);
		}
		else {
			ocenka_uchastnikam_v_moment_vskrytijaLocalServiceUtil.updateocenka_uchastnikam_v_moment_vskrytija(this);
		}
	}
}