/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.bjudzhetnoe.polnomochie.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import tj.bjudzhetnoe.polnomochie.model.bjudzhetnoe_polnomochie;
import tj.bjudzhetnoe.polnomochie.service.bjudzhetnoe_polnomochieService;
import tj.bjudzhetnoe.polnomochie.service.persistence.bjudzhetnoe_polnomochiePersistence;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the bjudzhetnoe_polnomochie remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link tj.bjudzhetnoe.polnomochie.service.impl.bjudzhetnoe_polnomochieServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see tj.bjudzhetnoe.polnomochie.service.impl.bjudzhetnoe_polnomochieServiceImpl
 * @see tj.bjudzhetnoe.polnomochie.service.bjudzhetnoe_polnomochieServiceUtil
 * @generated
 */
public abstract class bjudzhetnoe_polnomochieServiceBaseImpl
	extends BaseServiceImpl implements bjudzhetnoe_polnomochieService,
		IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link tj.bjudzhetnoe.polnomochie.service.bjudzhetnoe_polnomochieServiceUtil} to access the bjudzhetnoe_polnomochie remote service.
	 */

	/**
	 * Returns the bjudzhetnoe_polnomochie local service.
	 *
	 * @return the bjudzhetnoe_polnomochie local service
	 */
	public tj.bjudzhetnoe.polnomochie.service.bjudzhetnoe_polnomochieLocalService getbjudzhetnoe_polnomochieLocalService() {
		return bjudzhetnoe_polnomochieLocalService;
	}

	/**
	 * Sets the bjudzhetnoe_polnomochie local service.
	 *
	 * @param bjudzhetnoe_polnomochieLocalService the bjudzhetnoe_polnomochie local service
	 */
	public void setbjudzhetnoe_polnomochieLocalService(
		tj.bjudzhetnoe.polnomochie.service.bjudzhetnoe_polnomochieLocalService bjudzhetnoe_polnomochieLocalService) {
		this.bjudzhetnoe_polnomochieLocalService = bjudzhetnoe_polnomochieLocalService;
	}

	/**
	 * Returns the bjudzhetnoe_polnomochie remote service.
	 *
	 * @return the bjudzhetnoe_polnomochie remote service
	 */
	public bjudzhetnoe_polnomochieService getbjudzhetnoe_polnomochieService() {
		return bjudzhetnoe_polnomochieService;
	}

	/**
	 * Sets the bjudzhetnoe_polnomochie remote service.
	 *
	 * @param bjudzhetnoe_polnomochieService the bjudzhetnoe_polnomochie remote service
	 */
	public void setbjudzhetnoe_polnomochieService(
		bjudzhetnoe_polnomochieService bjudzhetnoe_polnomochieService) {
		this.bjudzhetnoe_polnomochieService = bjudzhetnoe_polnomochieService;
	}

	/**
	 * Returns the bjudzhetnoe_polnomochie persistence.
	 *
	 * @return the bjudzhetnoe_polnomochie persistence
	 */
	public bjudzhetnoe_polnomochiePersistence getbjudzhetnoe_polnomochiePersistence() {
		return bjudzhetnoe_polnomochiePersistence;
	}

	/**
	 * Sets the bjudzhetnoe_polnomochie persistence.
	 *
	 * @param bjudzhetnoe_polnomochiePersistence the bjudzhetnoe_polnomochie persistence
	 */
	public void setbjudzhetnoe_polnomochiePersistence(
		bjudzhetnoe_polnomochiePersistence bjudzhetnoe_polnomochiePersistence) {
		this.bjudzhetnoe_polnomochiePersistence = bjudzhetnoe_polnomochiePersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name remote service.
	 *
	 * @return the class name remote service
	 */
	public com.liferay.portal.kernel.service.ClassNameService getClassNameService() {
		return classNameService;
	}

	/**
	 * Sets the class name remote service.
	 *
	 * @param classNameService the class name remote service
	 */
	public void setClassNameService(
		com.liferay.portal.kernel.service.ClassNameService classNameService) {
		this.classNameService = classNameService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.kernel.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.kernel.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
	}

	public void destroy() {
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return bjudzhetnoe_polnomochieService.class.getName();
	}

	protected Class<?> getModelClass() {
		return bjudzhetnoe_polnomochie.class;
	}

	protected String getModelClassName() {
		return bjudzhetnoe_polnomochie.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = bjudzhetnoe_polnomochiePersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = tj.bjudzhetnoe.polnomochie.service.bjudzhetnoe_polnomochieLocalService.class)
	protected tj.bjudzhetnoe.polnomochie.service.bjudzhetnoe_polnomochieLocalService bjudzhetnoe_polnomochieLocalService;
	@BeanReference(type = bjudzhetnoe_polnomochieService.class)
	protected bjudzhetnoe_polnomochieService bjudzhetnoe_polnomochieService;
	@BeanReference(type = bjudzhetnoe_polnomochiePersistence.class)
	protected bjudzhetnoe_polnomochiePersistence bjudzhetnoe_polnomochiePersistence;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameService.class)
	protected com.liferay.portal.kernel.service.ClassNameService classNameService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserService.class)
	protected com.liferay.portal.kernel.service.UserService userService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
}