/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.protokol.dlja.zakljuchenija.kontrakta.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the protokol_dlja_zakljuchenija_kontrakta service. Represents a row in the &quot;sapp.protokol_dlja_zakljuchenija_kontrakta&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link tj.protokol.dlja.zakljuchenija.kontrakta.model.impl.protokol_dlja_zakljuchenija_kontraktaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link tj.protokol.dlja.zakljuchenija.kontrakta.model.impl.protokol_dlja_zakljuchenija_kontraktaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see protokol_dlja_zakljuchenija_kontrakta
 * @see tj.protokol.dlja.zakljuchenija.kontrakta.model.impl.protokol_dlja_zakljuchenija_kontraktaImpl
 * @see tj.protokol.dlja.zakljuchenija.kontrakta.model.impl.protokol_dlja_zakljuchenija_kontraktaModelImpl
 * @generated
 */
@ProviderType
public interface protokol_dlja_zakljuchenija_kontraktaModel extends BaseModel<protokol_dlja_zakljuchenija_kontrakta> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a protokol_dlja_zakljuchenija_kontrakta model instance should use the {@link protokol_dlja_zakljuchenija_kontrakta} interface instead.
	 */

	/**
	 * Returns the primary key of this protokol_dlja_zakljuchenija_kontrakta.
	 *
	 * @return the primary key of this protokol_dlja_zakljuchenija_kontrakta
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this protokol_dlja_zakljuchenija_kontrakta.
	 *
	 * @param primaryKey the primary key of this protokol_dlja_zakljuchenija_kontrakta
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the data_generacii of this protokol_dlja_zakljuchenija_kontrakta.
	 *
	 * @return the data_generacii of this protokol_dlja_zakljuchenija_kontrakta
	 */
	public Date getData_generacii();

	/**
	 * Sets the data_generacii of this protokol_dlja_zakljuchenija_kontrakta.
	 *
	 * @param data_generacii the data_generacii of this protokol_dlja_zakljuchenija_kontrakta
	 */
	public void setData_generacii(Date data_generacii);

	/**
	 * Returns the izvewenie_id of this protokol_dlja_zakljuchenija_kontrakta.
	 *
	 * @return the izvewenie_id of this protokol_dlja_zakljuchenija_kontrakta
	 */
	public long getIzvewenie_id();

	/**
	 * Sets the izvewenie_id of this protokol_dlja_zakljuchenija_kontrakta.
	 *
	 * @param izvewenie_id the izvewenie_id of this protokol_dlja_zakljuchenija_kontrakta
	 */
	public void setIzvewenie_id(long izvewenie_id);

	/**
	 * Returns the protokol_dlja_zakljuchenija_kontrakta_id of this protokol_dlja_zakljuchenija_kontrakta.
	 *
	 * @return the protokol_dlja_zakljuchenija_kontrakta_id of this protokol_dlja_zakljuchenija_kontrakta
	 */
	public long getProtokol_dlja_zakljuchenija_kontrakta_id();

	/**
	 * Sets the protokol_dlja_zakljuchenija_kontrakta_id of this protokol_dlja_zakljuchenija_kontrakta.
	 *
	 * @param protokol_dlja_zakljuchenija_kontrakta_id the protokol_dlja_zakljuchenija_kontrakta_id of this protokol_dlja_zakljuchenija_kontrakta
	 */
	public void setProtokol_dlja_zakljuchenija_kontrakta_id(
		long protokol_dlja_zakljuchenija_kontrakta_id);

	/**
	 * Returns the sgeneriroval of this protokol_dlja_zakljuchenija_kontrakta.
	 *
	 * @return the sgeneriroval of this protokol_dlja_zakljuchenija_kontrakta
	 */
	public long getSgeneriroval();

	/**
	 * Sets the sgeneriroval of this protokol_dlja_zakljuchenija_kontrakta.
	 *
	 * @param sgeneriroval the sgeneriroval of this protokol_dlja_zakljuchenija_kontrakta
	 */
	public void setSgeneriroval(long sgeneriroval);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		tj.protokol.dlja.zakljuchenija.kontrakta.model.protokol_dlja_zakljuchenija_kontrakta protokol_dlja_zakljuchenija_kontrakta);

	@Override
	public int hashCode();

	@Override
	public CacheModel<tj.protokol.dlja.zakljuchenija.kontrakta.model.protokol_dlja_zakljuchenija_kontrakta> toCacheModel();

	@Override
	public tj.protokol.dlja.zakljuchenija.kontrakta.model.protokol_dlja_zakljuchenija_kontrakta toEscapedModel();

	@Override
	public tj.protokol.dlja.zakljuchenija.kontrakta.model.protokol_dlja_zakljuchenija_kontrakta toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}