/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.konkursnaja.dokumentacija.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the konkursnaja_dokumentacija service. Represents a row in the &quot;sapp.konkursnaja_dokumentacija&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link tj.konkursnaja.dokumentacija.model.impl.konkursnaja_dokumentacijaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link tj.konkursnaja.dokumentacija.model.impl.konkursnaja_dokumentacijaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see konkursnaja_dokumentacija
 * @see tj.konkursnaja.dokumentacija.model.impl.konkursnaja_dokumentacijaImpl
 * @see tj.konkursnaja.dokumentacija.model.impl.konkursnaja_dokumentacijaModelImpl
 * @generated
 */
@ProviderType
public interface konkursnaja_dokumentacijaModel extends BaseModel<konkursnaja_dokumentacija> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a konkursnaja_dokumentacija model instance should use the {@link konkursnaja_dokumentacija} interface instead.
	 */

	/**
	 * Returns the primary key of this konkursnaja_dokumentacija.
	 *
	 * @return the primary key of this konkursnaja_dokumentacija
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this konkursnaja_dokumentacija.
	 *
	 * @param primaryKey the primary key of this konkursnaja_dokumentacija
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the data_zagruzki of this konkursnaja_dokumentacija.
	 *
	 * @return the data_zagruzki of this konkursnaja_dokumentacija
	 */
	public Date getData_zagruzki();

	/**
	 * Sets the data_zagruzki of this konkursnaja_dokumentacija.
	 *
	 * @param data_zagruzki the data_zagruzki of this konkursnaja_dokumentacija
	 */
	public void setData_zagruzki(Date data_zagruzki);

	/**
	 * Returns the imja_fajla of this konkursnaja_dokumentacija.
	 *
	 * @return the imja_fajla of this konkursnaja_dokumentacija
	 */
	@AutoEscape
	public String getImja_fajla();

	/**
	 * Sets the imja_fajla of this konkursnaja_dokumentacija.
	 *
	 * @param imja_fajla the imja_fajla of this konkursnaja_dokumentacija
	 */
	public void setImja_fajla(String imja_fajla);

	/**
	 * Returns the izvewenie_id of this konkursnaja_dokumentacija.
	 *
	 * @return the izvewenie_id of this konkursnaja_dokumentacija
	 */
	public long getIzvewenie_id();

	/**
	 * Sets the izvewenie_id of this konkursnaja_dokumentacija.
	 *
	 * @param izvewenie_id the izvewenie_id of this konkursnaja_dokumentacija
	 */
	public void setIzvewenie_id(long izvewenie_id);

	/**
	 * Returns the konkursnaja_dokumentacija_id of this konkursnaja_dokumentacija.
	 *
	 * @return the konkursnaja_dokumentacija_id of this konkursnaja_dokumentacija
	 */
	public long getKonkursnaja_dokumentacija_id();

	/**
	 * Sets the konkursnaja_dokumentacija_id of this konkursnaja_dokumentacija.
	 *
	 * @param konkursnaja_dokumentacija_id the konkursnaja_dokumentacija_id of this konkursnaja_dokumentacija
	 */
	public void setKonkursnaja_dokumentacija_id(
		long konkursnaja_dokumentacija_id);

	/**
	 * Returns the lot_id of this konkursnaja_dokumentacija.
	 *
	 * @return the lot_id of this konkursnaja_dokumentacija
	 */
	public long getLot_id();

	/**
	 * Sets the lot_id of this konkursnaja_dokumentacija.
	 *
	 * @param lot_id the lot_id of this konkursnaja_dokumentacija
	 */
	public void setLot_id(long lot_id);

	/**
	 * Returns the nazvanie_dokumenta of this konkursnaja_dokumentacija.
	 *
	 * @return the nazvanie_dokumenta of this konkursnaja_dokumentacija
	 */
	@AutoEscape
	public String getNazvanie_dokumenta();

	/**
	 * Sets the nazvanie_dokumenta of this konkursnaja_dokumentacija.
	 *
	 * @param nazvanie_dokumenta the nazvanie_dokumenta of this konkursnaja_dokumentacija
	 */
	public void setNazvanie_dokumenta(String nazvanie_dokumenta);

	/**
	 * Returns the zagruzil of this konkursnaja_dokumentacija.
	 *
	 * @return the zagruzil of this konkursnaja_dokumentacija
	 */
	public long getZagruzil();

	/**
	 * Sets the zagruzil of this konkursnaja_dokumentacija.
	 *
	 * @param zagruzil the zagruzil of this konkursnaja_dokumentacija
	 */
	public void setZagruzil(long zagruzil);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		tj.konkursnaja.dokumentacija.model.konkursnaja_dokumentacija konkursnaja_dokumentacija);

	@Override
	public int hashCode();

	@Override
	public CacheModel<tj.konkursnaja.dokumentacija.model.konkursnaja_dokumentacija> toCacheModel();

	@Override
	public tj.konkursnaja.dokumentacija.model.konkursnaja_dokumentacija toEscapedModel();

	@Override
	public tj.konkursnaja.dokumentacija.model.konkursnaja_dokumentacija toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}