/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.porjadok.raboty.komissii.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the porjadok_raboty_komissii service. Represents a row in the &quot;sapp.porjadok_raboty_komissii&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link tj.porjadok.raboty.komissii.model.impl.porjadok_raboty_komissiiModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link tj.porjadok.raboty.komissii.model.impl.porjadok_raboty_komissiiImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see porjadok_raboty_komissii
 * @see tj.porjadok.raboty.komissii.model.impl.porjadok_raboty_komissiiImpl
 * @see tj.porjadok.raboty.komissii.model.impl.porjadok_raboty_komissiiModelImpl
 * @generated
 */
@ProviderType
public interface porjadok_raboty_komissiiModel extends BaseModel<porjadok_raboty_komissii> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a porjadok_raboty_komissii model instance should use the {@link porjadok_raboty_komissii} interface instead.
	 */

	/**
	 * Returns the primary key of this porjadok_raboty_komissii.
	 *
	 * @return the primary key of this porjadok_raboty_komissii
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this porjadok_raboty_komissii.
	 *
	 * @param primaryKey the primary key of this porjadok_raboty_komissii
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the data_izmenenija of this porjadok_raboty_komissii.
	 *
	 * @return the data_izmenenija of this porjadok_raboty_komissii
	 */
	public Date getData_izmenenija();

	/**
	 * Sets the data_izmenenija of this porjadok_raboty_komissii.
	 *
	 * @param data_izmenenija the data_izmenenija of this porjadok_raboty_komissii
	 */
	public void setData_izmenenija(Date data_izmenenija);

	/**
	 * Returns the data_podvedenija_itogov of this porjadok_raboty_komissii.
	 *
	 * @return the data_podvedenija_itogov of this porjadok_raboty_komissii
	 */
	public Date getData_podvedenija_itogov();

	/**
	 * Sets the data_podvedenija_itogov of this porjadok_raboty_komissii.
	 *
	 * @param data_podvedenija_itogov the data_podvedenija_itogov of this porjadok_raboty_komissii
	 */
	public void setData_podvedenija_itogov(Date data_podvedenija_itogov);

	/**
	 * Returns the data_publikacii of this porjadok_raboty_komissii.
	 *
	 * @return the data_publikacii of this porjadok_raboty_komissii
	 */
	public Date getData_publikacii();

	/**
	 * Sets the data_publikacii of this porjadok_raboty_komissii.
	 *
	 * @param data_publikacii the data_publikacii of this porjadok_raboty_komissii
	 */
	public void setData_publikacii(Date data_publikacii);

	/**
	 * Returns the data_sozdanija of this porjadok_raboty_komissii.
	 *
	 * @return the data_sozdanija of this porjadok_raboty_komissii
	 */
	public Date getData_sozdanija();

	/**
	 * Sets the data_sozdanija of this porjadok_raboty_komissii.
	 *
	 * @param data_sozdanija the data_sozdanija of this porjadok_raboty_komissii
	 */
	public void setData_sozdanija(Date data_sozdanija);

	/**
	 * Returns the izmenil of this porjadok_raboty_komissii.
	 *
	 * @return the izmenil of this porjadok_raboty_komissii
	 */
	public long getIzmenil();

	/**
	 * Sets the izmenil of this porjadok_raboty_komissii.
	 *
	 * @param izmenil the izmenil of this porjadok_raboty_komissii
	 */
	public void setIzmenil(long izmenil);

	/**
	 * Returns the izvewenie_id of this porjadok_raboty_komissii.
	 *
	 * @return the izvewenie_id of this porjadok_raboty_komissii
	 */
	public long getIzvewenie_id();

	/**
	 * Sets the izvewenie_id of this porjadok_raboty_komissii.
	 *
	 * @param izvewenie_id the izvewenie_id of this porjadok_raboty_komissii
	 */
	public void setIzvewenie_id(long izvewenie_id);

	/**
	 * Returns the po_istecheniju_dnej of this porjadok_raboty_komissii.
	 *
	 * @return the po_istecheniju_dnej of this porjadok_raboty_komissii
	 */
	public long getPo_istecheniju_dnej();

	/**
	 * Sets the po_istecheniju_dnej of this porjadok_raboty_komissii.
	 *
	 * @param po_istecheniju_dnej the po_istecheniju_dnej of this porjadok_raboty_komissii
	 */
	public void setPo_istecheniju_dnej(long po_istecheniju_dnej);

	/**
	 * Returns the porjadok_raboty_komissii_id of this porjadok_raboty_komissii.
	 *
	 * @return the porjadok_raboty_komissii_id of this porjadok_raboty_komissii
	 */
	public long getPorjadok_raboty_komissii_id();

	/**
	 * Sets the porjadok_raboty_komissii_id of this porjadok_raboty_komissii.
	 *
	 * @param porjadok_raboty_komissii_id the porjadok_raboty_komissii_id of this porjadok_raboty_komissii
	 */
	public void setPorjadok_raboty_komissii_id(long porjadok_raboty_komissii_id);

	/**
	 * Returns the sozdal of this porjadok_raboty_komissii.
	 *
	 * @return the sozdal of this porjadok_raboty_komissii
	 */
	public long getSozdal();

	/**
	 * Sets the sozdal of this porjadok_raboty_komissii.
	 *
	 * @param sozdal the sozdal of this porjadok_raboty_komissii
	 */
	public void setSozdal(long sozdal);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		tj.porjadok.raboty.komissii.model.porjadok_raboty_komissii porjadok_raboty_komissii);

	@Override
	public int hashCode();

	@Override
	public CacheModel<tj.porjadok.raboty.komissii.model.porjadok_raboty_komissii> toCacheModel();

	@Override
	public tj.porjadok.raboty.komissii.model.porjadok_raboty_komissii toEscapedModel();

	@Override
	public tj.porjadok.raboty.komissii.model.porjadok_raboty_komissii toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}