/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.protokol.podachi.pretenzij.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import tj.protokol.podachi.pretenzij.model.protokol_podachi_pretenzij;
import tj.protokol.podachi.pretenzij.model.protokol_podachi_pretenzijModel;
import tj.protokol.podachi.pretenzij.model.protokol_podachi_pretenzijSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the protokol_podachi_pretenzij service. Represents a row in the &quot;sapp.protokol_podachi_pretenzij&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link protokol_podachi_pretenzijModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link protokol_podachi_pretenzijImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see protokol_podachi_pretenzijImpl
 * @see protokol_podachi_pretenzij
 * @see protokol_podachi_pretenzijModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class protokol_podachi_pretenzijModelImpl extends BaseModelImpl<protokol_podachi_pretenzij>
	implements protokol_podachi_pretenzijModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a protokol_podachi_pretenzij model instance should use the {@link protokol_podachi_pretenzij} interface instead.
	 */
	public static final String TABLE_NAME = "sapp.protokol_podachi_pretenzij";
	public static final Object[][] TABLE_COLUMNS = {
			{ "data_generacii", Types.TIMESTAMP },
			{ "izvewenie_id", Types.BIGINT },
			{ "protokol_podachi_pretenzij_id", Types.BIGINT },
			{ "sgeneriroval", Types.BIGINT }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("data_generacii", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("izvewenie_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("protokol_podachi_pretenzij_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("sgeneriroval", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE = "create table sapp.protokol_podachi_pretenzij (data_generacii DATE null,izvewenie_id LONG,protokol_podachi_pretenzij_id LONG not null primary key,sgeneriroval LONG)";
	public static final String TABLE_SQL_DROP = "drop table sapp.protokol_podachi_pretenzij";
	public static final String ORDER_BY_JPQL = " ORDER BY protokol_podachi_pretenzij.protokol_podachi_pretenzij_id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY sapp.protokol_podachi_pretenzij.protokol_podachi_pretenzij_id ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(tj.protokol.podachi.pretenzij.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.tj.protokol.podachi.pretenzij.model.protokol_podachi_pretenzij"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(tj.protokol.podachi.pretenzij.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.tj.protokol.podachi.pretenzij.model.protokol_podachi_pretenzij"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static protokol_podachi_pretenzij toModel(
		protokol_podachi_pretenzijSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		protokol_podachi_pretenzij model = new protokol_podachi_pretenzijImpl();

		model.setData_generacii(soapModel.getData_generacii());
		model.setIzvewenie_id(soapModel.getIzvewenie_id());
		model.setProtokol_podachi_pretenzij_id(soapModel.getProtokol_podachi_pretenzij_id());
		model.setSgeneriroval(soapModel.getSgeneriroval());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<protokol_podachi_pretenzij> toModels(
		protokol_podachi_pretenzijSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<protokol_podachi_pretenzij> models = new ArrayList<protokol_podachi_pretenzij>(soapModels.length);

		for (protokol_podachi_pretenzijSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(tj.protokol.podachi.pretenzij.service.util.ServiceProps.get(
				"lock.expiration.time.tj.protokol.podachi.pretenzij.model.protokol_podachi_pretenzij"));

	public protokol_podachi_pretenzijModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _protokol_podachi_pretenzij_id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setProtokol_podachi_pretenzij_id(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _protokol_podachi_pretenzij_id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return protokol_podachi_pretenzij.class;
	}

	@Override
	public String getModelClassName() {
		return protokol_podachi_pretenzij.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("data_generacii", getData_generacii());
		attributes.put("izvewenie_id", getIzvewenie_id());
		attributes.put("protokol_podachi_pretenzij_id",
			getProtokol_podachi_pretenzij_id());
		attributes.put("sgeneriroval", getSgeneriroval());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Date data_generacii = (Date)attributes.get("data_generacii");

		if (data_generacii != null) {
			setData_generacii(data_generacii);
		}

		Long izvewenie_id = (Long)attributes.get("izvewenie_id");

		if (izvewenie_id != null) {
			setIzvewenie_id(izvewenie_id);
		}

		Long protokol_podachi_pretenzij_id = (Long)attributes.get(
				"protokol_podachi_pretenzij_id");

		if (protokol_podachi_pretenzij_id != null) {
			setProtokol_podachi_pretenzij_id(protokol_podachi_pretenzij_id);
		}

		Long sgeneriroval = (Long)attributes.get("sgeneriroval");

		if (sgeneriroval != null) {
			setSgeneriroval(sgeneriroval);
		}
	}

	@JSON
	@Override
	public Date getData_generacii() {
		return _data_generacii;
	}

	@Override
	public void setData_generacii(Date data_generacii) {
		_data_generacii = data_generacii;
	}

	@JSON
	@Override
	public long getIzvewenie_id() {
		return _izvewenie_id;
	}

	@Override
	public void setIzvewenie_id(long izvewenie_id) {
		_izvewenie_id = izvewenie_id;
	}

	@JSON
	@Override
	public long getProtokol_podachi_pretenzij_id() {
		return _protokol_podachi_pretenzij_id;
	}

	@Override
	public void setProtokol_podachi_pretenzij_id(
		long protokol_podachi_pretenzij_id) {
		_protokol_podachi_pretenzij_id = protokol_podachi_pretenzij_id;
	}

	@JSON
	@Override
	public long getSgeneriroval() {
		return _sgeneriroval;
	}

	@Override
	public void setSgeneriroval(long sgeneriroval) {
		_sgeneriroval = sgeneriroval;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			protokol_podachi_pretenzij.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public protokol_podachi_pretenzij toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (protokol_podachi_pretenzij)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		protokol_podachi_pretenzijImpl protokol_podachi_pretenzijImpl = new protokol_podachi_pretenzijImpl();

		protokol_podachi_pretenzijImpl.setData_generacii(getData_generacii());
		protokol_podachi_pretenzijImpl.setIzvewenie_id(getIzvewenie_id());
		protokol_podachi_pretenzijImpl.setProtokol_podachi_pretenzij_id(getProtokol_podachi_pretenzij_id());
		protokol_podachi_pretenzijImpl.setSgeneriroval(getSgeneriroval());

		protokol_podachi_pretenzijImpl.resetOriginalValues();

		return protokol_podachi_pretenzijImpl;
	}

	@Override
	public int compareTo(protokol_podachi_pretenzij protokol_podachi_pretenzij) {
		long primaryKey = protokol_podachi_pretenzij.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof protokol_podachi_pretenzij)) {
			return false;
		}

		protokol_podachi_pretenzij protokol_podachi_pretenzij = (protokol_podachi_pretenzij)obj;

		long primaryKey = protokol_podachi_pretenzij.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<protokol_podachi_pretenzij> toCacheModel() {
		protokol_podachi_pretenzijCacheModel protokol_podachi_pretenzijCacheModel =
			new protokol_podachi_pretenzijCacheModel();

		Date data_generacii = getData_generacii();

		if (data_generacii != null) {
			protokol_podachi_pretenzijCacheModel.data_generacii = data_generacii.getTime();
		}
		else {
			protokol_podachi_pretenzijCacheModel.data_generacii = Long.MIN_VALUE;
		}

		protokol_podachi_pretenzijCacheModel.izvewenie_id = getIzvewenie_id();

		protokol_podachi_pretenzijCacheModel.protokol_podachi_pretenzij_id = getProtokol_podachi_pretenzij_id();

		protokol_podachi_pretenzijCacheModel.sgeneriroval = getSgeneriroval();

		return protokol_podachi_pretenzijCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(9);

		sb.append("{data_generacii=");
		sb.append(getData_generacii());
		sb.append(", izvewenie_id=");
		sb.append(getIzvewenie_id());
		sb.append(", protokol_podachi_pretenzij_id=");
		sb.append(getProtokol_podachi_pretenzij_id());
		sb.append(", sgeneriroval=");
		sb.append(getSgeneriroval());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(16);

		sb.append("<model><model-name>");
		sb.append(
			"tj.protokol.podachi.pretenzij.model.protokol_podachi_pretenzij");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>data_generacii</column-name><column-value><![CDATA[");
		sb.append(getData_generacii());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>izvewenie_id</column-name><column-value><![CDATA[");
		sb.append(getIzvewenie_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>protokol_podachi_pretenzij_id</column-name><column-value><![CDATA[");
		sb.append(getProtokol_podachi_pretenzij_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sgeneriroval</column-name><column-value><![CDATA[");
		sb.append(getSgeneriroval());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = protokol_podachi_pretenzij.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			protokol_podachi_pretenzij.class
		};
	private Date _data_generacii;
	private long _izvewenie_id;
	private long _protokol_podachi_pretenzij_id;
	private long _sgeneriroval;
	private protokol_podachi_pretenzij _escapedModel;
}