/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.podtverzhdenie.nalichija.sredstv.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import tj.podtverzhdenie.nalichija.sredstv.model.podtverzhdenie_nalichija_sredstv;
import tj.podtverzhdenie.nalichija.sredstv.model.podtverzhdenie_nalichija_sredstvModel;
import tj.podtverzhdenie.nalichija.sredstv.model.podtverzhdenie_nalichija_sredstvSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the podtverzhdenie_nalichija_sredstv service. Represents a row in the &quot;sapp.podtverzhdenie_nalichija_sredstv&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link podtverzhdenie_nalichija_sredstvModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link podtverzhdenie_nalichija_sredstvImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see podtverzhdenie_nalichija_sredstvImpl
 * @see podtverzhdenie_nalichija_sredstv
 * @see podtverzhdenie_nalichija_sredstvModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class podtverzhdenie_nalichija_sredstvModelImpl extends BaseModelImpl<podtverzhdenie_nalichija_sredstv>
	implements podtverzhdenie_nalichija_sredstvModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a podtverzhdenie_nalichija_sredstv model instance should use the {@link podtverzhdenie_nalichija_sredstv} interface instead.
	 */
	public static final String TABLE_NAME = "sapp.podtverzhdenie_nalichija_sredstv";
	public static final Object[][] TABLE_COLUMNS = {
			{ "data_zagruzki", Types.TIMESTAMP },
			{ "imja_fajla", Types.VARCHAR },
			{ "izvewenie_id", Types.BIGINT },
			{ "lot_id", Types.BIGINT },
			{ "nazvanie_dokumenta", Types.VARCHAR },
			{ "podtverzhdenie_nalichija_sredstv_id", Types.BIGINT },
			{ "zagruzil", Types.BIGINT }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("data_zagruzki", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("imja_fajla", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("izvewenie_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("lot_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("nazvanie_dokumenta", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("podtverzhdenie_nalichija_sredstv_id",
			Types.BIGINT);
		TABLE_COLUMNS_MAP.put("zagruzil", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE = "create table sapp.podtverzhdenie_nalichija_sredstv (data_zagruzki DATE null,imja_fajla VARCHAR(75) null,izvewenie_id LONG,lot_id LONG,nazvanie_dokumenta VARCHAR(75) null,podtverzhdenie_nalichija_sredstv_id LONG not null primary key,zagruzil LONG)";
	public static final String TABLE_SQL_DROP = "drop table sapp.podtverzhdenie_nalichija_sredstv";
	public static final String ORDER_BY_JPQL = " ORDER BY podtverzhdenie_nalichija_sredstv.podtverzhdenie_nalichija_sredstv_id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY sapp.podtverzhdenie_nalichija_sredstv.podtverzhdenie_nalichija_sredstv_id ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(tj.podtverzhdenie.nalichija.sredstv.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.tj.podtverzhdenie.nalichija.sredstv.model.podtverzhdenie_nalichija_sredstv"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(tj.podtverzhdenie.nalichija.sredstv.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.tj.podtverzhdenie.nalichija.sredstv.model.podtverzhdenie_nalichija_sredstv"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static podtverzhdenie_nalichija_sredstv toModel(
		podtverzhdenie_nalichija_sredstvSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		podtverzhdenie_nalichija_sredstv model = new podtverzhdenie_nalichija_sredstvImpl();

		model.setData_zagruzki(soapModel.getData_zagruzki());
		model.setImja_fajla(soapModel.getImja_fajla());
		model.setIzvewenie_id(soapModel.getIzvewenie_id());
		model.setLot_id(soapModel.getLot_id());
		model.setNazvanie_dokumenta(soapModel.getNazvanie_dokumenta());
		model.setPodtverzhdenie_nalichija_sredstv_id(soapModel.getPodtverzhdenie_nalichija_sredstv_id());
		model.setZagruzil(soapModel.getZagruzil());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<podtverzhdenie_nalichija_sredstv> toModels(
		podtverzhdenie_nalichija_sredstvSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<podtverzhdenie_nalichija_sredstv> models = new ArrayList<podtverzhdenie_nalichija_sredstv>(soapModels.length);

		for (podtverzhdenie_nalichija_sredstvSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(tj.podtverzhdenie.nalichija.sredstv.service.util.ServiceProps.get(
				"lock.expiration.time.tj.podtverzhdenie.nalichija.sredstv.model.podtverzhdenie_nalichija_sredstv"));

	public podtverzhdenie_nalichija_sredstvModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _podtverzhdenie_nalichija_sredstv_id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPodtverzhdenie_nalichija_sredstv_id(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _podtverzhdenie_nalichija_sredstv_id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return podtverzhdenie_nalichija_sredstv.class;
	}

	@Override
	public String getModelClassName() {
		return podtverzhdenie_nalichija_sredstv.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("data_zagruzki", getData_zagruzki());
		attributes.put("imja_fajla", getImja_fajla());
		attributes.put("izvewenie_id", getIzvewenie_id());
		attributes.put("lot_id", getLot_id());
		attributes.put("nazvanie_dokumenta", getNazvanie_dokumenta());
		attributes.put("podtverzhdenie_nalichija_sredstv_id",
			getPodtverzhdenie_nalichija_sredstv_id());
		attributes.put("zagruzil", getZagruzil());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Date data_zagruzki = (Date)attributes.get("data_zagruzki");

		if (data_zagruzki != null) {
			setData_zagruzki(data_zagruzki);
		}

		String imja_fajla = (String)attributes.get("imja_fajla");

		if (imja_fajla != null) {
			setImja_fajla(imja_fajla);
		}

		Long izvewenie_id = (Long)attributes.get("izvewenie_id");

		if (izvewenie_id != null) {
			setIzvewenie_id(izvewenie_id);
		}

		Long lot_id = (Long)attributes.get("lot_id");

		if (lot_id != null) {
			setLot_id(lot_id);
		}

		String nazvanie_dokumenta = (String)attributes.get("nazvanie_dokumenta");

		if (nazvanie_dokumenta != null) {
			setNazvanie_dokumenta(nazvanie_dokumenta);
		}

		Long podtverzhdenie_nalichija_sredstv_id = (Long)attributes.get(
				"podtverzhdenie_nalichija_sredstv_id");

		if (podtverzhdenie_nalichija_sredstv_id != null) {
			setPodtverzhdenie_nalichija_sredstv_id(podtverzhdenie_nalichija_sredstv_id);
		}

		Long zagruzil = (Long)attributes.get("zagruzil");

		if (zagruzil != null) {
			setZagruzil(zagruzil);
		}
	}

	@JSON
	@Override
	public Date getData_zagruzki() {
		return _data_zagruzki;
	}

	@Override
	public void setData_zagruzki(Date data_zagruzki) {
		_data_zagruzki = data_zagruzki;
	}

	@JSON
	@Override
	public String getImja_fajla() {
		if (_imja_fajla == null) {
			return StringPool.BLANK;
		}
		else {
			return _imja_fajla;
		}
	}

	@Override
	public void setImja_fajla(String imja_fajla) {
		_imja_fajla = imja_fajla;
	}

	@JSON
	@Override
	public long getIzvewenie_id() {
		return _izvewenie_id;
	}

	@Override
	public void setIzvewenie_id(long izvewenie_id) {
		_izvewenie_id = izvewenie_id;
	}

	@JSON
	@Override
	public long getLot_id() {
		return _lot_id;
	}

	@Override
	public void setLot_id(long lot_id) {
		_lot_id = lot_id;
	}

	@JSON
	@Override
	public String getNazvanie_dokumenta() {
		if (_nazvanie_dokumenta == null) {
			return StringPool.BLANK;
		}
		else {
			return _nazvanie_dokumenta;
		}
	}

	@Override
	public void setNazvanie_dokumenta(String nazvanie_dokumenta) {
		_nazvanie_dokumenta = nazvanie_dokumenta;
	}

	@JSON
	@Override
	public long getPodtverzhdenie_nalichija_sredstv_id() {
		return _podtverzhdenie_nalichija_sredstv_id;
	}

	@Override
	public void setPodtverzhdenie_nalichija_sredstv_id(
		long podtverzhdenie_nalichija_sredstv_id) {
		_podtverzhdenie_nalichija_sredstv_id = podtverzhdenie_nalichija_sredstv_id;
	}

	@JSON
	@Override
	public long getZagruzil() {
		return _zagruzil;
	}

	@Override
	public void setZagruzil(long zagruzil) {
		_zagruzil = zagruzil;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			podtverzhdenie_nalichija_sredstv.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public podtverzhdenie_nalichija_sredstv toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (podtverzhdenie_nalichija_sredstv)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		podtverzhdenie_nalichija_sredstvImpl podtverzhdenie_nalichija_sredstvImpl =
			new podtverzhdenie_nalichija_sredstvImpl();

		podtverzhdenie_nalichija_sredstvImpl.setData_zagruzki(getData_zagruzki());
		podtverzhdenie_nalichija_sredstvImpl.setImja_fajla(getImja_fajla());
		podtverzhdenie_nalichija_sredstvImpl.setIzvewenie_id(getIzvewenie_id());
		podtverzhdenie_nalichija_sredstvImpl.setLot_id(getLot_id());
		podtverzhdenie_nalichija_sredstvImpl.setNazvanie_dokumenta(getNazvanie_dokumenta());
		podtverzhdenie_nalichija_sredstvImpl.setPodtverzhdenie_nalichija_sredstv_id(getPodtverzhdenie_nalichija_sredstv_id());
		podtverzhdenie_nalichija_sredstvImpl.setZagruzil(getZagruzil());

		podtverzhdenie_nalichija_sredstvImpl.resetOriginalValues();

		return podtverzhdenie_nalichija_sredstvImpl;
	}

	@Override
	public int compareTo(
		podtverzhdenie_nalichija_sredstv podtverzhdenie_nalichija_sredstv) {
		long primaryKey = podtverzhdenie_nalichija_sredstv.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof podtverzhdenie_nalichija_sredstv)) {
			return false;
		}

		podtverzhdenie_nalichija_sredstv podtverzhdenie_nalichija_sredstv = (podtverzhdenie_nalichija_sredstv)obj;

		long primaryKey = podtverzhdenie_nalichija_sredstv.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<podtverzhdenie_nalichija_sredstv> toCacheModel() {
		podtverzhdenie_nalichija_sredstvCacheModel podtverzhdenie_nalichija_sredstvCacheModel =
			new podtverzhdenie_nalichija_sredstvCacheModel();

		Date data_zagruzki = getData_zagruzki();

		if (data_zagruzki != null) {
			podtverzhdenie_nalichija_sredstvCacheModel.data_zagruzki = data_zagruzki.getTime();
		}
		else {
			podtverzhdenie_nalichija_sredstvCacheModel.data_zagruzki = Long.MIN_VALUE;
		}

		podtverzhdenie_nalichija_sredstvCacheModel.imja_fajla = getImja_fajla();

		String imja_fajla = podtverzhdenie_nalichija_sredstvCacheModel.imja_fajla;

		if ((imja_fajla != null) && (imja_fajla.length() == 0)) {
			podtverzhdenie_nalichija_sredstvCacheModel.imja_fajla = null;
		}

		podtverzhdenie_nalichija_sredstvCacheModel.izvewenie_id = getIzvewenie_id();

		podtverzhdenie_nalichija_sredstvCacheModel.lot_id = getLot_id();

		podtverzhdenie_nalichija_sredstvCacheModel.nazvanie_dokumenta = getNazvanie_dokumenta();

		String nazvanie_dokumenta = podtverzhdenie_nalichija_sredstvCacheModel.nazvanie_dokumenta;

		if ((nazvanie_dokumenta != null) && (nazvanie_dokumenta.length() == 0)) {
			podtverzhdenie_nalichija_sredstvCacheModel.nazvanie_dokumenta = null;
		}

		podtverzhdenie_nalichija_sredstvCacheModel.podtverzhdenie_nalichija_sredstv_id = getPodtverzhdenie_nalichija_sredstv_id();

		podtverzhdenie_nalichija_sredstvCacheModel.zagruzil = getZagruzil();

		return podtverzhdenie_nalichija_sredstvCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(15);

		sb.append("{data_zagruzki=");
		sb.append(getData_zagruzki());
		sb.append(", imja_fajla=");
		sb.append(getImja_fajla());
		sb.append(", izvewenie_id=");
		sb.append(getIzvewenie_id());
		sb.append(", lot_id=");
		sb.append(getLot_id());
		sb.append(", nazvanie_dokumenta=");
		sb.append(getNazvanie_dokumenta());
		sb.append(", podtverzhdenie_nalichija_sredstv_id=");
		sb.append(getPodtverzhdenie_nalichija_sredstv_id());
		sb.append(", zagruzil=");
		sb.append(getZagruzil());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(25);

		sb.append("<model><model-name>");
		sb.append(
			"tj.podtverzhdenie.nalichija.sredstv.model.podtverzhdenie_nalichija_sredstv");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>data_zagruzki</column-name><column-value><![CDATA[");
		sb.append(getData_zagruzki());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>imja_fajla</column-name><column-value><![CDATA[");
		sb.append(getImja_fajla());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>izvewenie_id</column-name><column-value><![CDATA[");
		sb.append(getIzvewenie_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>lot_id</column-name><column-value><![CDATA[");
		sb.append(getLot_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nazvanie_dokumenta</column-name><column-value><![CDATA[");
		sb.append(getNazvanie_dokumenta());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>podtverzhdenie_nalichija_sredstv_id</column-name><column-value><![CDATA[");
		sb.append(getPodtverzhdenie_nalichija_sredstv_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>zagruzil</column-name><column-value><![CDATA[");
		sb.append(getZagruzil());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = podtverzhdenie_nalichija_sredstv.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			podtverzhdenie_nalichija_sredstv.class
		};
	private Date _data_zagruzki;
	private String _imja_fajla;
	private long _izvewenie_id;
	private long _lot_id;
	private String _nazvanie_dokumenta;
	private long _podtverzhdenie_nalichija_sredstv_id;
	private long _zagruzil;
	private podtverzhdenie_nalichija_sredstv _escapedModel;
}