/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.goroda.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import tj.goroda.model.goroda;
import tj.goroda.model.gorodaModel;
import tj.goroda.model.gorodaSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the goroda service. Represents a row in the &quot;sapp.goroda&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link gorodaModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link gorodaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see gorodaImpl
 * @see goroda
 * @see gorodaModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class gorodaModelImpl extends BaseModelImpl<goroda>
	implements gorodaModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a goroda model instance should use the {@link goroda} interface instead.
	 */
	public static final String TABLE_NAME = "sapp.goroda";
	public static final Object[][] TABLE_COLUMNS = {
			{ "goroda_id", Types.BIGINT },
			{ "nazvanie", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("goroda_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("nazvanie", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table sapp.goroda (goroda_id LONG not null primary key,nazvanie VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table sapp.goroda";
	public static final String ORDER_BY_JPQL = " ORDER BY goroda.goroda_id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY sapp.goroda.goroda_id ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(tj.goroda.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.tj.goroda.model.goroda"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(tj.goroda.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.tj.goroda.model.goroda"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static goroda toModel(gorodaSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		goroda model = new gorodaImpl();

		model.setGoroda_id(soapModel.getGoroda_id());
		model.setNazvanie(soapModel.getNazvanie());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<goroda> toModels(gorodaSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<goroda> models = new ArrayList<goroda>(soapModels.length);

		for (gorodaSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(tj.goroda.service.util.ServiceProps.get(
				"lock.expiration.time.tj.goroda.model.goroda"));

	public gorodaModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _goroda_id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setGoroda_id(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _goroda_id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return goroda.class;
	}

	@Override
	public String getModelClassName() {
		return goroda.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("goroda_id", getGoroda_id());
		attributes.put("nazvanie", getNazvanie());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long goroda_id = (Long)attributes.get("goroda_id");

		if (goroda_id != null) {
			setGoroda_id(goroda_id);
		}

		String nazvanie = (String)attributes.get("nazvanie");

		if (nazvanie != null) {
			setNazvanie(nazvanie);
		}
	}

	@JSON
	@Override
	public long getGoroda_id() {
		return _goroda_id;
	}

	@Override
	public void setGoroda_id(long goroda_id) {
		_goroda_id = goroda_id;
	}

	@JSON
	@Override
	public String getNazvanie() {
		if (_nazvanie == null) {
			return StringPool.BLANK;
		}
		else {
			return _nazvanie;
		}
	}

	@Override
	public void setNazvanie(String nazvanie) {
		_nazvanie = nazvanie;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			goroda.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public goroda toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (goroda)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		gorodaImpl gorodaImpl = new gorodaImpl();

		gorodaImpl.setGoroda_id(getGoroda_id());
		gorodaImpl.setNazvanie(getNazvanie());

		gorodaImpl.resetOriginalValues();

		return gorodaImpl;
	}

	@Override
	public int compareTo(goroda goroda) {
		long primaryKey = goroda.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof goroda)) {
			return false;
		}

		goroda goroda = (goroda)obj;

		long primaryKey = goroda.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<goroda> toCacheModel() {
		gorodaCacheModel gorodaCacheModel = new gorodaCacheModel();

		gorodaCacheModel.goroda_id = getGoroda_id();

		gorodaCacheModel.nazvanie = getNazvanie();

		String nazvanie = gorodaCacheModel.nazvanie;

		if ((nazvanie != null) && (nazvanie.length() == 0)) {
			gorodaCacheModel.nazvanie = null;
		}

		return gorodaCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(5);

		sb.append("{goroda_id=");
		sb.append(getGoroda_id());
		sb.append(", nazvanie=");
		sb.append(getNazvanie());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(10);

		sb.append("<model><model-name>");
		sb.append("tj.goroda.model.goroda");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>goroda_id</column-name><column-value><![CDATA[");
		sb.append(getGoroda_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nazvanie</column-name><column-value><![CDATA[");
		sb.append(getNazvanie());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = goroda.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			goroda.class
		};
	private long _goroda_id;
	private String _nazvanie;
	private goroda _escapedModel;
}