/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.goroda.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the goroda service. Represents a row in the &quot;sapp.goroda&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link tj.goroda.model.impl.gorodaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link tj.goroda.model.impl.gorodaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see goroda
 * @see tj.goroda.model.impl.gorodaImpl
 * @see tj.goroda.model.impl.gorodaModelImpl
 * @generated
 */
@ProviderType
public interface gorodaModel extends BaseModel<goroda> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a goroda model instance should use the {@link goroda} interface instead.
	 */

	/**
	 * Returns the primary key of this goroda.
	 *
	 * @return the primary key of this goroda
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this goroda.
	 *
	 * @param primaryKey the primary key of this goroda
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the goroda_id of this goroda.
	 *
	 * @return the goroda_id of this goroda
	 */
	public long getGoroda_id();

	/**
	 * Sets the goroda_id of this goroda.
	 *
	 * @param goroda_id the goroda_id of this goroda
	 */
	public void setGoroda_id(long goroda_id);

	/**
	 * Returns the nazvanie of this goroda.
	 *
	 * @return the nazvanie of this goroda
	 */
	@AutoEscape
	public String getNazvanie();

	/**
	 * Sets the nazvanie of this goroda.
	 *
	 * @param nazvanie the nazvanie of this goroda
	 */
	public void setNazvanie(String nazvanie);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(tj.goroda.model.goroda goroda);

	@Override
	public int hashCode();

	@Override
	public CacheModel<tj.goroda.model.goroda> toCacheModel();

	@Override
	public tj.goroda.model.goroda toEscapedModel();

	@Override
	public tj.goroda.model.goroda toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}