/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.podtverzhdenie.na.uchastie.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the podtverzhdenie_na_uchastie service. Represents a row in the &quot;sapp.podtverzhdenie_na_uchastie&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link tj.podtverzhdenie.na.uchastie.model.impl.podtverzhdenie_na_uchastieModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link tj.podtverzhdenie.na.uchastie.model.impl.podtverzhdenie_na_uchastieImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see podtverzhdenie_na_uchastie
 * @see tj.podtverzhdenie.na.uchastie.model.impl.podtverzhdenie_na_uchastieImpl
 * @see tj.podtverzhdenie.na.uchastie.model.impl.podtverzhdenie_na_uchastieModelImpl
 * @generated
 */
@ProviderType
public interface podtverzhdenie_na_uchastieModel extends BaseModel<podtverzhdenie_na_uchastie> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a podtverzhdenie_na_uchastie model instance should use the {@link podtverzhdenie_na_uchastie} interface instead.
	 */

	/**
	 * Returns the primary key of this podtverzhdenie_na_uchastie.
	 *
	 * @return the primary key of this podtverzhdenie_na_uchastie
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this podtverzhdenie_na_uchastie.
	 *
	 * @param primaryKey the primary key of this podtverzhdenie_na_uchastie
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the data_sozdanija of this podtverzhdenie_na_uchastie.
	 *
	 * @return the data_sozdanija of this podtverzhdenie_na_uchastie
	 */
	public Date getData_sozdanija();

	/**
	 * Sets the data_sozdanija of this podtverzhdenie_na_uchastie.
	 *
	 * @param data_sozdanija the data_sozdanija of this podtverzhdenie_na_uchastie
	 */
	public void setData_sozdanija(Date data_sozdanija);

	/**
	 * Returns the izvewenie_id of this podtverzhdenie_na_uchastie.
	 *
	 * @return the izvewenie_id of this podtverzhdenie_na_uchastie
	 */
	public long getIzvewenie_id();

	/**
	 * Sets the izvewenie_id of this podtverzhdenie_na_uchastie.
	 *
	 * @param izvewenie_id the izvewenie_id of this podtverzhdenie_na_uchastie
	 */
	public void setIzvewenie_id(long izvewenie_id);

	/**
	 * Returns the lot_id of this podtverzhdenie_na_uchastie.
	 *
	 * @return the lot_id of this podtverzhdenie_na_uchastie
	 */
	public long getLot_id();

	/**
	 * Sets the lot_id of this podtverzhdenie_na_uchastie.
	 *
	 * @param lot_id the lot_id of this podtverzhdenie_na_uchastie
	 */
	public void setLot_id(long lot_id);

	/**
	 * Returns the podtverzhdenie_na_uchastie_id of this podtverzhdenie_na_uchastie.
	 *
	 * @return the podtverzhdenie_na_uchastie_id of this podtverzhdenie_na_uchastie
	 */
	public long getPodtverzhdenie_na_uchastie_id();

	/**
	 * Sets the podtverzhdenie_na_uchastie_id of this podtverzhdenie_na_uchastie.
	 *
	 * @param podtverzhdenie_na_uchastie_id the podtverzhdenie_na_uchastie_id of this podtverzhdenie_na_uchastie
	 */
	public void setPodtverzhdenie_na_uchastie_id(
		long podtverzhdenie_na_uchastie_id);

	/**
	 * Returns the postavwik_id of this podtverzhdenie_na_uchastie.
	 *
	 * @return the postavwik_id of this podtverzhdenie_na_uchastie
	 */
	public long getPostavwik_id();

	/**
	 * Sets the postavwik_id of this podtverzhdenie_na_uchastie.
	 *
	 * @param postavwik_id the postavwik_id of this podtverzhdenie_na_uchastie
	 */
	public void setPostavwik_id(long postavwik_id);

	/**
	 * Returns the sozdal of this podtverzhdenie_na_uchastie.
	 *
	 * @return the sozdal of this podtverzhdenie_na_uchastie
	 */
	public long getSozdal();

	/**
	 * Sets the sozdal of this podtverzhdenie_na_uchastie.
	 *
	 * @param sozdal the sozdal of this podtverzhdenie_na_uchastie
	 */
	public void setSozdal(long sozdal);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		tj.podtverzhdenie.na.uchastie.model.podtverzhdenie_na_uchastie podtverzhdenie_na_uchastie);

	@Override
	public int hashCode();

	@Override
	public CacheModel<tj.podtverzhdenie.na.uchastie.model.podtverzhdenie_na_uchastie> toCacheModel();

	@Override
	public tj.podtverzhdenie.na.uchastie.model.podtverzhdenie_na_uchastie toEscapedModel();

	@Override
	public tj.podtverzhdenie.na.uchastie.model.podtverzhdenie_na_uchastie toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}