/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.otozvannye.zajavki.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the otozvannye_zajavki service. Represents a row in the &quot;sapp.otozvannye_zajavki&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link tj.otozvannye.zajavki.model.impl.otozvannye_zajavkiModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link tj.otozvannye.zajavki.model.impl.otozvannye_zajavkiImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see otozvannye_zajavki
 * @see tj.otozvannye.zajavki.model.impl.otozvannye_zajavkiImpl
 * @see tj.otozvannye.zajavki.model.impl.otozvannye_zajavkiModelImpl
 * @generated
 */
@ProviderType
public interface otozvannye_zajavkiModel extends BaseModel<otozvannye_zajavki> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a otozvannye_zajavki model instance should use the {@link otozvannye_zajavki} interface instead.
	 */

	/**
	 * Returns the primary key of this otozvannye_zajavki.
	 *
	 * @return the primary key of this otozvannye_zajavki
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this otozvannye_zajavki.
	 *
	 * @param primaryKey the primary key of this otozvannye_zajavki
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the data_otzyva of this otozvannye_zajavki.
	 *
	 * @return the data_otzyva of this otozvannye_zajavki
	 */
	public Date getData_otzyva();

	/**
	 * Sets the data_otzyva of this otozvannye_zajavki.
	 *
	 * @param data_otzyva the data_otzyva of this otozvannye_zajavki
	 */
	public void setData_otzyva(Date data_otzyva);

	/**
	 * Returns the itogo_za_tovar of this otozvannye_zajavki.
	 *
	 * @return the itogo_za_tovar of this otozvannye_zajavki
	 */
	public double getItogo_za_tovar();

	/**
	 * Sets the itogo_za_tovar of this otozvannye_zajavki.
	 *
	 * @param itogo_za_tovar the itogo_za_tovar of this otozvannye_zajavki
	 */
	public void setItogo_za_tovar(double itogo_za_tovar);

	/**
	 * Returns the izvewenie_id of this otozvannye_zajavki.
	 *
	 * @return the izvewenie_id of this otozvannye_zajavki
	 */
	public long getIzvewenie_id();

	/**
	 * Sets the izvewenie_id of this otozvannye_zajavki.
	 *
	 * @param izvewenie_id the izvewenie_id of this otozvannye_zajavki
	 */
	public void setIzvewenie_id(long izvewenie_id);

	/**
	 * Returns the kolichestvo of this otozvannye_zajavki.
	 *
	 * @return the kolichestvo of this otozvannye_zajavki
	 */
	public int getKolichestvo();

	/**
	 * Sets the kolichestvo of this otozvannye_zajavki.
	 *
	 * @param kolichestvo the kolichestvo of this otozvannye_zajavki
	 */
	public void setKolichestvo(int kolichestvo);

	/**
	 * Returns the lot_id of this otozvannye_zajavki.
	 *
	 * @return the lot_id of this otozvannye_zajavki
	 */
	public long getLot_id();

	/**
	 * Sets the lot_id of this otozvannye_zajavki.
	 *
	 * @param lot_id the lot_id of this otozvannye_zajavki
	 */
	public void setLot_id(long lot_id);

	/**
	 * Returns the otozval of this otozvannye_zajavki.
	 *
	 * @return the otozval of this otozvannye_zajavki
	 */
	public long getOtozval();

	/**
	 * Sets the otozval of this otozvannye_zajavki.
	 *
	 * @param otozval the otozval of this otozvannye_zajavki
	 */
	public void setOtozval(long otozval);

	/**
	 * Returns the otozvannye_zajavki_id of this otozvannye_zajavki.
	 *
	 * @return the otozvannye_zajavki_id of this otozvannye_zajavki
	 */
	public long getOtozvannye_zajavki_id();

	/**
	 * Sets the otozvannye_zajavki_id of this otozvannye_zajavki.
	 *
	 * @param otozvannye_zajavki_id the otozvannye_zajavki_id of this otozvannye_zajavki
	 */
	public void setOtozvannye_zajavki_id(long otozvannye_zajavki_id);

	/**
	 * Returns the postavwik_id of this otozvannye_zajavki.
	 *
	 * @return the postavwik_id of this otozvannye_zajavki
	 */
	public long getPostavwik_id();

	/**
	 * Sets the postavwik_id of this otozvannye_zajavki.
	 *
	 * @param postavwik_id the postavwik_id of this otozvannye_zajavki
	 */
	public void setPostavwik_id(long postavwik_id);

	/**
	 * Returns the summa_za_edinicu_tovara of this otozvannye_zajavki.
	 *
	 * @return the summa_za_edinicu_tovara of this otozvannye_zajavki
	 */
	public double getSumma_za_edinicu_tovara();

	/**
	 * Sets the summa_za_edinicu_tovara of this otozvannye_zajavki.
	 *
	 * @param summa_za_edinicu_tovara the summa_za_edinicu_tovara of this otozvannye_zajavki
	 */
	public void setSumma_za_edinicu_tovara(double summa_za_edinicu_tovara);

	/**
	 * Returns the tovar_id of this otozvannye_zajavki.
	 *
	 * @return the tovar_id of this otozvannye_zajavki
	 */
	public long getTovar_id();

	/**
	 * Sets the tovar_id of this otozvannye_zajavki.
	 *
	 * @param tovar_id the tovar_id of this otozvannye_zajavki
	 */
	public void setTovar_id(long tovar_id);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		tj.otozvannye.zajavki.model.otozvannye_zajavki otozvannye_zajavki);

	@Override
	public int hashCode();

	@Override
	public CacheModel<tj.otozvannye.zajavki.model.otozvannye_zajavki> toCacheModel();

	@Override
	public tj.otozvannye.zajavki.model.otozvannye_zajavki toEscapedModel();

	@Override
	public tj.otozvannye.zajavki.model.otozvannye_zajavki toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}