/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.informacija.o.razmewenii.service.base;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import tj.informacija.o.razmewenii.model.informacija_o_razmewenii;
import tj.informacija.o.razmewenii.service.informacija_o_razmeweniiLocalService;
import tj.informacija.o.razmewenii.service.persistence.informacija_o_razmeweniiPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the informacija_o_razmewenii local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link tj.informacija.o.razmewenii.service.impl.informacija_o_razmeweniiLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see tj.informacija.o.razmewenii.service.impl.informacija_o_razmeweniiLocalServiceImpl
 * @see tj.informacija.o.razmewenii.service.informacija_o_razmeweniiLocalServiceUtil
 * @generated
 */
@ProviderType
public abstract class informacija_o_razmeweniiLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements informacija_o_razmeweniiLocalService,
		IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link tj.informacija.o.razmewenii.service.informacija_o_razmeweniiLocalServiceUtil} to access the informacija_o_razmewenii local service.
	 */

	/**
	 * Adds the informacija_o_razmewenii to the database. Also notifies the appropriate model listeners.
	 *
	 * @param informacija_o_razmewenii the informacija_o_razmewenii
	 * @return the informacija_o_razmewenii that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public informacija_o_razmewenii addinformacija_o_razmewenii(
		informacija_o_razmewenii informacija_o_razmewenii) {
		informacija_o_razmewenii.setNew(true);

		return informacija_o_razmeweniiPersistence.update(informacija_o_razmewenii);
	}

	/**
	 * Creates a new informacija_o_razmewenii with the primary key. Does not add the informacija_o_razmewenii to the database.
	 *
	 * @param informacija_o_razmewenii_id the primary key for the new informacija_o_razmewenii
	 * @return the new informacija_o_razmewenii
	 */
	@Override
	public informacija_o_razmewenii createinformacija_o_razmewenii(
		long informacija_o_razmewenii_id) {
		return informacija_o_razmeweniiPersistence.create(informacija_o_razmewenii_id);
	}

	/**
	 * Deletes the informacija_o_razmewenii with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param informacija_o_razmewenii_id the primary key of the informacija_o_razmewenii
	 * @return the informacija_o_razmewenii that was removed
	 * @throws PortalException if a informacija_o_razmewenii with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public informacija_o_razmewenii deleteinformacija_o_razmewenii(
		long informacija_o_razmewenii_id) throws PortalException {
		return informacija_o_razmeweniiPersistence.remove(informacija_o_razmewenii_id);
	}

	/**
	 * Deletes the informacija_o_razmewenii from the database. Also notifies the appropriate model listeners.
	 *
	 * @param informacija_o_razmewenii the informacija_o_razmewenii
	 * @return the informacija_o_razmewenii that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public informacija_o_razmewenii deleteinformacija_o_razmewenii(
		informacija_o_razmewenii informacija_o_razmewenii) {
		return informacija_o_razmeweniiPersistence.remove(informacija_o_razmewenii);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(informacija_o_razmewenii.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return informacija_o_razmeweniiPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link tj.informacija.o.razmewenii.model.impl.informacija_o_razmeweniiModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end) {
		return informacija_o_razmeweniiPersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link tj.informacija.o.razmewenii.model.impl.informacija_o_razmeweniiModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end, OrderByComparator<T> orderByComparator) {
		return informacija_o_razmeweniiPersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return informacija_o_razmeweniiPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) {
		return informacija_o_razmeweniiPersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public informacija_o_razmewenii fetchinformacija_o_razmewenii(
		long informacija_o_razmewenii_id) {
		return informacija_o_razmeweniiPersistence.fetchByPrimaryKey(informacija_o_razmewenii_id);
	}

	/**
	 * Returns the informacija_o_razmewenii with the primary key.
	 *
	 * @param informacija_o_razmewenii_id the primary key of the informacija_o_razmewenii
	 * @return the informacija_o_razmewenii
	 * @throws PortalException if a informacija_o_razmewenii with the primary key could not be found
	 */
	@Override
	public informacija_o_razmewenii getinformacija_o_razmewenii(
		long informacija_o_razmewenii_id) throws PortalException {
		return informacija_o_razmeweniiPersistence.findByPrimaryKey(informacija_o_razmewenii_id);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery = new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(informacija_o_razmeweniiLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(informacija_o_razmewenii.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"informacija_o_razmewenii_id");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery getIndexableActionableDynamicQuery() {
		IndexableActionableDynamicQuery indexableActionableDynamicQuery = new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(informacija_o_razmeweniiLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(informacija_o_razmewenii.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"informacija_o_razmewenii_id");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {
		actionableDynamicQuery.setBaseLocalService(informacija_o_razmeweniiLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(informacija_o_razmewenii.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"informacija_o_razmewenii_id");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {
		return informacija_o_razmeweniiLocalService.deleteinformacija_o_razmewenii((informacija_o_razmewenii)persistedModel);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {
		return informacija_o_razmeweniiPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the informacija_o_razmeweniis.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link tj.informacija.o.razmewenii.model.impl.informacija_o_razmeweniiModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of informacija_o_razmeweniis
	 * @param end the upper bound of the range of informacija_o_razmeweniis (not inclusive)
	 * @return the range of informacija_o_razmeweniis
	 */
	@Override
	public List<informacija_o_razmewenii> getinformacija_o_razmeweniis(
		int start, int end) {
		return informacija_o_razmeweniiPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of informacija_o_razmeweniis.
	 *
	 * @return the number of informacija_o_razmeweniis
	 */
	@Override
	public int getinformacija_o_razmeweniisCount() {
		return informacija_o_razmeweniiPersistence.countAll();
	}

	/**
	 * Updates the informacija_o_razmewenii in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param informacija_o_razmewenii the informacija_o_razmewenii
	 * @return the informacija_o_razmewenii that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public informacija_o_razmewenii updateinformacija_o_razmewenii(
		informacija_o_razmewenii informacija_o_razmewenii) {
		return informacija_o_razmeweniiPersistence.update(informacija_o_razmewenii);
	}

	/**
	 * Returns the informacija_o_razmewenii local service.
	 *
	 * @return the informacija_o_razmewenii local service
	 */
	public informacija_o_razmeweniiLocalService getinformacija_o_razmeweniiLocalService() {
		return informacija_o_razmeweniiLocalService;
	}

	/**
	 * Sets the informacija_o_razmewenii local service.
	 *
	 * @param informacija_o_razmeweniiLocalService the informacija_o_razmewenii local service
	 */
	public void setinformacija_o_razmeweniiLocalService(
		informacija_o_razmeweniiLocalService informacija_o_razmeweniiLocalService) {
		this.informacija_o_razmeweniiLocalService = informacija_o_razmeweniiLocalService;
	}

	/**
	 * Returns the informacija_o_razmewenii persistence.
	 *
	 * @return the informacija_o_razmewenii persistence
	 */
	public informacija_o_razmeweniiPersistence getinformacija_o_razmeweniiPersistence() {
		return informacija_o_razmeweniiPersistence;
	}

	/**
	 * Sets the informacija_o_razmewenii persistence.
	 *
	 * @param informacija_o_razmeweniiPersistence the informacija_o_razmewenii persistence
	 */
	public void setinformacija_o_razmeweniiPersistence(
		informacija_o_razmeweniiPersistence informacija_o_razmeweniiPersistence) {
		this.informacija_o_razmeweniiPersistence = informacija_o_razmeweniiPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register("tj.informacija.o.razmewenii.model.informacija_o_razmewenii",
			informacija_o_razmeweniiLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"tj.informacija.o.razmewenii.model.informacija_o_razmewenii");
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return informacija_o_razmeweniiLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return informacija_o_razmewenii.class;
	}

	protected String getModelClassName() {
		return informacija_o_razmewenii.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = informacija_o_razmeweniiPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = informacija_o_razmeweniiLocalService.class)
	protected informacija_o_razmeweniiLocalService informacija_o_razmeweniiLocalService;
	@BeanReference(type = informacija_o_razmeweniiPersistence.class)
	protected informacija_o_razmeweniiPersistence informacija_o_razmeweniiPersistence;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry persistedModelLocalServiceRegistry;
}