/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.balans.postavwika.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import tj.balans.postavwika.model.balans_postavwika;
import tj.balans.postavwika.model.balans_postavwikaModel;
import tj.balans.postavwika.model.balans_postavwikaSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the balans_postavwika service. Represents a row in the &quot;sapp.balans_postavwika&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link balans_postavwikaModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link balans_postavwikaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see balans_postavwikaImpl
 * @see balans_postavwika
 * @see balans_postavwikaModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class balans_postavwikaModelImpl extends BaseModelImpl<balans_postavwika>
	implements balans_postavwikaModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a balans_postavwika model instance should use the {@link balans_postavwika} interface instead.
	 */
	public static final String TABLE_NAME = "sapp.balans_postavwika";
	public static final Object[][] TABLE_COLUMNS = {
			{ "balans_postavwika_id", Types.BIGINT },
			{ "balans", Types.DOUBLE },
			{ "postavwik_id", Types.BIGINT }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("balans_postavwika_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("balans", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("postavwik_id", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE = "create table sapp.balans_postavwika (balans_postavwika_id LONG not null primary key,balans DOUBLE,postavwik_id LONG)";
	public static final String TABLE_SQL_DROP = "drop table sapp.balans_postavwika";
	public static final String ORDER_BY_JPQL = " ORDER BY balans_postavwika.balans_postavwika_id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY sapp.balans_postavwika.balans_postavwika_id ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(tj.balans.postavwika.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.tj.balans.postavwika.model.balans_postavwika"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(tj.balans.postavwika.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.tj.balans.postavwika.model.balans_postavwika"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static balans_postavwika toModel(balans_postavwikaSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		balans_postavwika model = new balans_postavwikaImpl();

		model.setBalans_postavwika_id(soapModel.getBalans_postavwika_id());
		model.setBalans(soapModel.getBalans());
		model.setPostavwik_id(soapModel.getPostavwik_id());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<balans_postavwika> toModels(
		balans_postavwikaSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<balans_postavwika> models = new ArrayList<balans_postavwika>(soapModels.length);

		for (balans_postavwikaSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(tj.balans.postavwika.service.util.ServiceProps.get(
				"lock.expiration.time.tj.balans.postavwika.model.balans_postavwika"));

	public balans_postavwikaModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _balans_postavwika_id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setBalans_postavwika_id(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _balans_postavwika_id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return balans_postavwika.class;
	}

	@Override
	public String getModelClassName() {
		return balans_postavwika.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("balans_postavwika_id", getBalans_postavwika_id());
		attributes.put("balans", getBalans());
		attributes.put("postavwik_id", getPostavwik_id());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long balans_postavwika_id = (Long)attributes.get("balans_postavwika_id");

		if (balans_postavwika_id != null) {
			setBalans_postavwika_id(balans_postavwika_id);
		}

		Double balans = (Double)attributes.get("balans");

		if (balans != null) {
			setBalans(balans);
		}

		Long postavwik_id = (Long)attributes.get("postavwik_id");

		if (postavwik_id != null) {
			setPostavwik_id(postavwik_id);
		}
	}

	@JSON
	@Override
	public long getBalans_postavwika_id() {
		return _balans_postavwika_id;
	}

	@Override
	public void setBalans_postavwika_id(long balans_postavwika_id) {
		_balans_postavwika_id = balans_postavwika_id;
	}

	@JSON
	@Override
	public double getBalans() {
		return _balans;
	}

	@Override
	public void setBalans(double balans) {
		_balans = balans;
	}

	@JSON
	@Override
	public long getPostavwik_id() {
		return _postavwik_id;
	}

	@Override
	public void setPostavwik_id(long postavwik_id) {
		_postavwik_id = postavwik_id;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			balans_postavwika.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public balans_postavwika toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (balans_postavwika)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		balans_postavwikaImpl balans_postavwikaImpl = new balans_postavwikaImpl();

		balans_postavwikaImpl.setBalans_postavwika_id(getBalans_postavwika_id());
		balans_postavwikaImpl.setBalans(getBalans());
		balans_postavwikaImpl.setPostavwik_id(getPostavwik_id());

		balans_postavwikaImpl.resetOriginalValues();

		return balans_postavwikaImpl;
	}

	@Override
	public int compareTo(balans_postavwika balans_postavwika) {
		long primaryKey = balans_postavwika.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof balans_postavwika)) {
			return false;
		}

		balans_postavwika balans_postavwika = (balans_postavwika)obj;

		long primaryKey = balans_postavwika.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<balans_postavwika> toCacheModel() {
		balans_postavwikaCacheModel balans_postavwikaCacheModel = new balans_postavwikaCacheModel();

		balans_postavwikaCacheModel.balans_postavwika_id = getBalans_postavwika_id();

		balans_postavwikaCacheModel.balans = getBalans();

		balans_postavwikaCacheModel.postavwik_id = getPostavwik_id();

		return balans_postavwikaCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(7);

		sb.append("{balans_postavwika_id=");
		sb.append(getBalans_postavwika_id());
		sb.append(", balans=");
		sb.append(getBalans());
		sb.append(", postavwik_id=");
		sb.append(getPostavwik_id());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(13);

		sb.append("<model><model-name>");
		sb.append("tj.balans.postavwika.model.balans_postavwika");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>balans_postavwika_id</column-name><column-value><![CDATA[");
		sb.append(getBalans_postavwika_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>balans</column-name><column-value><![CDATA[");
		sb.append(getBalans());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>postavwik_id</column-name><column-value><![CDATA[");
		sb.append(getPostavwik_id());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = balans_postavwika.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			balans_postavwika.class
		};
	private long _balans_postavwika_id;
	private double _balans;
	private long _postavwik_id;
	private balans_postavwika _escapedModel;
}