/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.rezultat.rassmotrenija.pretenzii.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the rezultat_rassmotrenija_pretenzii service. Represents a row in the &quot;sapp.rezultat_rassmotrenija_pretenzii&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link tj.rezultat.rassmotrenija.pretenzii.model.impl.rezultat_rassmotrenija_pretenziiModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link tj.rezultat.rassmotrenija.pretenzii.model.impl.rezultat_rassmotrenija_pretenziiImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see rezultat_rassmotrenija_pretenzii
 * @see tj.rezultat.rassmotrenija.pretenzii.model.impl.rezultat_rassmotrenija_pretenziiImpl
 * @see tj.rezultat.rassmotrenija.pretenzii.model.impl.rezultat_rassmotrenija_pretenziiModelImpl
 * @generated
 */
@ProviderType
public interface rezultat_rassmotrenija_pretenziiModel extends BaseModel<rezultat_rassmotrenija_pretenzii> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a rezultat_rassmotrenija_pretenzii model instance should use the {@link rezultat_rassmotrenija_pretenzii} interface instead.
	 */

	/**
	 * Returns the primary key of this rezultat_rassmotrenija_pretenzii.
	 *
	 * @return the primary key of this rezultat_rassmotrenija_pretenzii
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this rezultat_rassmotrenija_pretenzii.
	 *
	 * @param primaryKey the primary key of this rezultat_rassmotrenija_pretenzii
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the data_zagruzki of this rezultat_rassmotrenija_pretenzii.
	 *
	 * @return the data_zagruzki of this rezultat_rassmotrenija_pretenzii
	 */
	public Date getData_zagruzki();

	/**
	 * Sets the data_zagruzki of this rezultat_rassmotrenija_pretenzii.
	 *
	 * @param data_zagruzki the data_zagruzki of this rezultat_rassmotrenija_pretenzii
	 */
	public void setData_zagruzki(Date data_zagruzki);

	/**
	 * Returns the imja_fajla of this rezultat_rassmotrenija_pretenzii.
	 *
	 * @return the imja_fajla of this rezultat_rassmotrenija_pretenzii
	 */
	@AutoEscape
	public String getImja_fajla();

	/**
	 * Sets the imja_fajla of this rezultat_rassmotrenija_pretenzii.
	 *
	 * @param imja_fajla the imja_fajla of this rezultat_rassmotrenija_pretenzii
	 */
	public void setImja_fajla(String imja_fajla);

	/**
	 * Returns the izvewenie_id of this rezultat_rassmotrenija_pretenzii.
	 *
	 * @return the izvewenie_id of this rezultat_rassmotrenija_pretenzii
	 */
	public long getIzvewenie_id();

	/**
	 * Sets the izvewenie_id of this rezultat_rassmotrenija_pretenzii.
	 *
	 * @param izvewenie_id the izvewenie_id of this rezultat_rassmotrenija_pretenzii
	 */
	public void setIzvewenie_id(long izvewenie_id);

	/**
	 * Returns the lot_id of this rezultat_rassmotrenija_pretenzii.
	 *
	 * @return the lot_id of this rezultat_rassmotrenija_pretenzii
	 */
	public long getLot_id();

	/**
	 * Sets the lot_id of this rezultat_rassmotrenija_pretenzii.
	 *
	 * @param lot_id the lot_id of this rezultat_rassmotrenija_pretenzii
	 */
	public void setLot_id(long lot_id);

	/**
	 * Returns the nazvanie_dokumenta of this rezultat_rassmotrenija_pretenzii.
	 *
	 * @return the nazvanie_dokumenta of this rezultat_rassmotrenija_pretenzii
	 */
	@AutoEscape
	public String getNazvanie_dokumenta();

	/**
	 * Sets the nazvanie_dokumenta of this rezultat_rassmotrenija_pretenzii.
	 *
	 * @param nazvanie_dokumenta the nazvanie_dokumenta of this rezultat_rassmotrenija_pretenzii
	 */
	public void setNazvanie_dokumenta(String nazvanie_dokumenta);

	/**
	 * Returns the postavwik_id of this rezultat_rassmotrenija_pretenzii.
	 *
	 * @return the postavwik_id of this rezultat_rassmotrenija_pretenzii
	 */
	public long getPostavwik_id();

	/**
	 * Sets the postavwik_id of this rezultat_rassmotrenija_pretenzii.
	 *
	 * @param postavwik_id the postavwik_id of this rezultat_rassmotrenija_pretenzii
	 */
	public void setPostavwik_id(long postavwik_id);

	/**
	 * Returns the rezultat_rassmotrenija_pretenzii_id of this rezultat_rassmotrenija_pretenzii.
	 *
	 * @return the rezultat_rassmotrenija_pretenzii_id of this rezultat_rassmotrenija_pretenzii
	 */
	public long getRezultat_rassmotrenija_pretenzii_id();

	/**
	 * Sets the rezultat_rassmotrenija_pretenzii_id of this rezultat_rassmotrenija_pretenzii.
	 *
	 * @param rezultat_rassmotrenija_pretenzii_id the rezultat_rassmotrenija_pretenzii_id of this rezultat_rassmotrenija_pretenzii
	 */
	public void setRezultat_rassmotrenija_pretenzii_id(
		long rezultat_rassmotrenija_pretenzii_id);

	/**
	 * Returns the zagruzil of this rezultat_rassmotrenija_pretenzii.
	 *
	 * @return the zagruzil of this rezultat_rassmotrenija_pretenzii
	 */
	public long getZagruzil();

	/**
	 * Sets the zagruzil of this rezultat_rassmotrenija_pretenzii.
	 *
	 * @param zagruzil the zagruzil of this rezultat_rassmotrenija_pretenzii
	 */
	public void setZagruzil(long zagruzil);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		tj.rezultat.rassmotrenija.pretenzii.model.rezultat_rassmotrenija_pretenzii rezultat_rassmotrenija_pretenzii);

	@Override
	public int hashCode();

	@Override
	public CacheModel<tj.rezultat.rassmotrenija.pretenzii.model.rezultat_rassmotrenija_pretenzii> toCacheModel();

	@Override
	public tj.rezultat.rassmotrenija.pretenzii.model.rezultat_rassmotrenija_pretenzii toEscapedModel();

	@Override
	public tj.rezultat.rassmotrenija.pretenzii.model.rezultat_rassmotrenija_pretenzii toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}