/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.bjudzhetnoe.polnomochie.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the bjudzhetnoe_polnomochie service. Represents a row in the &quot;sapp.bjudzhetnoe_polnomochie&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link tj.bjudzhetnoe.polnomochie.model.impl.bjudzhetnoe_polnomochieModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link tj.bjudzhetnoe.polnomochie.model.impl.bjudzhetnoe_polnomochieImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see bjudzhetnoe_polnomochie
 * @see tj.bjudzhetnoe.polnomochie.model.impl.bjudzhetnoe_polnomochieImpl
 * @see tj.bjudzhetnoe.polnomochie.model.impl.bjudzhetnoe_polnomochieModelImpl
 * @generated
 */
@ProviderType
public interface bjudzhetnoe_polnomochieModel extends BaseModel<bjudzhetnoe_polnomochie> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a bjudzhetnoe_polnomochie model instance should use the {@link bjudzhetnoe_polnomochie} interface instead.
	 */

	/**
	 * Returns the primary key of this bjudzhetnoe_polnomochie.
	 *
	 * @return the primary key of this bjudzhetnoe_polnomochie
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this bjudzhetnoe_polnomochie.
	 *
	 * @param primaryKey the primary key of this bjudzhetnoe_polnomochie
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the bjudzhetnoe_polnomochie_id of this bjudzhetnoe_polnomochie.
	 *
	 * @return the bjudzhetnoe_polnomochie_id of this bjudzhetnoe_polnomochie
	 */
	public long getBjudzhetnoe_polnomochie_id();

	/**
	 * Sets the bjudzhetnoe_polnomochie_id of this bjudzhetnoe_polnomochie.
	 *
	 * @param bjudzhetnoe_polnomochie_id the bjudzhetnoe_polnomochie_id of this bjudzhetnoe_polnomochie
	 */
	public void setBjudzhetnoe_polnomochie_id(long bjudzhetnoe_polnomochie_id);

	/**
	 * Returns the naimenovanie of this bjudzhetnoe_polnomochie.
	 *
	 * @return the naimenovanie of this bjudzhetnoe_polnomochie
	 */
	@AutoEscape
	public String getNaimenovanie();

	/**
	 * Sets the naimenovanie of this bjudzhetnoe_polnomochie.
	 *
	 * @param naimenovanie the naimenovanie of this bjudzhetnoe_polnomochie
	 */
	public void setNaimenovanie(String naimenovanie);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		tj.bjudzhetnoe.polnomochie.model.bjudzhetnoe_polnomochie bjudzhetnoe_polnomochie);

	@Override
	public int hashCode();

	@Override
	public CacheModel<tj.bjudzhetnoe.polnomochie.model.bjudzhetnoe_polnomochie> toCacheModel();

	@Override
	public tj.bjudzhetnoe.polnomochie.model.bjudzhetnoe_polnomochie toEscapedModel();

	@Override
	public tj.bjudzhetnoe.polnomochie.model.bjudzhetnoe_polnomochie toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}