/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.dokumenty.na.zajavku.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import tj.dokumenty.na.zajavku.model.dokumenty_na_zajavku;
import tj.dokumenty.na.zajavku.service.dokumenty_na_zajavkuService;
import tj.dokumenty.na.zajavku.service.persistence.dokumenty_na_zajavkuPersistence;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the dokumenty_na_zajavku remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link tj.dokumenty.na.zajavku.service.impl.dokumenty_na_zajavkuServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see tj.dokumenty.na.zajavku.service.impl.dokumenty_na_zajavkuServiceImpl
 * @see tj.dokumenty.na.zajavku.service.dokumenty_na_zajavkuServiceUtil
 * @generated
 */
public abstract class dokumenty_na_zajavkuServiceBaseImpl
	extends BaseServiceImpl implements dokumenty_na_zajavkuService,
		IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link tj.dokumenty.na.zajavku.service.dokumenty_na_zajavkuServiceUtil} to access the dokumenty_na_zajavku remote service.
	 */

	/**
	 * Returns the dokumenty_na_zajavku local service.
	 *
	 * @return the dokumenty_na_zajavku local service
	 */
	public tj.dokumenty.na.zajavku.service.dokumenty_na_zajavkuLocalService getdokumenty_na_zajavkuLocalService() {
		return dokumenty_na_zajavkuLocalService;
	}

	/**
	 * Sets the dokumenty_na_zajavku local service.
	 *
	 * @param dokumenty_na_zajavkuLocalService the dokumenty_na_zajavku local service
	 */
	public void setdokumenty_na_zajavkuLocalService(
		tj.dokumenty.na.zajavku.service.dokumenty_na_zajavkuLocalService dokumenty_na_zajavkuLocalService) {
		this.dokumenty_na_zajavkuLocalService = dokumenty_na_zajavkuLocalService;
	}

	/**
	 * Returns the dokumenty_na_zajavku remote service.
	 *
	 * @return the dokumenty_na_zajavku remote service
	 */
	public dokumenty_na_zajavkuService getdokumenty_na_zajavkuService() {
		return dokumenty_na_zajavkuService;
	}

	/**
	 * Sets the dokumenty_na_zajavku remote service.
	 *
	 * @param dokumenty_na_zajavkuService the dokumenty_na_zajavku remote service
	 */
	public void setdokumenty_na_zajavkuService(
		dokumenty_na_zajavkuService dokumenty_na_zajavkuService) {
		this.dokumenty_na_zajavkuService = dokumenty_na_zajavkuService;
	}

	/**
	 * Returns the dokumenty_na_zajavku persistence.
	 *
	 * @return the dokumenty_na_zajavku persistence
	 */
	public dokumenty_na_zajavkuPersistence getdokumenty_na_zajavkuPersistence() {
		return dokumenty_na_zajavkuPersistence;
	}

	/**
	 * Sets the dokumenty_na_zajavku persistence.
	 *
	 * @param dokumenty_na_zajavkuPersistence the dokumenty_na_zajavku persistence
	 */
	public void setdokumenty_na_zajavkuPersistence(
		dokumenty_na_zajavkuPersistence dokumenty_na_zajavkuPersistence) {
		this.dokumenty_na_zajavkuPersistence = dokumenty_na_zajavkuPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name remote service.
	 *
	 * @return the class name remote service
	 */
	public com.liferay.portal.kernel.service.ClassNameService getClassNameService() {
		return classNameService;
	}

	/**
	 * Sets the class name remote service.
	 *
	 * @param classNameService the class name remote service
	 */
	public void setClassNameService(
		com.liferay.portal.kernel.service.ClassNameService classNameService) {
		this.classNameService = classNameService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.kernel.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.kernel.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
	}

	public void destroy() {
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return dokumenty_na_zajavkuService.class.getName();
	}

	protected Class<?> getModelClass() {
		return dokumenty_na_zajavku.class;
	}

	protected String getModelClassName() {
		return dokumenty_na_zajavku.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = dokumenty_na_zajavkuPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = tj.dokumenty.na.zajavku.service.dokumenty_na_zajavkuLocalService.class)
	protected tj.dokumenty.na.zajavku.service.dokumenty_na_zajavkuLocalService dokumenty_na_zajavkuLocalService;
	@BeanReference(type = dokumenty_na_zajavkuService.class)
	protected dokumenty_na_zajavkuService dokumenty_na_zajavkuService;
	@BeanReference(type = dokumenty_na_zajavkuPersistence.class)
	protected dokumenty_na_zajavkuPersistence dokumenty_na_zajavkuPersistence;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameService.class)
	protected com.liferay.portal.kernel.service.ClassNameService classNameService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserService.class)
	protected com.liferay.portal.kernel.service.UserService userService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
}