/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.dokumenty.na.zajavku.service.base;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import tj.dokumenty.na.zajavku.model.dokumenty_na_zajavku;
import tj.dokumenty.na.zajavku.service.dokumenty_na_zajavkuLocalService;
import tj.dokumenty.na.zajavku.service.persistence.dokumenty_na_zajavkuPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the dokumenty_na_zajavku local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link tj.dokumenty.na.zajavku.service.impl.dokumenty_na_zajavkuLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see tj.dokumenty.na.zajavku.service.impl.dokumenty_na_zajavkuLocalServiceImpl
 * @see tj.dokumenty.na.zajavku.service.dokumenty_na_zajavkuLocalServiceUtil
 * @generated
 */
@ProviderType
public abstract class dokumenty_na_zajavkuLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements dokumenty_na_zajavkuLocalService,
		IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link tj.dokumenty.na.zajavku.service.dokumenty_na_zajavkuLocalServiceUtil} to access the dokumenty_na_zajavku local service.
	 */

	/**
	 * Adds the dokumenty_na_zajavku to the database. Also notifies the appropriate model listeners.
	 *
	 * @param dokumenty_na_zajavku the dokumenty_na_zajavku
	 * @return the dokumenty_na_zajavku that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public dokumenty_na_zajavku adddokumenty_na_zajavku(
		dokumenty_na_zajavku dokumenty_na_zajavku) {
		dokumenty_na_zajavku.setNew(true);

		return dokumenty_na_zajavkuPersistence.update(dokumenty_na_zajavku);
	}

	/**
	 * Creates a new dokumenty_na_zajavku with the primary key. Does not add the dokumenty_na_zajavku to the database.
	 *
	 * @param dokumenty_na_zajavku_id the primary key for the new dokumenty_na_zajavku
	 * @return the new dokumenty_na_zajavku
	 */
	@Override
	public dokumenty_na_zajavku createdokumenty_na_zajavku(
		long dokumenty_na_zajavku_id) {
		return dokumenty_na_zajavkuPersistence.create(dokumenty_na_zajavku_id);
	}

	/**
	 * Deletes the dokumenty_na_zajavku with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param dokumenty_na_zajavku_id the primary key of the dokumenty_na_zajavku
	 * @return the dokumenty_na_zajavku that was removed
	 * @throws PortalException if a dokumenty_na_zajavku with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public dokumenty_na_zajavku deletedokumenty_na_zajavku(
		long dokumenty_na_zajavku_id) throws PortalException {
		return dokumenty_na_zajavkuPersistence.remove(dokumenty_na_zajavku_id);
	}

	/**
	 * Deletes the dokumenty_na_zajavku from the database. Also notifies the appropriate model listeners.
	 *
	 * @param dokumenty_na_zajavku the dokumenty_na_zajavku
	 * @return the dokumenty_na_zajavku that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public dokumenty_na_zajavku deletedokumenty_na_zajavku(
		dokumenty_na_zajavku dokumenty_na_zajavku) {
		return dokumenty_na_zajavkuPersistence.remove(dokumenty_na_zajavku);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(dokumenty_na_zajavku.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return dokumenty_na_zajavkuPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link tj.dokumenty.na.zajavku.model.impl.dokumenty_na_zajavkuModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end) {
		return dokumenty_na_zajavkuPersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link tj.dokumenty.na.zajavku.model.impl.dokumenty_na_zajavkuModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end, OrderByComparator<T> orderByComparator) {
		return dokumenty_na_zajavkuPersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return dokumenty_na_zajavkuPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) {
		return dokumenty_na_zajavkuPersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public dokumenty_na_zajavku fetchdokumenty_na_zajavku(
		long dokumenty_na_zajavku_id) {
		return dokumenty_na_zajavkuPersistence.fetchByPrimaryKey(dokumenty_na_zajavku_id);
	}

	/**
	 * Returns the dokumenty_na_zajavku with the primary key.
	 *
	 * @param dokumenty_na_zajavku_id the primary key of the dokumenty_na_zajavku
	 * @return the dokumenty_na_zajavku
	 * @throws PortalException if a dokumenty_na_zajavku with the primary key could not be found
	 */
	@Override
	public dokumenty_na_zajavku getdokumenty_na_zajavku(
		long dokumenty_na_zajavku_id) throws PortalException {
		return dokumenty_na_zajavkuPersistence.findByPrimaryKey(dokumenty_na_zajavku_id);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery = new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(dokumenty_na_zajavkuLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(dokumenty_na_zajavku.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"dokumenty_na_zajavku_id");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery getIndexableActionableDynamicQuery() {
		IndexableActionableDynamicQuery indexableActionableDynamicQuery = new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(dokumenty_na_zajavkuLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(dokumenty_na_zajavku.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"dokumenty_na_zajavku_id");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {
		actionableDynamicQuery.setBaseLocalService(dokumenty_na_zajavkuLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(dokumenty_na_zajavku.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"dokumenty_na_zajavku_id");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {
		return dokumenty_na_zajavkuLocalService.deletedokumenty_na_zajavku((dokumenty_na_zajavku)persistedModel);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {
		return dokumenty_na_zajavkuPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the dokumenty_na_zajavkus.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link tj.dokumenty.na.zajavku.model.impl.dokumenty_na_zajavkuModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of dokumenty_na_zajavkus
	 * @param end the upper bound of the range of dokumenty_na_zajavkus (not inclusive)
	 * @return the range of dokumenty_na_zajavkus
	 */
	@Override
	public List<dokumenty_na_zajavku> getdokumenty_na_zajavkus(int start,
		int end) {
		return dokumenty_na_zajavkuPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of dokumenty_na_zajavkus.
	 *
	 * @return the number of dokumenty_na_zajavkus
	 */
	@Override
	public int getdokumenty_na_zajavkusCount() {
		return dokumenty_na_zajavkuPersistence.countAll();
	}

	/**
	 * Updates the dokumenty_na_zajavku in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param dokumenty_na_zajavku the dokumenty_na_zajavku
	 * @return the dokumenty_na_zajavku that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public dokumenty_na_zajavku updatedokumenty_na_zajavku(
		dokumenty_na_zajavku dokumenty_na_zajavku) {
		return dokumenty_na_zajavkuPersistence.update(dokumenty_na_zajavku);
	}

	/**
	 * Returns the dokumenty_na_zajavku local service.
	 *
	 * @return the dokumenty_na_zajavku local service
	 */
	public dokumenty_na_zajavkuLocalService getdokumenty_na_zajavkuLocalService() {
		return dokumenty_na_zajavkuLocalService;
	}

	/**
	 * Sets the dokumenty_na_zajavku local service.
	 *
	 * @param dokumenty_na_zajavkuLocalService the dokumenty_na_zajavku local service
	 */
	public void setdokumenty_na_zajavkuLocalService(
		dokumenty_na_zajavkuLocalService dokumenty_na_zajavkuLocalService) {
		this.dokumenty_na_zajavkuLocalService = dokumenty_na_zajavkuLocalService;
	}

	/**
	 * Returns the dokumenty_na_zajavku persistence.
	 *
	 * @return the dokumenty_na_zajavku persistence
	 */
	public dokumenty_na_zajavkuPersistence getdokumenty_na_zajavkuPersistence() {
		return dokumenty_na_zajavkuPersistence;
	}

	/**
	 * Sets the dokumenty_na_zajavku persistence.
	 *
	 * @param dokumenty_na_zajavkuPersistence the dokumenty_na_zajavku persistence
	 */
	public void setdokumenty_na_zajavkuPersistence(
		dokumenty_na_zajavkuPersistence dokumenty_na_zajavkuPersistence) {
		this.dokumenty_na_zajavkuPersistence = dokumenty_na_zajavkuPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register("tj.dokumenty.na.zajavku.model.dokumenty_na_zajavku",
			dokumenty_na_zajavkuLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"tj.dokumenty.na.zajavku.model.dokumenty_na_zajavku");
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return dokumenty_na_zajavkuLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return dokumenty_na_zajavku.class;
	}

	protected String getModelClassName() {
		return dokumenty_na_zajavku.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = dokumenty_na_zajavkuPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = dokumenty_na_zajavkuLocalService.class)
	protected dokumenty_na_zajavkuLocalService dokumenty_na_zajavkuLocalService;
	@BeanReference(type = dokumenty_na_zajavkuPersistence.class)
	protected dokumenty_na_zajavkuPersistence dokumenty_na_zajavkuPersistence;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry persistedModelLocalServiceRegistry;
}