/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.roli.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the roli service. Represents a row in the &quot;sapp.roli&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link tj.roli.model.impl.roliModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link tj.roli.model.impl.roliImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see roli
 * @see tj.roli.model.impl.roliImpl
 * @see tj.roli.model.impl.roliModelImpl
 * @generated
 */
@ProviderType
public interface roliModel extends BaseModel<roli> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a roli model instance should use the {@link roli} interface instead.
	 */

	/**
	 * Returns the primary key of this roli.
	 *
	 * @return the primary key of this roli
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this roli.
	 *
	 * @param primaryKey the primary key of this roli
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the rol of this roli.
	 *
	 * @return the rol of this roli
	 */
	@AutoEscape
	public String getRol();

	/**
	 * Sets the rol of this roli.
	 *
	 * @param rol the rol of this roli
	 */
	public void setRol(String rol);

	/**
	 * Returns the roli_id of this roli.
	 *
	 * @return the roli_id of this roli
	 */
	public long getRoli_id();

	/**
	 * Sets the roli_id of this roli.
	 *
	 * @param roli_id the roli_id of this roli
	 */
	public void setRoli_id(long roli_id);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(tj.roli.model.roli roli);

	@Override
	public int hashCode();

	@Override
	public CacheModel<tj.roli.model.roli> toCacheModel();

	@Override
	public tj.roli.model.roli toEscapedModel();

	@Override
	public tj.roli.model.roli toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}