/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.otpravlennye.zajavki.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the otpravlennye_zajavki service. Represents a row in the &quot;sapp.otpravlennye_zajavki&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link tj.otpravlennye.zajavki.model.impl.otpravlennye_zajavkiModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link tj.otpravlennye.zajavki.model.impl.otpravlennye_zajavkiImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see otpravlennye_zajavki
 * @see tj.otpravlennye.zajavki.model.impl.otpravlennye_zajavkiImpl
 * @see tj.otpravlennye.zajavki.model.impl.otpravlennye_zajavkiModelImpl
 * @generated
 */
@ProviderType
public interface otpravlennye_zajavkiModel extends BaseModel<otpravlennye_zajavki> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a otpravlennye_zajavki model instance should use the {@link otpravlennye_zajavki} interface instead.
	 */

	/**
	 * Returns the primary key of this otpravlennye_zajavki.
	 *
	 * @return the primary key of this otpravlennye_zajavki
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this otpravlennye_zajavki.
	 *
	 * @param primaryKey the primary key of this otpravlennye_zajavki
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the data_izmenenija of this otpravlennye_zajavki.
	 *
	 * @return the data_izmenenija of this otpravlennye_zajavki
	 */
	public Date getData_izmenenija();

	/**
	 * Sets the data_izmenenija of this otpravlennye_zajavki.
	 *
	 * @param data_izmenenija the data_izmenenija of this otpravlennye_zajavki
	 */
	public void setData_izmenenija(Date data_izmenenija);

	/**
	 * Returns the data_otpravki of this otpravlennye_zajavki.
	 *
	 * @return the data_otpravki of this otpravlennye_zajavki
	 */
	public Date getData_otpravki();

	/**
	 * Sets the data_otpravki of this otpravlennye_zajavki.
	 *
	 * @param data_otpravki the data_otpravki of this otpravlennye_zajavki
	 */
	public void setData_otpravki(Date data_otpravki);

	/**
	 * Returns the izmenil of this otpravlennye_zajavki.
	 *
	 * @return the izmenil of this otpravlennye_zajavki
	 */
	public long getIzmenil();

	/**
	 * Sets the izmenil of this otpravlennye_zajavki.
	 *
	 * @param izmenil the izmenil of this otpravlennye_zajavki
	 */
	public void setIzmenil(long izmenil);

	/**
	 * Returns the izvewenie_id of this otpravlennye_zajavki.
	 *
	 * @return the izvewenie_id of this otpravlennye_zajavki
	 */
	public long getIzvewenie_id();

	/**
	 * Sets the izvewenie_id of this otpravlennye_zajavki.
	 *
	 * @param izvewenie_id the izvewenie_id of this otpravlennye_zajavki
	 */
	public void setIzvewenie_id(long izvewenie_id);

	/**
	 * Returns the kolichestvo_otpravok of this otpravlennye_zajavki.
	 *
	 * @return the kolichestvo_otpravok of this otpravlennye_zajavki
	 */
	public long getKolichestvo_otpravok();

	/**
	 * Sets the kolichestvo_otpravok of this otpravlennye_zajavki.
	 *
	 * @param kolichestvo_otpravok the kolichestvo_otpravok of this otpravlennye_zajavki
	 */
	public void setKolichestvo_otpravok(long kolichestvo_otpravok);

	/**
	 * Returns the lot_id of this otpravlennye_zajavki.
	 *
	 * @return the lot_id of this otpravlennye_zajavki
	 */
	public long getLot_id();

	/**
	 * Sets the lot_id of this otpravlennye_zajavki.
	 *
	 * @param lot_id the lot_id of this otpravlennye_zajavki
	 */
	public void setLot_id(long lot_id);

	/**
	 * Returns the otpravil of this otpravlennye_zajavki.
	 *
	 * @return the otpravil of this otpravlennye_zajavki
	 */
	public long getOtpravil();

	/**
	 * Sets the otpravil of this otpravlennye_zajavki.
	 *
	 * @param otpravil the otpravil of this otpravlennye_zajavki
	 */
	public void setOtpravil(long otpravil);

	/**
	 * Returns the otpravlennye_zajavki_id of this otpravlennye_zajavki.
	 *
	 * @return the otpravlennye_zajavki_id of this otpravlennye_zajavki
	 */
	public long getOtpravlennye_zajavki_id();

	/**
	 * Sets the otpravlennye_zajavki_id of this otpravlennye_zajavki.
	 *
	 * @param otpravlennye_zajavki_id the otpravlennye_zajavki_id of this otpravlennye_zajavki
	 */
	public void setOtpravlennye_zajavki_id(long otpravlennye_zajavki_id);

	/**
	 * Returns the postavwik_id of this otpravlennye_zajavki.
	 *
	 * @return the postavwik_id of this otpravlennye_zajavki
	 */
	public long getPostavwik_id();

	/**
	 * Sets the postavwik_id of this otpravlennye_zajavki.
	 *
	 * @param postavwik_id the postavwik_id of this otpravlennye_zajavki
	 */
	public void setPostavwik_id(long postavwik_id);

	/**
	 * Returns the status of this otpravlennye_zajavki.
	 *
	 * @return the status of this otpravlennye_zajavki
	 */
	public long getStatus();

	/**
	 * Sets the status of this otpravlennye_zajavki.
	 *
	 * @param status the status of this otpravlennye_zajavki
	 */
	public void setStatus(long status);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		tj.otpravlennye.zajavki.model.otpravlennye_zajavki otpravlennye_zajavki);

	@Override
	public int hashCode();

	@Override
	public CacheModel<tj.otpravlennye.zajavki.model.otpravlennye_zajavki> toCacheModel();

	@Override
	public tj.otpravlennye.zajavki.model.otpravlennye_zajavki toEscapedModel();

	@Override
	public tj.otpravlennye.zajavki.model.otpravlennye_zajavki toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}