/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.ne.uchastvujushhie.zajavki.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ne_uchastvujushhie_zajavki service. Represents a row in the &quot;ne_uchastvujushhie_zajavki_ne_uchastvujushhie_zajavki&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link tj.ne.uchastvujushhie.zajavki.model.impl.ne_uchastvujushhie_zajavkiModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link tj.ne.uchastvujushhie.zajavki.model.impl.ne_uchastvujushhie_zajavkiImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ne_uchastvujushhie_zajavki
 * @see tj.ne.uchastvujushhie.zajavki.model.impl.ne_uchastvujushhie_zajavkiImpl
 * @see tj.ne.uchastvujushhie.zajavki.model.impl.ne_uchastvujushhie_zajavkiModelImpl
 * @generated
 */
@ProviderType
public interface ne_uchastvujushhie_zajavkiModel extends BaseModel<ne_uchastvujushhie_zajavki> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ne_uchastvujushhie_zajavki model instance should use the {@link ne_uchastvujushhie_zajavki} interface instead.
	 */

	/**
	 * Returns the primary key of this ne_uchastvujushhie_zajavki.
	 *
	 * @return the primary key of this ne_uchastvujushhie_zajavki
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this ne_uchastvujushhie_zajavki.
	 *
	 * @param primaryKey the primary key of this ne_uchastvujushhie_zajavki
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the data_sozdanija of this ne_uchastvujushhie_zajavki.
	 *
	 * @return the data_sozdanija of this ne_uchastvujushhie_zajavki
	 */
	public Date getData_sozdanija();

	/**
	 * Sets the data_sozdanija of this ne_uchastvujushhie_zajavki.
	 *
	 * @param data_sozdanija the data_sozdanija of this ne_uchastvujushhie_zajavki
	 */
	public void setData_sozdanija(Date data_sozdanija);

	/**
	 * Returns the itogo_za_tovar of this ne_uchastvujushhie_zajavki.
	 *
	 * @return the itogo_za_tovar of this ne_uchastvujushhie_zajavki
	 */
	public double getItogo_za_tovar();

	/**
	 * Sets the itogo_za_tovar of this ne_uchastvujushhie_zajavki.
	 *
	 * @param itogo_za_tovar the itogo_za_tovar of this ne_uchastvujushhie_zajavki
	 */
	public void setItogo_za_tovar(double itogo_za_tovar);

	/**
	 * Returns the izvewenie_id of this ne_uchastvujushhie_zajavki.
	 *
	 * @return the izvewenie_id of this ne_uchastvujushhie_zajavki
	 */
	public long getIzvewenie_id();

	/**
	 * Sets the izvewenie_id of this ne_uchastvujushhie_zajavki.
	 *
	 * @param izvewenie_id the izvewenie_id of this ne_uchastvujushhie_zajavki
	 */
	public void setIzvewenie_id(long izvewenie_id);

	/**
	 * Returns the kolichestvo of this ne_uchastvujushhie_zajavki.
	 *
	 * @return the kolichestvo of this ne_uchastvujushhie_zajavki
	 */
	public long getKolichestvo();

	/**
	 * Sets the kolichestvo of this ne_uchastvujushhie_zajavki.
	 *
	 * @param kolichestvo the kolichestvo of this ne_uchastvujushhie_zajavki
	 */
	public void setKolichestvo(long kolichestvo);

	/**
	 * Returns the lot_id of this ne_uchastvujushhie_zajavki.
	 *
	 * @return the lot_id of this ne_uchastvujushhie_zajavki
	 */
	public long getLot_id();

	/**
	 * Sets the lot_id of this ne_uchastvujushhie_zajavki.
	 *
	 * @param lot_id the lot_id of this ne_uchastvujushhie_zajavki
	 */
	public void setLot_id(long lot_id);

	/**
	 * Returns the ne_uchastvujushhie_zajavki_id of this ne_uchastvujushhie_zajavki.
	 *
	 * @return the ne_uchastvujushhie_zajavki_id of this ne_uchastvujushhie_zajavki
	 */
	public long getNe_uchastvujushhie_zajavki_id();

	/**
	 * Sets the ne_uchastvujushhie_zajavki_id of this ne_uchastvujushhie_zajavki.
	 *
	 * @param ne_uchastvujushhie_zajavki_id the ne_uchastvujushhie_zajavki_id of this ne_uchastvujushhie_zajavki
	 */
	public void setNe_uchastvujushhie_zajavki_id(
		long ne_uchastvujushhie_zajavki_id);

	/**
	 * Returns the postavwik_id of this ne_uchastvujushhie_zajavki.
	 *
	 * @return the postavwik_id of this ne_uchastvujushhie_zajavki
	 */
	public long getPostavwik_id();

	/**
	 * Sets the postavwik_id of this ne_uchastvujushhie_zajavki.
	 *
	 * @param postavwik_id the postavwik_id of this ne_uchastvujushhie_zajavki
	 */
	public void setPostavwik_id(long postavwik_id);

	/**
	 * Returns the sozdal of this ne_uchastvujushhie_zajavki.
	 *
	 * @return the sozdal of this ne_uchastvujushhie_zajavki
	 */
	public long getSozdal();

	/**
	 * Sets the sozdal of this ne_uchastvujushhie_zajavki.
	 *
	 * @param sozdal the sozdal of this ne_uchastvujushhie_zajavki
	 */
	public void setSozdal(long sozdal);

	/**
	 * Returns the summa_za_edinicu_tovara of this ne_uchastvujushhie_zajavki.
	 *
	 * @return the summa_za_edinicu_tovara of this ne_uchastvujushhie_zajavki
	 */
	public double getSumma_za_edinicu_tovara();

	/**
	 * Sets the summa_za_edinicu_tovara of this ne_uchastvujushhie_zajavki.
	 *
	 * @param summa_za_edinicu_tovara the summa_za_edinicu_tovara of this ne_uchastvujushhie_zajavki
	 */
	public void setSumma_za_edinicu_tovara(double summa_za_edinicu_tovara);

	/**
	 * Returns the tovar_id of this ne_uchastvujushhie_zajavki.
	 *
	 * @return the tovar_id of this ne_uchastvujushhie_zajavki
	 */
	public long getTovar_id();

	/**
	 * Sets the tovar_id of this ne_uchastvujushhie_zajavki.
	 *
	 * @param tovar_id the tovar_id of this ne_uchastvujushhie_zajavki
	 */
	public void setTovar_id(long tovar_id);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		tj.ne.uchastvujushhie.zajavki.model.ne_uchastvujushhie_zajavki ne_uchastvujushhie_zajavki);

	@Override
	public int hashCode();

	@Override
	public CacheModel<tj.ne.uchastvujushhie.zajavki.model.ne_uchastvujushhie_zajavki> toCacheModel();

	@Override
	public tj.ne.uchastvujushhie.zajavki.model.ne_uchastvujushhie_zajavki toEscapedModel();

	@Override
	public tj.ne.uchastvujushhie.zajavki.model.ne_uchastvujushhie_zajavki toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}