/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.konkursnaja.dokumentacija.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import tj.konkursnaja.dokumentacija.model.konkursnaja_dokumentacija;
import tj.konkursnaja.dokumentacija.model.konkursnaja_dokumentacijaModel;
import tj.konkursnaja.dokumentacija.model.konkursnaja_dokumentacijaSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the konkursnaja_dokumentacija service. Represents a row in the &quot;sapp.konkursnaja_dokumentacija&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link konkursnaja_dokumentacijaModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link konkursnaja_dokumentacijaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see konkursnaja_dokumentacijaImpl
 * @see konkursnaja_dokumentacija
 * @see konkursnaja_dokumentacijaModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class konkursnaja_dokumentacijaModelImpl extends BaseModelImpl<konkursnaja_dokumentacija>
	implements konkursnaja_dokumentacijaModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a konkursnaja_dokumentacija model instance should use the {@link konkursnaja_dokumentacija} interface instead.
	 */
	public static final String TABLE_NAME = "sapp.konkursnaja_dokumentacija";
	public static final Object[][] TABLE_COLUMNS = {
			{ "data_zagruzki", Types.TIMESTAMP },
			{ "imja_fajla", Types.VARCHAR },
			{ "izvewenie_id", Types.BIGINT },
			{ "konkursnaja_dokumentacija_id", Types.BIGINT },
			{ "lot_id", Types.BIGINT },
			{ "nazvanie_dokumenta", Types.VARCHAR },
			{ "zagruzil", Types.BIGINT }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("data_zagruzki", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("imja_fajla", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("izvewenie_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("konkursnaja_dokumentacija_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("lot_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("nazvanie_dokumenta", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("zagruzil", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE = "create table sapp.konkursnaja_dokumentacija (data_zagruzki DATE null,imja_fajla VARCHAR(75) null,izvewenie_id LONG,konkursnaja_dokumentacija_id LONG not null primary key,lot_id LONG,nazvanie_dokumenta VARCHAR(75) null,zagruzil LONG)";
	public static final String TABLE_SQL_DROP = "drop table sapp.konkursnaja_dokumentacija";
	public static final String ORDER_BY_JPQL = " ORDER BY konkursnaja_dokumentacija.konkursnaja_dokumentacija_id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY sapp.konkursnaja_dokumentacija.konkursnaja_dokumentacija_id ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(tj.konkursnaja.dokumentacija.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.tj.konkursnaja.dokumentacija.model.konkursnaja_dokumentacija"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(tj.konkursnaja.dokumentacija.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.tj.konkursnaja.dokumentacija.model.konkursnaja_dokumentacija"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static konkursnaja_dokumentacija toModel(
		konkursnaja_dokumentacijaSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		konkursnaja_dokumentacija model = new konkursnaja_dokumentacijaImpl();

		model.setData_zagruzki(soapModel.getData_zagruzki());
		model.setImja_fajla(soapModel.getImja_fajla());
		model.setIzvewenie_id(soapModel.getIzvewenie_id());
		model.setKonkursnaja_dokumentacija_id(soapModel.getKonkursnaja_dokumentacija_id());
		model.setLot_id(soapModel.getLot_id());
		model.setNazvanie_dokumenta(soapModel.getNazvanie_dokumenta());
		model.setZagruzil(soapModel.getZagruzil());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<konkursnaja_dokumentacija> toModels(
		konkursnaja_dokumentacijaSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<konkursnaja_dokumentacija> models = new ArrayList<konkursnaja_dokumentacija>(soapModels.length);

		for (konkursnaja_dokumentacijaSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(tj.konkursnaja.dokumentacija.service.util.ServiceProps.get(
				"lock.expiration.time.tj.konkursnaja.dokumentacija.model.konkursnaja_dokumentacija"));

	public konkursnaja_dokumentacijaModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _konkursnaja_dokumentacija_id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setKonkursnaja_dokumentacija_id(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _konkursnaja_dokumentacija_id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return konkursnaja_dokumentacija.class;
	}

	@Override
	public String getModelClassName() {
		return konkursnaja_dokumentacija.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("data_zagruzki", getData_zagruzki());
		attributes.put("imja_fajla", getImja_fajla());
		attributes.put("izvewenie_id", getIzvewenie_id());
		attributes.put("konkursnaja_dokumentacija_id",
			getKonkursnaja_dokumentacija_id());
		attributes.put("lot_id", getLot_id());
		attributes.put("nazvanie_dokumenta", getNazvanie_dokumenta());
		attributes.put("zagruzil", getZagruzil());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Date data_zagruzki = (Date)attributes.get("data_zagruzki");

		if (data_zagruzki != null) {
			setData_zagruzki(data_zagruzki);
		}

		String imja_fajla = (String)attributes.get("imja_fajla");

		if (imja_fajla != null) {
			setImja_fajla(imja_fajla);
		}

		Long izvewenie_id = (Long)attributes.get("izvewenie_id");

		if (izvewenie_id != null) {
			setIzvewenie_id(izvewenie_id);
		}

		Long konkursnaja_dokumentacija_id = (Long)attributes.get(
				"konkursnaja_dokumentacija_id");

		if (konkursnaja_dokumentacija_id != null) {
			setKonkursnaja_dokumentacija_id(konkursnaja_dokumentacija_id);
		}

		Long lot_id = (Long)attributes.get("lot_id");

		if (lot_id != null) {
			setLot_id(lot_id);
		}

		String nazvanie_dokumenta = (String)attributes.get("nazvanie_dokumenta");

		if (nazvanie_dokumenta != null) {
			setNazvanie_dokumenta(nazvanie_dokumenta);
		}

		Long zagruzil = (Long)attributes.get("zagruzil");

		if (zagruzil != null) {
			setZagruzil(zagruzil);
		}
	}

	@JSON
	@Override
	public Date getData_zagruzki() {
		return _data_zagruzki;
	}

	@Override
	public void setData_zagruzki(Date data_zagruzki) {
		_data_zagruzki = data_zagruzki;
	}

	@JSON
	@Override
	public String getImja_fajla() {
		if (_imja_fajla == null) {
			return StringPool.BLANK;
		}
		else {
			return _imja_fajla;
		}
	}

	@Override
	public void setImja_fajla(String imja_fajla) {
		_imja_fajla = imja_fajla;
	}

	@JSON
	@Override
	public long getIzvewenie_id() {
		return _izvewenie_id;
	}

	@Override
	public void setIzvewenie_id(long izvewenie_id) {
		_izvewenie_id = izvewenie_id;
	}

	@JSON
	@Override
	public long getKonkursnaja_dokumentacija_id() {
		return _konkursnaja_dokumentacija_id;
	}

	@Override
	public void setKonkursnaja_dokumentacija_id(
		long konkursnaja_dokumentacija_id) {
		_konkursnaja_dokumentacija_id = konkursnaja_dokumentacija_id;
	}

	@JSON
	@Override
	public long getLot_id() {
		return _lot_id;
	}

	@Override
	public void setLot_id(long lot_id) {
		_lot_id = lot_id;
	}

	@JSON
	@Override
	public String getNazvanie_dokumenta() {
		if (_nazvanie_dokumenta == null) {
			return StringPool.BLANK;
		}
		else {
			return _nazvanie_dokumenta;
		}
	}

	@Override
	public void setNazvanie_dokumenta(String nazvanie_dokumenta) {
		_nazvanie_dokumenta = nazvanie_dokumenta;
	}

	@JSON
	@Override
	public long getZagruzil() {
		return _zagruzil;
	}

	@Override
	public void setZagruzil(long zagruzil) {
		_zagruzil = zagruzil;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			konkursnaja_dokumentacija.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public konkursnaja_dokumentacija toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (konkursnaja_dokumentacija)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		konkursnaja_dokumentacijaImpl konkursnaja_dokumentacijaImpl = new konkursnaja_dokumentacijaImpl();

		konkursnaja_dokumentacijaImpl.setData_zagruzki(getData_zagruzki());
		konkursnaja_dokumentacijaImpl.setImja_fajla(getImja_fajla());
		konkursnaja_dokumentacijaImpl.setIzvewenie_id(getIzvewenie_id());
		konkursnaja_dokumentacijaImpl.setKonkursnaja_dokumentacija_id(getKonkursnaja_dokumentacija_id());
		konkursnaja_dokumentacijaImpl.setLot_id(getLot_id());
		konkursnaja_dokumentacijaImpl.setNazvanie_dokumenta(getNazvanie_dokumenta());
		konkursnaja_dokumentacijaImpl.setZagruzil(getZagruzil());

		konkursnaja_dokumentacijaImpl.resetOriginalValues();

		return konkursnaja_dokumentacijaImpl;
	}

	@Override
	public int compareTo(konkursnaja_dokumentacija konkursnaja_dokumentacija) {
		long primaryKey = konkursnaja_dokumentacija.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof konkursnaja_dokumentacija)) {
			return false;
		}

		konkursnaja_dokumentacija konkursnaja_dokumentacija = (konkursnaja_dokumentacija)obj;

		long primaryKey = konkursnaja_dokumentacija.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<konkursnaja_dokumentacija> toCacheModel() {
		konkursnaja_dokumentacijaCacheModel konkursnaja_dokumentacijaCacheModel = new konkursnaja_dokumentacijaCacheModel();

		Date data_zagruzki = getData_zagruzki();

		if (data_zagruzki != null) {
			konkursnaja_dokumentacijaCacheModel.data_zagruzki = data_zagruzki.getTime();
		}
		else {
			konkursnaja_dokumentacijaCacheModel.data_zagruzki = Long.MIN_VALUE;
		}

		konkursnaja_dokumentacijaCacheModel.imja_fajla = getImja_fajla();

		String imja_fajla = konkursnaja_dokumentacijaCacheModel.imja_fajla;

		if ((imja_fajla != null) && (imja_fajla.length() == 0)) {
			konkursnaja_dokumentacijaCacheModel.imja_fajla = null;
		}

		konkursnaja_dokumentacijaCacheModel.izvewenie_id = getIzvewenie_id();

		konkursnaja_dokumentacijaCacheModel.konkursnaja_dokumentacija_id = getKonkursnaja_dokumentacija_id();

		konkursnaja_dokumentacijaCacheModel.lot_id = getLot_id();

		konkursnaja_dokumentacijaCacheModel.nazvanie_dokumenta = getNazvanie_dokumenta();

		String nazvanie_dokumenta = konkursnaja_dokumentacijaCacheModel.nazvanie_dokumenta;

		if ((nazvanie_dokumenta != null) && (nazvanie_dokumenta.length() == 0)) {
			konkursnaja_dokumentacijaCacheModel.nazvanie_dokumenta = null;
		}

		konkursnaja_dokumentacijaCacheModel.zagruzil = getZagruzil();

		return konkursnaja_dokumentacijaCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(15);

		sb.append("{data_zagruzki=");
		sb.append(getData_zagruzki());
		sb.append(", imja_fajla=");
		sb.append(getImja_fajla());
		sb.append(", izvewenie_id=");
		sb.append(getIzvewenie_id());
		sb.append(", konkursnaja_dokumentacija_id=");
		sb.append(getKonkursnaja_dokumentacija_id());
		sb.append(", lot_id=");
		sb.append(getLot_id());
		sb.append(", nazvanie_dokumenta=");
		sb.append(getNazvanie_dokumenta());
		sb.append(", zagruzil=");
		sb.append(getZagruzil());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(25);

		sb.append("<model><model-name>");
		sb.append(
			"tj.konkursnaja.dokumentacija.model.konkursnaja_dokumentacija");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>data_zagruzki</column-name><column-value><![CDATA[");
		sb.append(getData_zagruzki());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>imja_fajla</column-name><column-value><![CDATA[");
		sb.append(getImja_fajla());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>izvewenie_id</column-name><column-value><![CDATA[");
		sb.append(getIzvewenie_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>konkursnaja_dokumentacija_id</column-name><column-value><![CDATA[");
		sb.append(getKonkursnaja_dokumentacija_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>lot_id</column-name><column-value><![CDATA[");
		sb.append(getLot_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nazvanie_dokumenta</column-name><column-value><![CDATA[");
		sb.append(getNazvanie_dokumenta());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>zagruzil</column-name><column-value><![CDATA[");
		sb.append(getZagruzil());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = konkursnaja_dokumentacija.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			konkursnaja_dokumentacija.class
		};
	private Date _data_zagruzki;
	private String _imja_fajla;
	private long _izvewenie_id;
	private long _konkursnaja_dokumentacija_id;
	private long _lot_id;
	private String _nazvanie_dokumenta;
	private long _zagruzil;
	private konkursnaja_dokumentacija _escapedModel;
}