/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.dokumenty.postavwika.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import tj.dokumenty.postavwika.model.dokumenty_postavwika;
import tj.dokumenty.postavwika.service.dokumenty_postavwikaService;
import tj.dokumenty.postavwika.service.persistence.dokumenty_postavwikaPersistence;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the dokumenty_postavwika remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link tj.dokumenty.postavwika.service.impl.dokumenty_postavwikaServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see tj.dokumenty.postavwika.service.impl.dokumenty_postavwikaServiceImpl
 * @see tj.dokumenty.postavwika.service.dokumenty_postavwikaServiceUtil
 * @generated
 */
public abstract class dokumenty_postavwikaServiceBaseImpl
	extends BaseServiceImpl implements dokumenty_postavwikaService,
		IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link tj.dokumenty.postavwika.service.dokumenty_postavwikaServiceUtil} to access the dokumenty_postavwika remote service.
	 */

	/**
	 * Returns the dokumenty_postavwika local service.
	 *
	 * @return the dokumenty_postavwika local service
	 */
	public tj.dokumenty.postavwika.service.dokumenty_postavwikaLocalService getdokumenty_postavwikaLocalService() {
		return dokumenty_postavwikaLocalService;
	}

	/**
	 * Sets the dokumenty_postavwika local service.
	 *
	 * @param dokumenty_postavwikaLocalService the dokumenty_postavwika local service
	 */
	public void setdokumenty_postavwikaLocalService(
		tj.dokumenty.postavwika.service.dokumenty_postavwikaLocalService dokumenty_postavwikaLocalService) {
		this.dokumenty_postavwikaLocalService = dokumenty_postavwikaLocalService;
	}

	/**
	 * Returns the dokumenty_postavwika remote service.
	 *
	 * @return the dokumenty_postavwika remote service
	 */
	public dokumenty_postavwikaService getdokumenty_postavwikaService() {
		return dokumenty_postavwikaService;
	}

	/**
	 * Sets the dokumenty_postavwika remote service.
	 *
	 * @param dokumenty_postavwikaService the dokumenty_postavwika remote service
	 */
	public void setdokumenty_postavwikaService(
		dokumenty_postavwikaService dokumenty_postavwikaService) {
		this.dokumenty_postavwikaService = dokumenty_postavwikaService;
	}

	/**
	 * Returns the dokumenty_postavwika persistence.
	 *
	 * @return the dokumenty_postavwika persistence
	 */
	public dokumenty_postavwikaPersistence getdokumenty_postavwikaPersistence() {
		return dokumenty_postavwikaPersistence;
	}

	/**
	 * Sets the dokumenty_postavwika persistence.
	 *
	 * @param dokumenty_postavwikaPersistence the dokumenty_postavwika persistence
	 */
	public void setdokumenty_postavwikaPersistence(
		dokumenty_postavwikaPersistence dokumenty_postavwikaPersistence) {
		this.dokumenty_postavwikaPersistence = dokumenty_postavwikaPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name remote service.
	 *
	 * @return the class name remote service
	 */
	public com.liferay.portal.kernel.service.ClassNameService getClassNameService() {
		return classNameService;
	}

	/**
	 * Sets the class name remote service.
	 *
	 * @param classNameService the class name remote service
	 */
	public void setClassNameService(
		com.liferay.portal.kernel.service.ClassNameService classNameService) {
		this.classNameService = classNameService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.kernel.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.kernel.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
	}

	public void destroy() {
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return dokumenty_postavwikaService.class.getName();
	}

	protected Class<?> getModelClass() {
		return dokumenty_postavwika.class;
	}

	protected String getModelClassName() {
		return dokumenty_postavwika.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = dokumenty_postavwikaPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = tj.dokumenty.postavwika.service.dokumenty_postavwikaLocalService.class)
	protected tj.dokumenty.postavwika.service.dokumenty_postavwikaLocalService dokumenty_postavwikaLocalService;
	@BeanReference(type = dokumenty_postavwikaService.class)
	protected dokumenty_postavwikaService dokumenty_postavwikaService;
	@BeanReference(type = dokumenty_postavwikaPersistence.class)
	protected dokumenty_postavwikaPersistence dokumenty_postavwikaPersistence;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameService.class)
	protected com.liferay.portal.kernel.service.ClassNameService classNameService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserService.class)
	protected com.liferay.portal.kernel.service.UserService userService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
}