/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.zakazchiki.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the zakazchiki service. Represents a row in the &quot;sapp.zakazchiki&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link tj.zakazchiki.model.impl.zakazchikiModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link tj.zakazchiki.model.impl.zakazchikiImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see zakazchiki
 * @see tj.zakazchiki.model.impl.zakazchikiImpl
 * @see tj.zakazchiki.model.impl.zakazchikiModelImpl
 * @generated
 */
@ProviderType
public interface zakazchikiModel extends BaseModel<zakazchiki> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a zakazchiki model instance should use the {@link zakazchiki} interface instead.
	 */

	/**
	 * Returns the primary key of this zakazchiki.
	 *
	 * @return the primary key of this zakazchiki
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this zakazchiki.
	 *
	 * @param primaryKey the primary key of this zakazchiki
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the adres of this zakazchiki.
	 *
	 * @return the adres of this zakazchiki
	 */
	@AutoEscape
	public String getAdres();

	/**
	 * Sets the adres of this zakazchiki.
	 *
	 * @param adres the adres of this zakazchiki
	 */
	public void setAdres(String adres);

	/**
	 * Returns the data_izmenenija of this zakazchiki.
	 *
	 * @return the data_izmenenija of this zakazchiki
	 */
	public Date getData_izmenenija();

	/**
	 * Sets the data_izmenenija of this zakazchiki.
	 *
	 * @param data_izmenenija the data_izmenenija of this zakazchiki
	 */
	public void setData_izmenenija(Date data_izmenenija);

	/**
	 * Returns the data_sozdanija of this zakazchiki.
	 *
	 * @return the data_sozdanija of this zakazchiki
	 */
	public Date getData_sozdanija();

	/**
	 * Sets the data_sozdanija of this zakazchiki.
	 *
	 * @param data_sozdanija the data_sozdanija of this zakazchiki
	 */
	public void setData_sozdanija(Date data_sozdanija);

	/**
	 * Returns the ein of this zakazchiki.
	 *
	 * @return the ein of this zakazchiki
	 */
	@AutoEscape
	public String getEin();

	/**
	 * Sets the ein of this zakazchiki.
	 *
	 * @param ein the ein of this zakazchiki
	 */
	public void setEin(String ein);

	/**
	 * Returns the fbk_id of this zakazchiki.
	 *
	 * @return the fbk_id of this zakazchiki
	 */
	public long getFbk_id();

	/**
	 * Sets the fbk_id of this zakazchiki.
	 *
	 * @param fbk_id the fbk_id of this zakazchiki
	 */
	public void setFbk_id(long fbk_id);

	/**
	 * Returns the gorod of this zakazchiki.
	 *
	 * @return the gorod of this zakazchiki
	 */
	@AutoEscape
	public String getGorod();

	/**
	 * Sets the gorod of this zakazchiki.
	 *
	 * @param gorod the gorod of this zakazchiki
	 */
	public void setGorod(String gorod);

	/**
	 * Returns the inn of this zakazchiki.
	 *
	 * @return the inn of this zakazchiki
	 */
	@AutoEscape
	public String getInn();

	/**
	 * Sets the inn of this zakazchiki.
	 *
	 * @param inn the inn of this zakazchiki
	 */
	public void setInn(String inn);

	/**
	 * Returns the istochnik_finansirovanija_id of this zakazchiki.
	 *
	 * @return the istochnik_finansirovanija_id of this zakazchiki
	 */
	public long getIstochnik_finansirovanija_id();

	/**
	 * Sets the istochnik_finansirovanija_id of this zakazchiki.
	 *
	 * @param istochnik_finansirovanija_id the istochnik_finansirovanija_id of this zakazchiki
	 */
	public void setIstochnik_finansirovanija_id(
		long istochnik_finansirovanija_id);

	/**
	 * Returns the izmenil of this zakazchiki.
	 *
	 * @return the izmenil of this zakazchiki
	 */
	public long getIzmenil();

	/**
	 * Sets the izmenil of this zakazchiki.
	 *
	 * @param izmenil the izmenil of this zakazchiki
	 */
	public void setIzmenil(long izmenil);

	/**
	 * Returns the je_pochta of this zakazchiki.
	 *
	 * @return the je_pochta of this zakazchiki
	 */
	@AutoEscape
	public String getJe_pochta();

	/**
	 * Sets the je_pochta of this zakazchiki.
	 *
	 * @param je_pochta the je_pochta of this zakazchiki
	 */
	public void setJe_pochta(String je_pochta);

	/**
	 * Returns the kontaktnyj_telefon of this zakazchiki.
	 *
	 * @return the kontaktnyj_telefon of this zakazchiki
	 */
	@AutoEscape
	public String getKontaktnyj_telefon();

	/**
	 * Sets the kontaktnyj_telefon of this zakazchiki.
	 *
	 * @param kontaktnyj_telefon the kontaktnyj_telefon of this zakazchiki
	 */
	public void setKontaktnyj_telefon(String kontaktnyj_telefon);

	/**
	 * Returns the kvalificirovannaja_organizacija of this zakazchiki.
	 *
	 * @return the kvalificirovannaja_organizacija of this zakazchiki
	 */
	public long getKvalificirovannaja_organizacija();

	/**
	 * Sets the kvalificirovannaja_organizacija of this zakazchiki.
	 *
	 * @param kvalificirovannaja_organizacija the kvalificirovannaja_organizacija of this zakazchiki
	 */
	public void setKvalificirovannaja_organizacija(
		long kvalificirovannaja_organizacija);

	/**
	 * Returns the naimenovanie of this zakazchiki.
	 *
	 * @return the naimenovanie of this zakazchiki
	 */
	@AutoEscape
	public String getNaimenovanie();

	/**
	 * Sets the naimenovanie of this zakazchiki.
	 *
	 * @param naimenovanie the naimenovanie of this zakazchiki
	 */
	public void setNaimenovanie(String naimenovanie);

	/**
	 * Returns the oblast_id of this zakazchiki.
	 *
	 * @return the oblast_id of this zakazchiki
	 */
	public long getOblast_id();

	/**
	 * Sets the oblast_id of this zakazchiki.
	 *
	 * @param oblast_id the oblast_id of this zakazchiki
	 */
	public void setOblast_id(long oblast_id);

	/**
	 * Returns the otvetstvennoe_lico of this zakazchiki.
	 *
	 * @return the otvetstvennoe_lico of this zakazchiki
	 */
	@AutoEscape
	public String getOtvetstvennoe_lico();

	/**
	 * Sets the otvetstvennoe_lico of this zakazchiki.
	 *
	 * @param otvetstvennoe_lico the otvetstvennoe_lico of this zakazchiki
	 */
	public void setOtvetstvennoe_lico(String otvetstvennoe_lico);

	/**
	 * Returns the rajon_id of this zakazchiki.
	 *
	 * @return the rajon_id of this zakazchiki
	 */
	public long getRajon_id();

	/**
	 * Sets the rajon_id of this zakazchiki.
	 *
	 * @param rajon_id the rajon_id of this zakazchiki
	 */
	public void setRajon_id(long rajon_id);

	/**
	 * Returns the rukovoditel of this zakazchiki.
	 *
	 * @return the rukovoditel of this zakazchiki
	 */
	@AutoEscape
	public String getRukovoditel();

	/**
	 * Sets the rukovoditel of this zakazchiki.
	 *
	 * @param rukovoditel the rukovoditel of this zakazchiki
	 */
	public void setRukovoditel(String rukovoditel);

	/**
	 * Returns the sozdal of this zakazchiki.
	 *
	 * @return the sozdal of this zakazchiki
	 */
	public long getSozdal();

	/**
	 * Sets the sozdal of this zakazchiki.
	 *
	 * @param sozdal the sozdal of this zakazchiki
	 */
	public void setSozdal(long sozdal);

	/**
	 * Returns the vbk_id of this zakazchiki.
	 *
	 * @return the vbk_id of this zakazchiki
	 */
	public long getVbk_id();

	/**
	 * Sets the vbk_id of this zakazchiki.
	 *
	 * @param vbk_id the vbk_id of this zakazchiki
	 */
	public void setVbk_id(long vbk_id);

	/**
	 * Returns the zakazchiki_id of this zakazchiki.
	 *
	 * @return the zakazchiki_id of this zakazchiki
	 */
	public long getZakazchiki_id();

	/**
	 * Sets the zakazchiki_id of this zakazchiki.
	 *
	 * @param zakazchiki_id the zakazchiki_id of this zakazchiki
	 */
	public void setZakazchiki_id(long zakazchiki_id);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(tj.zakazchiki.model.zakazchiki zakazchiki);

	@Override
	public int hashCode();

	@Override
	public CacheModel<tj.zakazchiki.model.zakazchiki> toCacheModel();

	@Override
	public tj.zakazchiki.model.zakazchiki toEscapedModel();

	@Override
	public tj.zakazchiki.model.zakazchiki toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}