/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.prochaja.informacija.dlja.zajavki.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import tj.prochaja.informacija.dlja.zajavki.model.prochaja_informacija_dlja_zajavki;
import tj.prochaja.informacija.dlja.zajavki.model.prochaja_informacija_dlja_zajavkiModel;
import tj.prochaja.informacija.dlja.zajavki.model.prochaja_informacija_dlja_zajavkiSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the prochaja_informacija_dlja_zajavki service. Represents a row in the &quot;sapp.prochaja_informacija_dlja_zajavki&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link prochaja_informacija_dlja_zajavkiModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link prochaja_informacija_dlja_zajavkiImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see prochaja_informacija_dlja_zajavkiImpl
 * @see prochaja_informacija_dlja_zajavki
 * @see prochaja_informacija_dlja_zajavkiModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class prochaja_informacija_dlja_zajavkiModelImpl extends BaseModelImpl<prochaja_informacija_dlja_zajavki>
	implements prochaja_informacija_dlja_zajavkiModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a prochaja_informacija_dlja_zajavki model instance should use the {@link prochaja_informacija_dlja_zajavki} interface instead.
	 */
	public static final String TABLE_NAME = "sapp.prochaja_informacija_dlja_zajavki";
	public static final Object[][] TABLE_COLUMNS = {
			{ "cena_postavki", Types.VARCHAR },
			{ "cena_postavki_soglasno_zakazchiku", Types.BIGINT },
			{ "data_sozdanija", Types.TIMESTAMP },
			{ "izvewenie_id", Types.BIGINT },
			{ "lot_id", Types.BIGINT },
			{ "mesto_postavki", Types.VARCHAR },
			{ "mesto_postavki_soglasno_zakazchiku", Types.BIGINT },
			{ "oplata", Types.VARCHAR },
			{ "oplata_soglasno_zakazchiku", Types.BIGINT },
			{ "postavwik_id", Types.BIGINT },
			{ "prochaja_informacija_dlja_zajavki_id", Types.BIGINT },
			{ "soputstvujuwie_uslovija", Types.VARCHAR },
			{ "soputstvujuwie_uslovija_soglasno_zakazchiku", Types.BIGINT },
			{ "sozdal", Types.BIGINT },
			{ "srok_dejstvija", Types.VARCHAR },
			{ "srok_dejstvija_soglasno_zakazchiku", Types.BIGINT },
			{ "srok_ispolnenija_zajavki", Types.VARCHAR },
			{ "srok_ispolnenija_zajavki_soglasno_zakazchiku", Types.BIGINT },
			{ "srok_obespechenija_zajavki", Types.VARCHAR },
			{ "srok_obespechenija_zajavki_soglasno_zakazchiku", Types.BIGINT },
			{ "srok_postavki", Types.VARCHAR },
			{ "srok_postavki_soglasno_zakazchiku", Types.BIGINT }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("cena_postavki", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("cena_postavki_soglasno_zakazchiku", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("data_sozdanija", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("izvewenie_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("lot_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("mesto_postavki", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("mesto_postavki_soglasno_zakazchiku", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("oplata", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("oplata_soglasno_zakazchiku", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("postavwik_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("prochaja_informacija_dlja_zajavki_id",
			Types.BIGINT);
		TABLE_COLUMNS_MAP.put("soputstvujuwie_uslovija", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("soputstvujuwie_uslovija_soglasno_zakazchiku",
			Types.BIGINT);
		TABLE_COLUMNS_MAP.put("sozdal", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("srok_dejstvija", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("srok_dejstvija_soglasno_zakazchiku", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("srok_ispolnenija_zajavki", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("srok_ispolnenija_zajavki_soglasno_zakazchiku",
			Types.BIGINT);
		TABLE_COLUMNS_MAP.put("srok_obespechenija_zajavki", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("srok_obespechenija_zajavki_soglasno_zakazchiku",
			Types.BIGINT);
		TABLE_COLUMNS_MAP.put("srok_postavki", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("srok_postavki_soglasno_zakazchiku", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE = "create table sapp.prochaja_informacija_dlja_zajavki (cena_postavki VARCHAR(75) null,cena_postavki_soglasno_zakazchiku LONG,data_sozdanija DATE null,izvewenie_id LONG,lot_id LONG,mesto_postavki VARCHAR(75) null,mesto_postavki_soglasno_zakazchiku LONG,oplata VARCHAR(75) null,oplata_soglasno_zakazchiku LONG,postavwik_id LONG,prochaja_informacija_dlja_zajavki_id LONG not null primary key,soputstvujuwie_uslovija VARCHAR(75) null,soputstvujuwie_uslovija_soglasno_zakazchiku LONG,sozdal LONG,srok_dejstvija VARCHAR(75) null,srok_dejstvija_soglasno_zakazchiku LONG,srok_ispolnenija_zajavki VARCHAR(75) null,srok_ispolnenija_zajavki_soglasno_zakazchiku LONG,srok_obespechenija_zajavki VARCHAR(75) null,srok_obespechenija_zajavki_soglasno_zakazchiku LONG,srok_postavki VARCHAR(75) null,srok_postavki_soglasno_zakazchiku LONG)";
	public static final String TABLE_SQL_DROP = "drop table sapp.prochaja_informacija_dlja_zajavki";
	public static final String ORDER_BY_JPQL = " ORDER BY prochaja_informacija_dlja_zajavki.prochaja_informacija_dlja_zajavki_id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY sapp.prochaja_informacija_dlja_zajavki.prochaja_informacija_dlja_zajavki_id ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(tj.prochaja.informacija.dlja.zajavki.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.tj.prochaja.informacija.dlja.zajavki.model.prochaja_informacija_dlja_zajavki"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(tj.prochaja.informacija.dlja.zajavki.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.tj.prochaja.informacija.dlja.zajavki.model.prochaja_informacija_dlja_zajavki"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static prochaja_informacija_dlja_zajavki toModel(
		prochaja_informacija_dlja_zajavkiSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		prochaja_informacija_dlja_zajavki model = new prochaja_informacija_dlja_zajavkiImpl();

		model.setCena_postavki(soapModel.getCena_postavki());
		model.setCena_postavki_soglasno_zakazchiku(soapModel.getCena_postavki_soglasno_zakazchiku());
		model.setData_sozdanija(soapModel.getData_sozdanija());
		model.setIzvewenie_id(soapModel.getIzvewenie_id());
		model.setLot_id(soapModel.getLot_id());
		model.setMesto_postavki(soapModel.getMesto_postavki());
		model.setMesto_postavki_soglasno_zakazchiku(soapModel.getMesto_postavki_soglasno_zakazchiku());
		model.setOplata(soapModel.getOplata());
		model.setOplata_soglasno_zakazchiku(soapModel.getOplata_soglasno_zakazchiku());
		model.setPostavwik_id(soapModel.getPostavwik_id());
		model.setProchaja_informacija_dlja_zajavki_id(soapModel.getProchaja_informacija_dlja_zajavki_id());
		model.setSoputstvujuwie_uslovija(soapModel.getSoputstvujuwie_uslovija());
		model.setSoputstvujuwie_uslovija_soglasno_zakazchiku(soapModel.getSoputstvujuwie_uslovija_soglasno_zakazchiku());
		model.setSozdal(soapModel.getSozdal());
		model.setSrok_dejstvija(soapModel.getSrok_dejstvija());
		model.setSrok_dejstvija_soglasno_zakazchiku(soapModel.getSrok_dejstvija_soglasno_zakazchiku());
		model.setSrok_ispolnenija_zajavki(soapModel.getSrok_ispolnenija_zajavki());
		model.setSrok_ispolnenija_zajavki_soglasno_zakazchiku(soapModel.getSrok_ispolnenija_zajavki_soglasno_zakazchiku());
		model.setSrok_obespechenija_zajavki(soapModel.getSrok_obespechenija_zajavki());
		model.setSrok_obespechenija_zajavki_soglasno_zakazchiku(soapModel.getSrok_obespechenija_zajavki_soglasno_zakazchiku());
		model.setSrok_postavki(soapModel.getSrok_postavki());
		model.setSrok_postavki_soglasno_zakazchiku(soapModel.getSrok_postavki_soglasno_zakazchiku());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<prochaja_informacija_dlja_zajavki> toModels(
		prochaja_informacija_dlja_zajavkiSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<prochaja_informacija_dlja_zajavki> models = new ArrayList<prochaja_informacija_dlja_zajavki>(soapModels.length);

		for (prochaja_informacija_dlja_zajavkiSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(tj.prochaja.informacija.dlja.zajavki.service.util.ServiceProps.get(
				"lock.expiration.time.tj.prochaja.informacija.dlja.zajavki.model.prochaja_informacija_dlja_zajavki"));

	public prochaja_informacija_dlja_zajavkiModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _prochaja_informacija_dlja_zajavki_id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setProchaja_informacija_dlja_zajavki_id(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _prochaja_informacija_dlja_zajavki_id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return prochaja_informacija_dlja_zajavki.class;
	}

	@Override
	public String getModelClassName() {
		return prochaja_informacija_dlja_zajavki.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("cena_postavki", getCena_postavki());
		attributes.put("cena_postavki_soglasno_zakazchiku",
			getCena_postavki_soglasno_zakazchiku());
		attributes.put("data_sozdanija", getData_sozdanija());
		attributes.put("izvewenie_id", getIzvewenie_id());
		attributes.put("lot_id", getLot_id());
		attributes.put("mesto_postavki", getMesto_postavki());
		attributes.put("mesto_postavki_soglasno_zakazchiku",
			getMesto_postavki_soglasno_zakazchiku());
		attributes.put("oplata", getOplata());
		attributes.put("oplata_soglasno_zakazchiku",
			getOplata_soglasno_zakazchiku());
		attributes.put("postavwik_id", getPostavwik_id());
		attributes.put("prochaja_informacija_dlja_zajavki_id",
			getProchaja_informacija_dlja_zajavki_id());
		attributes.put("soputstvujuwie_uslovija", getSoputstvujuwie_uslovija());
		attributes.put("soputstvujuwie_uslovija_soglasno_zakazchiku",
			getSoputstvujuwie_uslovija_soglasno_zakazchiku());
		attributes.put("sozdal", getSozdal());
		attributes.put("srok_dejstvija", getSrok_dejstvija());
		attributes.put("srok_dejstvija_soglasno_zakazchiku",
			getSrok_dejstvija_soglasno_zakazchiku());
		attributes.put("srok_ispolnenija_zajavki", getSrok_ispolnenija_zajavki());
		attributes.put("srok_ispolnenija_zajavki_soglasno_zakazchiku",
			getSrok_ispolnenija_zajavki_soglasno_zakazchiku());
		attributes.put("srok_obespechenija_zajavki",
			getSrok_obespechenija_zajavki());
		attributes.put("srok_obespechenija_zajavki_soglasno_zakazchiku",
			getSrok_obespechenija_zajavki_soglasno_zakazchiku());
		attributes.put("srok_postavki", getSrok_postavki());
		attributes.put("srok_postavki_soglasno_zakazchiku",
			getSrok_postavki_soglasno_zakazchiku());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String cena_postavki = (String)attributes.get("cena_postavki");

		if (cena_postavki != null) {
			setCena_postavki(cena_postavki);
		}

		Long cena_postavki_soglasno_zakazchiku = (Long)attributes.get(
				"cena_postavki_soglasno_zakazchiku");

		if (cena_postavki_soglasno_zakazchiku != null) {
			setCena_postavki_soglasno_zakazchiku(cena_postavki_soglasno_zakazchiku);
		}

		Date data_sozdanija = (Date)attributes.get("data_sozdanija");

		if (data_sozdanija != null) {
			setData_sozdanija(data_sozdanija);
		}

		Long izvewenie_id = (Long)attributes.get("izvewenie_id");

		if (izvewenie_id != null) {
			setIzvewenie_id(izvewenie_id);
		}

		Long lot_id = (Long)attributes.get("lot_id");

		if (lot_id != null) {
			setLot_id(lot_id);
		}

		String mesto_postavki = (String)attributes.get("mesto_postavki");

		if (mesto_postavki != null) {
			setMesto_postavki(mesto_postavki);
		}

		Long mesto_postavki_soglasno_zakazchiku = (Long)attributes.get(
				"mesto_postavki_soglasno_zakazchiku");

		if (mesto_postavki_soglasno_zakazchiku != null) {
			setMesto_postavki_soglasno_zakazchiku(mesto_postavki_soglasno_zakazchiku);
		}

		String oplata = (String)attributes.get("oplata");

		if (oplata != null) {
			setOplata(oplata);
		}

		Long oplata_soglasno_zakazchiku = (Long)attributes.get(
				"oplata_soglasno_zakazchiku");

		if (oplata_soglasno_zakazchiku != null) {
			setOplata_soglasno_zakazchiku(oplata_soglasno_zakazchiku);
		}

		Long postavwik_id = (Long)attributes.get("postavwik_id");

		if (postavwik_id != null) {
			setPostavwik_id(postavwik_id);
		}

		Long prochaja_informacija_dlja_zajavki_id = (Long)attributes.get(
				"prochaja_informacija_dlja_zajavki_id");

		if (prochaja_informacija_dlja_zajavki_id != null) {
			setProchaja_informacija_dlja_zajavki_id(prochaja_informacija_dlja_zajavki_id);
		}

		String soputstvujuwie_uslovija = (String)attributes.get(
				"soputstvujuwie_uslovija");

		if (soputstvujuwie_uslovija != null) {
			setSoputstvujuwie_uslovija(soputstvujuwie_uslovija);
		}

		Long soputstvujuwie_uslovija_soglasno_zakazchiku = (Long)attributes.get(
				"soputstvujuwie_uslovija_soglasno_zakazchiku");

		if (soputstvujuwie_uslovija_soglasno_zakazchiku != null) {
			setSoputstvujuwie_uslovija_soglasno_zakazchiku(soputstvujuwie_uslovija_soglasno_zakazchiku);
		}

		Long sozdal = (Long)attributes.get("sozdal");

		if (sozdal != null) {
			setSozdal(sozdal);
		}

		String srok_dejstvija = (String)attributes.get("srok_dejstvija");

		if (srok_dejstvija != null) {
			setSrok_dejstvija(srok_dejstvija);
		}

		Long srok_dejstvija_soglasno_zakazchiku = (Long)attributes.get(
				"srok_dejstvija_soglasno_zakazchiku");

		if (srok_dejstvija_soglasno_zakazchiku != null) {
			setSrok_dejstvija_soglasno_zakazchiku(srok_dejstvija_soglasno_zakazchiku);
		}

		String srok_ispolnenija_zajavki = (String)attributes.get(
				"srok_ispolnenija_zajavki");

		if (srok_ispolnenija_zajavki != null) {
			setSrok_ispolnenija_zajavki(srok_ispolnenija_zajavki);
		}

		Long srok_ispolnenija_zajavki_soglasno_zakazchiku = (Long)attributes.get(
				"srok_ispolnenija_zajavki_soglasno_zakazchiku");

		if (srok_ispolnenija_zajavki_soglasno_zakazchiku != null) {
			setSrok_ispolnenija_zajavki_soglasno_zakazchiku(srok_ispolnenija_zajavki_soglasno_zakazchiku);
		}

		String srok_obespechenija_zajavki = (String)attributes.get(
				"srok_obespechenija_zajavki");

		if (srok_obespechenija_zajavki != null) {
			setSrok_obespechenija_zajavki(srok_obespechenija_zajavki);
		}

		Long srok_obespechenija_zajavki_soglasno_zakazchiku = (Long)attributes.get(
				"srok_obespechenija_zajavki_soglasno_zakazchiku");

		if (srok_obespechenija_zajavki_soglasno_zakazchiku != null) {
			setSrok_obespechenija_zajavki_soglasno_zakazchiku(srok_obespechenija_zajavki_soglasno_zakazchiku);
		}

		String srok_postavki = (String)attributes.get("srok_postavki");

		if (srok_postavki != null) {
			setSrok_postavki(srok_postavki);
		}

		Long srok_postavki_soglasno_zakazchiku = (Long)attributes.get(
				"srok_postavki_soglasno_zakazchiku");

		if (srok_postavki_soglasno_zakazchiku != null) {
			setSrok_postavki_soglasno_zakazchiku(srok_postavki_soglasno_zakazchiku);
		}
	}

	@JSON
	@Override
	public String getCena_postavki() {
		if (_cena_postavki == null) {
			return StringPool.BLANK;
		}
		else {
			return _cena_postavki;
		}
	}

	@Override
	public void setCena_postavki(String cena_postavki) {
		_cena_postavki = cena_postavki;
	}

	@JSON
	@Override
	public long getCena_postavki_soglasno_zakazchiku() {
		return _cena_postavki_soglasno_zakazchiku;
	}

	@Override
	public void setCena_postavki_soglasno_zakazchiku(
		long cena_postavki_soglasno_zakazchiku) {
		_cena_postavki_soglasno_zakazchiku = cena_postavki_soglasno_zakazchiku;
	}

	@JSON
	@Override
	public Date getData_sozdanija() {
		return _data_sozdanija;
	}

	@Override
	public void setData_sozdanija(Date data_sozdanija) {
		_data_sozdanija = data_sozdanija;
	}

	@JSON
	@Override
	public long getIzvewenie_id() {
		return _izvewenie_id;
	}

	@Override
	public void setIzvewenie_id(long izvewenie_id) {
		_izvewenie_id = izvewenie_id;
	}

	@JSON
	@Override
	public long getLot_id() {
		return _lot_id;
	}

	@Override
	public void setLot_id(long lot_id) {
		_lot_id = lot_id;
	}

	@JSON
	@Override
	public String getMesto_postavki() {
		if (_mesto_postavki == null) {
			return StringPool.BLANK;
		}
		else {
			return _mesto_postavki;
		}
	}

	@Override
	public void setMesto_postavki(String mesto_postavki) {
		_mesto_postavki = mesto_postavki;
	}

	@JSON
	@Override
	public long getMesto_postavki_soglasno_zakazchiku() {
		return _mesto_postavki_soglasno_zakazchiku;
	}

	@Override
	public void setMesto_postavki_soglasno_zakazchiku(
		long mesto_postavki_soglasno_zakazchiku) {
		_mesto_postavki_soglasno_zakazchiku = mesto_postavki_soglasno_zakazchiku;
	}

	@JSON
	@Override
	public String getOplata() {
		if (_oplata == null) {
			return StringPool.BLANK;
		}
		else {
			return _oplata;
		}
	}

	@Override
	public void setOplata(String oplata) {
		_oplata = oplata;
	}

	@JSON
	@Override
	public long getOplata_soglasno_zakazchiku() {
		return _oplata_soglasno_zakazchiku;
	}

	@Override
	public void setOplata_soglasno_zakazchiku(long oplata_soglasno_zakazchiku) {
		_oplata_soglasno_zakazchiku = oplata_soglasno_zakazchiku;
	}

	@JSON
	@Override
	public long getPostavwik_id() {
		return _postavwik_id;
	}

	@Override
	public void setPostavwik_id(long postavwik_id) {
		_postavwik_id = postavwik_id;
	}

	@JSON
	@Override
	public long getProchaja_informacija_dlja_zajavki_id() {
		return _prochaja_informacija_dlja_zajavki_id;
	}

	@Override
	public void setProchaja_informacija_dlja_zajavki_id(
		long prochaja_informacija_dlja_zajavki_id) {
		_prochaja_informacija_dlja_zajavki_id = prochaja_informacija_dlja_zajavki_id;
	}

	@JSON
	@Override
	public String getSoputstvujuwie_uslovija() {
		if (_soputstvujuwie_uslovija == null) {
			return StringPool.BLANK;
		}
		else {
			return _soputstvujuwie_uslovija;
		}
	}

	@Override
	public void setSoputstvujuwie_uslovija(String soputstvujuwie_uslovija) {
		_soputstvujuwie_uslovija = soputstvujuwie_uslovija;
	}

	@JSON
	@Override
	public long getSoputstvujuwie_uslovija_soglasno_zakazchiku() {
		return _soputstvujuwie_uslovija_soglasno_zakazchiku;
	}

	@Override
	public void setSoputstvujuwie_uslovija_soglasno_zakazchiku(
		long soputstvujuwie_uslovija_soglasno_zakazchiku) {
		_soputstvujuwie_uslovija_soglasno_zakazchiku = soputstvujuwie_uslovija_soglasno_zakazchiku;
	}

	@JSON
	@Override
	public long getSozdal() {
		return _sozdal;
	}

	@Override
	public void setSozdal(long sozdal) {
		_sozdal = sozdal;
	}

	@JSON
	@Override
	public String getSrok_dejstvija() {
		if (_srok_dejstvija == null) {
			return StringPool.BLANK;
		}
		else {
			return _srok_dejstvija;
		}
	}

	@Override
	public void setSrok_dejstvija(String srok_dejstvija) {
		_srok_dejstvija = srok_dejstvija;
	}

	@JSON
	@Override
	public long getSrok_dejstvija_soglasno_zakazchiku() {
		return _srok_dejstvija_soglasno_zakazchiku;
	}

	@Override
	public void setSrok_dejstvija_soglasno_zakazchiku(
		long srok_dejstvija_soglasno_zakazchiku) {
		_srok_dejstvija_soglasno_zakazchiku = srok_dejstvija_soglasno_zakazchiku;
	}

	@JSON
	@Override
	public String getSrok_ispolnenija_zajavki() {
		if (_srok_ispolnenija_zajavki == null) {
			return StringPool.BLANK;
		}
		else {
			return _srok_ispolnenija_zajavki;
		}
	}

	@Override
	public void setSrok_ispolnenija_zajavki(String srok_ispolnenija_zajavki) {
		_srok_ispolnenija_zajavki = srok_ispolnenija_zajavki;
	}

	@JSON
	@Override
	public long getSrok_ispolnenija_zajavki_soglasno_zakazchiku() {
		return _srok_ispolnenija_zajavki_soglasno_zakazchiku;
	}

	@Override
	public void setSrok_ispolnenija_zajavki_soglasno_zakazchiku(
		long srok_ispolnenija_zajavki_soglasno_zakazchiku) {
		_srok_ispolnenija_zajavki_soglasno_zakazchiku = srok_ispolnenija_zajavki_soglasno_zakazchiku;
	}

	@JSON
	@Override
	public String getSrok_obespechenija_zajavki() {
		if (_srok_obespechenija_zajavki == null) {
			return StringPool.BLANK;
		}
		else {
			return _srok_obespechenija_zajavki;
		}
	}

	@Override
	public void setSrok_obespechenija_zajavki(String srok_obespechenija_zajavki) {
		_srok_obespechenija_zajavki = srok_obespechenija_zajavki;
	}

	@JSON
	@Override
	public long getSrok_obespechenija_zajavki_soglasno_zakazchiku() {
		return _srok_obespechenija_zajavki_soglasno_zakazchiku;
	}

	@Override
	public void setSrok_obespechenija_zajavki_soglasno_zakazchiku(
		long srok_obespechenija_zajavki_soglasno_zakazchiku) {
		_srok_obespechenija_zajavki_soglasno_zakazchiku = srok_obespechenija_zajavki_soglasno_zakazchiku;
	}

	@JSON
	@Override
	public String getSrok_postavki() {
		if (_srok_postavki == null) {
			return StringPool.BLANK;
		}
		else {
			return _srok_postavki;
		}
	}

	@Override
	public void setSrok_postavki(String srok_postavki) {
		_srok_postavki = srok_postavki;
	}

	@JSON
	@Override
	public long getSrok_postavki_soglasno_zakazchiku() {
		return _srok_postavki_soglasno_zakazchiku;
	}

	@Override
	public void setSrok_postavki_soglasno_zakazchiku(
		long srok_postavki_soglasno_zakazchiku) {
		_srok_postavki_soglasno_zakazchiku = srok_postavki_soglasno_zakazchiku;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			prochaja_informacija_dlja_zajavki.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public prochaja_informacija_dlja_zajavki toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (prochaja_informacija_dlja_zajavki)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		prochaja_informacija_dlja_zajavkiImpl prochaja_informacija_dlja_zajavkiImpl =
			new prochaja_informacija_dlja_zajavkiImpl();

		prochaja_informacija_dlja_zajavkiImpl.setCena_postavki(getCena_postavki());
		prochaja_informacija_dlja_zajavkiImpl.setCena_postavki_soglasno_zakazchiku(getCena_postavki_soglasno_zakazchiku());
		prochaja_informacija_dlja_zajavkiImpl.setData_sozdanija(getData_sozdanija());
		prochaja_informacija_dlja_zajavkiImpl.setIzvewenie_id(getIzvewenie_id());
		prochaja_informacija_dlja_zajavkiImpl.setLot_id(getLot_id());
		prochaja_informacija_dlja_zajavkiImpl.setMesto_postavki(getMesto_postavki());
		prochaja_informacija_dlja_zajavkiImpl.setMesto_postavki_soglasno_zakazchiku(getMesto_postavki_soglasno_zakazchiku());
		prochaja_informacija_dlja_zajavkiImpl.setOplata(getOplata());
		prochaja_informacija_dlja_zajavkiImpl.setOplata_soglasno_zakazchiku(getOplata_soglasno_zakazchiku());
		prochaja_informacija_dlja_zajavkiImpl.setPostavwik_id(getPostavwik_id());
		prochaja_informacija_dlja_zajavkiImpl.setProchaja_informacija_dlja_zajavki_id(getProchaja_informacija_dlja_zajavki_id());
		prochaja_informacija_dlja_zajavkiImpl.setSoputstvujuwie_uslovija(getSoputstvujuwie_uslovija());
		prochaja_informacija_dlja_zajavkiImpl.setSoputstvujuwie_uslovija_soglasno_zakazchiku(getSoputstvujuwie_uslovija_soglasno_zakazchiku());
		prochaja_informacija_dlja_zajavkiImpl.setSozdal(getSozdal());
		prochaja_informacija_dlja_zajavkiImpl.setSrok_dejstvija(getSrok_dejstvija());
		prochaja_informacija_dlja_zajavkiImpl.setSrok_dejstvija_soglasno_zakazchiku(getSrok_dejstvija_soglasno_zakazchiku());
		prochaja_informacija_dlja_zajavkiImpl.setSrok_ispolnenija_zajavki(getSrok_ispolnenija_zajavki());
		prochaja_informacija_dlja_zajavkiImpl.setSrok_ispolnenija_zajavki_soglasno_zakazchiku(getSrok_ispolnenija_zajavki_soglasno_zakazchiku());
		prochaja_informacija_dlja_zajavkiImpl.setSrok_obespechenija_zajavki(getSrok_obespechenija_zajavki());
		prochaja_informacija_dlja_zajavkiImpl.setSrok_obespechenija_zajavki_soglasno_zakazchiku(getSrok_obespechenija_zajavki_soglasno_zakazchiku());
		prochaja_informacija_dlja_zajavkiImpl.setSrok_postavki(getSrok_postavki());
		prochaja_informacija_dlja_zajavkiImpl.setSrok_postavki_soglasno_zakazchiku(getSrok_postavki_soglasno_zakazchiku());

		prochaja_informacija_dlja_zajavkiImpl.resetOriginalValues();

		return prochaja_informacija_dlja_zajavkiImpl;
	}

	@Override
	public int compareTo(
		prochaja_informacija_dlja_zajavki prochaja_informacija_dlja_zajavki) {
		long primaryKey = prochaja_informacija_dlja_zajavki.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof prochaja_informacija_dlja_zajavki)) {
			return false;
		}

		prochaja_informacija_dlja_zajavki prochaja_informacija_dlja_zajavki = (prochaja_informacija_dlja_zajavki)obj;

		long primaryKey = prochaja_informacija_dlja_zajavki.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<prochaja_informacija_dlja_zajavki> toCacheModel() {
		prochaja_informacija_dlja_zajavkiCacheModel prochaja_informacija_dlja_zajavkiCacheModel =
			new prochaja_informacija_dlja_zajavkiCacheModel();

		prochaja_informacija_dlja_zajavkiCacheModel.cena_postavki = getCena_postavki();

		String cena_postavki = prochaja_informacija_dlja_zajavkiCacheModel.cena_postavki;

		if ((cena_postavki != null) && (cena_postavki.length() == 0)) {
			prochaja_informacija_dlja_zajavkiCacheModel.cena_postavki = null;
		}

		prochaja_informacija_dlja_zajavkiCacheModel.cena_postavki_soglasno_zakazchiku = getCena_postavki_soglasno_zakazchiku();

		Date data_sozdanija = getData_sozdanija();

		if (data_sozdanija != null) {
			prochaja_informacija_dlja_zajavkiCacheModel.data_sozdanija = data_sozdanija.getTime();
		}
		else {
			prochaja_informacija_dlja_zajavkiCacheModel.data_sozdanija = Long.MIN_VALUE;
		}

		prochaja_informacija_dlja_zajavkiCacheModel.izvewenie_id = getIzvewenie_id();

		prochaja_informacija_dlja_zajavkiCacheModel.lot_id = getLot_id();

		prochaja_informacija_dlja_zajavkiCacheModel.mesto_postavki = getMesto_postavki();

		String mesto_postavki = prochaja_informacija_dlja_zajavkiCacheModel.mesto_postavki;

		if ((mesto_postavki != null) && (mesto_postavki.length() == 0)) {
			prochaja_informacija_dlja_zajavkiCacheModel.mesto_postavki = null;
		}

		prochaja_informacija_dlja_zajavkiCacheModel.mesto_postavki_soglasno_zakazchiku = getMesto_postavki_soglasno_zakazchiku();

		prochaja_informacija_dlja_zajavkiCacheModel.oplata = getOplata();

		String oplata = prochaja_informacija_dlja_zajavkiCacheModel.oplata;

		if ((oplata != null) && (oplata.length() == 0)) {
			prochaja_informacija_dlja_zajavkiCacheModel.oplata = null;
		}

		prochaja_informacija_dlja_zajavkiCacheModel.oplata_soglasno_zakazchiku = getOplata_soglasno_zakazchiku();

		prochaja_informacija_dlja_zajavkiCacheModel.postavwik_id = getPostavwik_id();

		prochaja_informacija_dlja_zajavkiCacheModel.prochaja_informacija_dlja_zajavki_id = getProchaja_informacija_dlja_zajavki_id();

		prochaja_informacija_dlja_zajavkiCacheModel.soputstvujuwie_uslovija = getSoputstvujuwie_uslovija();

		String soputstvujuwie_uslovija = prochaja_informacija_dlja_zajavkiCacheModel.soputstvujuwie_uslovija;

		if ((soputstvujuwie_uslovija != null) &&
				(soputstvujuwie_uslovija.length() == 0)) {
			prochaja_informacija_dlja_zajavkiCacheModel.soputstvujuwie_uslovija = null;
		}

		prochaja_informacija_dlja_zajavkiCacheModel.soputstvujuwie_uslovija_soglasno_zakazchiku = getSoputstvujuwie_uslovija_soglasno_zakazchiku();

		prochaja_informacija_dlja_zajavkiCacheModel.sozdal = getSozdal();

		prochaja_informacija_dlja_zajavkiCacheModel.srok_dejstvija = getSrok_dejstvija();

		String srok_dejstvija = prochaja_informacija_dlja_zajavkiCacheModel.srok_dejstvija;

		if ((srok_dejstvija != null) && (srok_dejstvija.length() == 0)) {
			prochaja_informacija_dlja_zajavkiCacheModel.srok_dejstvija = null;
		}

		prochaja_informacija_dlja_zajavkiCacheModel.srok_dejstvija_soglasno_zakazchiku = getSrok_dejstvija_soglasno_zakazchiku();

		prochaja_informacija_dlja_zajavkiCacheModel.srok_ispolnenija_zajavki = getSrok_ispolnenija_zajavki();

		String srok_ispolnenija_zajavki = prochaja_informacija_dlja_zajavkiCacheModel.srok_ispolnenija_zajavki;

		if ((srok_ispolnenija_zajavki != null) &&
				(srok_ispolnenija_zajavki.length() == 0)) {
			prochaja_informacija_dlja_zajavkiCacheModel.srok_ispolnenija_zajavki = null;
		}

		prochaja_informacija_dlja_zajavkiCacheModel.srok_ispolnenija_zajavki_soglasno_zakazchiku = getSrok_ispolnenija_zajavki_soglasno_zakazchiku();

		prochaja_informacija_dlja_zajavkiCacheModel.srok_obespechenija_zajavki = getSrok_obespechenija_zajavki();

		String srok_obespechenija_zajavki = prochaja_informacija_dlja_zajavkiCacheModel.srok_obespechenija_zajavki;

		if ((srok_obespechenija_zajavki != null) &&
				(srok_obespechenija_zajavki.length() == 0)) {
			prochaja_informacija_dlja_zajavkiCacheModel.srok_obespechenija_zajavki = null;
		}

		prochaja_informacija_dlja_zajavkiCacheModel.srok_obespechenija_zajavki_soglasno_zakazchiku = getSrok_obespechenija_zajavki_soglasno_zakazchiku();

		prochaja_informacija_dlja_zajavkiCacheModel.srok_postavki = getSrok_postavki();

		String srok_postavki = prochaja_informacija_dlja_zajavkiCacheModel.srok_postavki;

		if ((srok_postavki != null) && (srok_postavki.length() == 0)) {
			prochaja_informacija_dlja_zajavkiCacheModel.srok_postavki = null;
		}

		prochaja_informacija_dlja_zajavkiCacheModel.srok_postavki_soglasno_zakazchiku = getSrok_postavki_soglasno_zakazchiku();

		return prochaja_informacija_dlja_zajavkiCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(45);

		sb.append("{cena_postavki=");
		sb.append(getCena_postavki());
		sb.append(", cena_postavki_soglasno_zakazchiku=");
		sb.append(getCena_postavki_soglasno_zakazchiku());
		sb.append(", data_sozdanija=");
		sb.append(getData_sozdanija());
		sb.append(", izvewenie_id=");
		sb.append(getIzvewenie_id());
		sb.append(", lot_id=");
		sb.append(getLot_id());
		sb.append(", mesto_postavki=");
		sb.append(getMesto_postavki());
		sb.append(", mesto_postavki_soglasno_zakazchiku=");
		sb.append(getMesto_postavki_soglasno_zakazchiku());
		sb.append(", oplata=");
		sb.append(getOplata());
		sb.append(", oplata_soglasno_zakazchiku=");
		sb.append(getOplata_soglasno_zakazchiku());
		sb.append(", postavwik_id=");
		sb.append(getPostavwik_id());
		sb.append(", prochaja_informacija_dlja_zajavki_id=");
		sb.append(getProchaja_informacija_dlja_zajavki_id());
		sb.append(", soputstvujuwie_uslovija=");
		sb.append(getSoputstvujuwie_uslovija());
		sb.append(", soputstvujuwie_uslovija_soglasno_zakazchiku=");
		sb.append(getSoputstvujuwie_uslovija_soglasno_zakazchiku());
		sb.append(", sozdal=");
		sb.append(getSozdal());
		sb.append(", srok_dejstvija=");
		sb.append(getSrok_dejstvija());
		sb.append(", srok_dejstvija_soglasno_zakazchiku=");
		sb.append(getSrok_dejstvija_soglasno_zakazchiku());
		sb.append(", srok_ispolnenija_zajavki=");
		sb.append(getSrok_ispolnenija_zajavki());
		sb.append(", srok_ispolnenija_zajavki_soglasno_zakazchiku=");
		sb.append(getSrok_ispolnenija_zajavki_soglasno_zakazchiku());
		sb.append(", srok_obespechenija_zajavki=");
		sb.append(getSrok_obespechenija_zajavki());
		sb.append(", srok_obespechenija_zajavki_soglasno_zakazchiku=");
		sb.append(getSrok_obespechenija_zajavki_soglasno_zakazchiku());
		sb.append(", srok_postavki=");
		sb.append(getSrok_postavki());
		sb.append(", srok_postavki_soglasno_zakazchiku=");
		sb.append(getSrok_postavki_soglasno_zakazchiku());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(70);

		sb.append("<model><model-name>");
		sb.append(
			"tj.prochaja.informacija.dlja.zajavki.model.prochaja_informacija_dlja_zajavki");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>cena_postavki</column-name><column-value><![CDATA[");
		sb.append(getCena_postavki());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>cena_postavki_soglasno_zakazchiku</column-name><column-value><![CDATA[");
		sb.append(getCena_postavki_soglasno_zakazchiku());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>data_sozdanija</column-name><column-value><![CDATA[");
		sb.append(getData_sozdanija());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>izvewenie_id</column-name><column-value><![CDATA[");
		sb.append(getIzvewenie_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>lot_id</column-name><column-value><![CDATA[");
		sb.append(getLot_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>mesto_postavki</column-name><column-value><![CDATA[");
		sb.append(getMesto_postavki());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>mesto_postavki_soglasno_zakazchiku</column-name><column-value><![CDATA[");
		sb.append(getMesto_postavki_soglasno_zakazchiku());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>oplata</column-name><column-value><![CDATA[");
		sb.append(getOplata());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>oplata_soglasno_zakazchiku</column-name><column-value><![CDATA[");
		sb.append(getOplata_soglasno_zakazchiku());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>postavwik_id</column-name><column-value><![CDATA[");
		sb.append(getPostavwik_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>prochaja_informacija_dlja_zajavki_id</column-name><column-value><![CDATA[");
		sb.append(getProchaja_informacija_dlja_zajavki_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soputstvujuwie_uslovija</column-name><column-value><![CDATA[");
		sb.append(getSoputstvujuwie_uslovija());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soputstvujuwie_uslovija_soglasno_zakazchiku</column-name><column-value><![CDATA[");
		sb.append(getSoputstvujuwie_uslovija_soglasno_zakazchiku());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sozdal</column-name><column-value><![CDATA[");
		sb.append(getSozdal());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>srok_dejstvija</column-name><column-value><![CDATA[");
		sb.append(getSrok_dejstvija());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>srok_dejstvija_soglasno_zakazchiku</column-name><column-value><![CDATA[");
		sb.append(getSrok_dejstvija_soglasno_zakazchiku());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>srok_ispolnenija_zajavki</column-name><column-value><![CDATA[");
		sb.append(getSrok_ispolnenija_zajavki());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>srok_ispolnenija_zajavki_soglasno_zakazchiku</column-name><column-value><![CDATA[");
		sb.append(getSrok_ispolnenija_zajavki_soglasno_zakazchiku());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>srok_obespechenija_zajavki</column-name><column-value><![CDATA[");
		sb.append(getSrok_obespechenija_zajavki());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>srok_obespechenija_zajavki_soglasno_zakazchiku</column-name><column-value><![CDATA[");
		sb.append(getSrok_obespechenija_zajavki_soglasno_zakazchiku());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>srok_postavki</column-name><column-value><![CDATA[");
		sb.append(getSrok_postavki());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>srok_postavki_soglasno_zakazchiku</column-name><column-value><![CDATA[");
		sb.append(getSrok_postavki_soglasno_zakazchiku());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = prochaja_informacija_dlja_zajavki.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			prochaja_informacija_dlja_zajavki.class
		};
	private String _cena_postavki;
	private long _cena_postavki_soglasno_zakazchiku;
	private Date _data_sozdanija;
	private long _izvewenie_id;
	private long _lot_id;
	private String _mesto_postavki;
	private long _mesto_postavki_soglasno_zakazchiku;
	private String _oplata;
	private long _oplata_soglasno_zakazchiku;
	private long _postavwik_id;
	private long _prochaja_informacija_dlja_zajavki_id;
	private String _soputstvujuwie_uslovija;
	private long _soputstvujuwie_uslovija_soglasno_zakazchiku;
	private long _sozdal;
	private String _srok_dejstvija;
	private long _srok_dejstvija_soglasno_zakazchiku;
	private String _srok_ispolnenija_zajavki;
	private long _srok_ispolnenija_zajavki_soglasno_zakazchiku;
	private String _srok_obespechenija_zajavki;
	private long _srok_obespechenija_zajavki_soglasno_zakazchiku;
	private String _srok_postavki;
	private long _srok_postavki_soglasno_zakazchiku;
	private prochaja_informacija_dlja_zajavki _escapedModel;
}