/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.tipy.dokumentov.postavwika.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import tj.tipy.dokumentov.postavwika.model.tipy_dokumentov_postavwika;
import tj.tipy.dokumentov.postavwika.model.tipy_dokumentov_postavwikaModel;
import tj.tipy.dokumentov.postavwika.model.tipy_dokumentov_postavwikaSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the tipy_dokumentov_postavwika service. Represents a row in the &quot;sapp.tipy_dokumentov_postavwika&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link tipy_dokumentov_postavwikaModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link tipy_dokumentov_postavwikaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see tipy_dokumentov_postavwikaImpl
 * @see tipy_dokumentov_postavwika
 * @see tipy_dokumentov_postavwikaModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class tipy_dokumentov_postavwikaModelImpl extends BaseModelImpl<tipy_dokumentov_postavwika>
	implements tipy_dokumentov_postavwikaModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a tipy_dokumentov_postavwika model instance should use the {@link tipy_dokumentov_postavwika} interface instead.
	 */
	public static final String TABLE_NAME = "sapp.tipy_dokumentov_postavwika";
	public static final Object[][] TABLE_COLUMNS = {
			{ "tip", Types.VARCHAR },
			{ "tipy_dokumentov_postavwika_id", Types.BIGINT }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("tip", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("tipy_dokumentov_postavwika_id", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE = "create table sapp.tipy_dokumentov_postavwika (tip VARCHAR(75) null,tipy_dokumentov_postavwika_id LONG not null primary key)";
	public static final String TABLE_SQL_DROP = "drop table sapp.tipy_dokumentov_postavwika";
	public static final String ORDER_BY_JPQL = " ORDER BY tipy_dokumentov_postavwika.tipy_dokumentov_postavwika_id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY sapp.tipy_dokumentov_postavwika.tipy_dokumentov_postavwika_id ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(tj.tipy.dokumentov.postavwika.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.tj.tipy.dokumentov.postavwika.model.tipy_dokumentov_postavwika"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(tj.tipy.dokumentov.postavwika.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.tj.tipy.dokumentov.postavwika.model.tipy_dokumentov_postavwika"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static tipy_dokumentov_postavwika toModel(
		tipy_dokumentov_postavwikaSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		tipy_dokumentov_postavwika model = new tipy_dokumentov_postavwikaImpl();

		model.setTip(soapModel.getTip());
		model.setTipy_dokumentov_postavwika_id(soapModel.getTipy_dokumentov_postavwika_id());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<tipy_dokumentov_postavwika> toModels(
		tipy_dokumentov_postavwikaSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<tipy_dokumentov_postavwika> models = new ArrayList<tipy_dokumentov_postavwika>(soapModels.length);

		for (tipy_dokumentov_postavwikaSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(tj.tipy.dokumentov.postavwika.service.util.ServiceProps.get(
				"lock.expiration.time.tj.tipy.dokumentov.postavwika.model.tipy_dokumentov_postavwika"));

	public tipy_dokumentov_postavwikaModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _tipy_dokumentov_postavwika_id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setTipy_dokumentov_postavwika_id(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _tipy_dokumentov_postavwika_id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return tipy_dokumentov_postavwika.class;
	}

	@Override
	public String getModelClassName() {
		return tipy_dokumentov_postavwika.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("tip", getTip());
		attributes.put("tipy_dokumentov_postavwika_id",
			getTipy_dokumentov_postavwika_id());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String tip = (String)attributes.get("tip");

		if (tip != null) {
			setTip(tip);
		}

		Long tipy_dokumentov_postavwika_id = (Long)attributes.get(
				"tipy_dokumentov_postavwika_id");

		if (tipy_dokumentov_postavwika_id != null) {
			setTipy_dokumentov_postavwika_id(tipy_dokumentov_postavwika_id);
		}
	}

	@JSON
	@Override
	public String getTip() {
		if (_tip == null) {
			return StringPool.BLANK;
		}
		else {
			return _tip;
		}
	}

	@Override
	public void setTip(String tip) {
		_tip = tip;
	}

	@JSON
	@Override
	public long getTipy_dokumentov_postavwika_id() {
		return _tipy_dokumentov_postavwika_id;
	}

	@Override
	public void setTipy_dokumentov_postavwika_id(
		long tipy_dokumentov_postavwika_id) {
		_tipy_dokumentov_postavwika_id = tipy_dokumentov_postavwika_id;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			tipy_dokumentov_postavwika.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public tipy_dokumentov_postavwika toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (tipy_dokumentov_postavwika)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		tipy_dokumentov_postavwikaImpl tipy_dokumentov_postavwikaImpl = new tipy_dokumentov_postavwikaImpl();

		tipy_dokumentov_postavwikaImpl.setTip(getTip());
		tipy_dokumentov_postavwikaImpl.setTipy_dokumentov_postavwika_id(getTipy_dokumentov_postavwika_id());

		tipy_dokumentov_postavwikaImpl.resetOriginalValues();

		return tipy_dokumentov_postavwikaImpl;
	}

	@Override
	public int compareTo(tipy_dokumentov_postavwika tipy_dokumentov_postavwika) {
		long primaryKey = tipy_dokumentov_postavwika.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof tipy_dokumentov_postavwika)) {
			return false;
		}

		tipy_dokumentov_postavwika tipy_dokumentov_postavwika = (tipy_dokumentov_postavwika)obj;

		long primaryKey = tipy_dokumentov_postavwika.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<tipy_dokumentov_postavwika> toCacheModel() {
		tipy_dokumentov_postavwikaCacheModel tipy_dokumentov_postavwikaCacheModel =
			new tipy_dokumentov_postavwikaCacheModel();

		tipy_dokumentov_postavwikaCacheModel.tip = getTip();

		String tip = tipy_dokumentov_postavwikaCacheModel.tip;

		if ((tip != null) && (tip.length() == 0)) {
			tipy_dokumentov_postavwikaCacheModel.tip = null;
		}

		tipy_dokumentov_postavwikaCacheModel.tipy_dokumentov_postavwika_id = getTipy_dokumentov_postavwika_id();

		return tipy_dokumentov_postavwikaCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(5);

		sb.append("{tip=");
		sb.append(getTip());
		sb.append(", tipy_dokumentov_postavwika_id=");
		sb.append(getTipy_dokumentov_postavwika_id());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(10);

		sb.append("<model><model-name>");
		sb.append(
			"tj.tipy.dokumentov.postavwika.model.tipy_dokumentov_postavwika");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>tip</column-name><column-value><![CDATA[");
		sb.append(getTip());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tipy_dokumentov_postavwika_id</column-name><column-value><![CDATA[");
		sb.append(getTipy_dokumentov_postavwika_id());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = tipy_dokumentov_postavwika.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			tipy_dokumentov_postavwika.class
		};
	private String _tip;
	private long _tipy_dokumentov_postavwika_id;
	private tipy_dokumentov_postavwika _escapedModel;
}