/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.tipy.dokumentov.postavwika.model.impl;

import aQute.bnd.annotation.ProviderType;

import tj.tipy.dokumentov.postavwika.model.tipy_dokumentov_postavwika;
import tj.tipy.dokumentov.postavwika.service.tipy_dokumentov_postavwikaLocalServiceUtil;

/**
 * The extended model base implementation for the tipy_dokumentov_postavwika service. Represents a row in the &quot;sapp.tipy_dokumentov_postavwika&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link tipy_dokumentov_postavwikaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see tipy_dokumentov_postavwikaImpl
 * @see tipy_dokumentov_postavwika
 * @generated
 */
@ProviderType
public abstract class tipy_dokumentov_postavwikaBaseImpl
	extends tipy_dokumentov_postavwikaModelImpl
	implements tipy_dokumentov_postavwika {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a tipy_dokumentov_postavwika model instance should use the {@link tipy_dokumentov_postavwika} interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			tipy_dokumentov_postavwikaLocalServiceUtil.addtipy_dokumentov_postavwika(this);
		}
		else {
			tipy_dokumentov_postavwikaLocalServiceUtil.updatetipy_dokumentov_postavwika(this);
		}
	}
}