/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.protokol.podachi.pretenzij.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the protokol_podachi_pretenzij service. Represents a row in the &quot;sapp.protokol_podachi_pretenzij&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link tj.protokol.podachi.pretenzij.model.impl.protokol_podachi_pretenzijModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link tj.protokol.podachi.pretenzij.model.impl.protokol_podachi_pretenzijImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see protokol_podachi_pretenzij
 * @see tj.protokol.podachi.pretenzij.model.impl.protokol_podachi_pretenzijImpl
 * @see tj.protokol.podachi.pretenzij.model.impl.protokol_podachi_pretenzijModelImpl
 * @generated
 */
@ProviderType
public interface protokol_podachi_pretenzijModel extends BaseModel<protokol_podachi_pretenzij> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a protokol_podachi_pretenzij model instance should use the {@link protokol_podachi_pretenzij} interface instead.
	 */

	/**
	 * Returns the primary key of this protokol_podachi_pretenzij.
	 *
	 * @return the primary key of this protokol_podachi_pretenzij
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this protokol_podachi_pretenzij.
	 *
	 * @param primaryKey the primary key of this protokol_podachi_pretenzij
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the data_generacii of this protokol_podachi_pretenzij.
	 *
	 * @return the data_generacii of this protokol_podachi_pretenzij
	 */
	public Date getData_generacii();

	/**
	 * Sets the data_generacii of this protokol_podachi_pretenzij.
	 *
	 * @param data_generacii the data_generacii of this protokol_podachi_pretenzij
	 */
	public void setData_generacii(Date data_generacii);

	/**
	 * Returns the izvewenie_id of this protokol_podachi_pretenzij.
	 *
	 * @return the izvewenie_id of this protokol_podachi_pretenzij
	 */
	public long getIzvewenie_id();

	/**
	 * Sets the izvewenie_id of this protokol_podachi_pretenzij.
	 *
	 * @param izvewenie_id the izvewenie_id of this protokol_podachi_pretenzij
	 */
	public void setIzvewenie_id(long izvewenie_id);

	/**
	 * Returns the protokol_podachi_pretenzij_id of this protokol_podachi_pretenzij.
	 *
	 * @return the protokol_podachi_pretenzij_id of this protokol_podachi_pretenzij
	 */
	public long getProtokol_podachi_pretenzij_id();

	/**
	 * Sets the protokol_podachi_pretenzij_id of this protokol_podachi_pretenzij.
	 *
	 * @param protokol_podachi_pretenzij_id the protokol_podachi_pretenzij_id of this protokol_podachi_pretenzij
	 */
	public void setProtokol_podachi_pretenzij_id(
		long protokol_podachi_pretenzij_id);

	/**
	 * Returns the sgeneriroval of this protokol_podachi_pretenzij.
	 *
	 * @return the sgeneriroval of this protokol_podachi_pretenzij
	 */
	public long getSgeneriroval();

	/**
	 * Sets the sgeneriroval of this protokol_podachi_pretenzij.
	 *
	 * @param sgeneriroval the sgeneriroval of this protokol_podachi_pretenzij
	 */
	public void setSgeneriroval(long sgeneriroval);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		tj.protokol.podachi.pretenzij.model.protokol_podachi_pretenzij protokol_podachi_pretenzij);

	@Override
	public int hashCode();

	@Override
	public CacheModel<tj.protokol.podachi.pretenzij.model.protokol_podachi_pretenzij> toCacheModel();

	@Override
	public tj.protokol.podachi.pretenzij.model.protokol_podachi_pretenzij toEscapedModel();

	@Override
	public tj.protokol.podachi.pretenzij.model.protokol_podachi_pretenzij toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}