/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.dokumenty.na.zajavku.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import tj.dokumenty.na.zajavku.model.dokumenty_na_zajavku;
import tj.dokumenty.na.zajavku.model.dokumenty_na_zajavkuModel;
import tj.dokumenty.na.zajavku.model.dokumenty_na_zajavkuSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the dokumenty_na_zajavku service. Represents a row in the &quot;sapp.dokumenty_na_zajavku&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link dokumenty_na_zajavkuModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link dokumenty_na_zajavkuImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see dokumenty_na_zajavkuImpl
 * @see dokumenty_na_zajavku
 * @see dokumenty_na_zajavkuModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class dokumenty_na_zajavkuModelImpl extends BaseModelImpl<dokumenty_na_zajavku>
	implements dokumenty_na_zajavkuModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a dokumenty_na_zajavku model instance should use the {@link dokumenty_na_zajavku} interface instead.
	 */
	public static final String TABLE_NAME = "sapp.dokumenty_na_zajavku";
	public static final Object[][] TABLE_COLUMNS = {
			{ "dokumenty_na_zajavku_id", Types.BIGINT },
			{ "data_zagruzki", Types.TIMESTAMP },
			{ "imja_fajla", Types.VARCHAR },
			{ "izvewenie_id", Types.BIGINT },
			{ "lot_id", Types.BIGINT },
			{ "nazvanie_dokumenta", Types.VARCHAR },
			{ "postavwik_id", Types.BIGINT },
			{ "zagruzil", Types.BIGINT }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("dokumenty_na_zajavku_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("data_zagruzki", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("imja_fajla", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("izvewenie_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("lot_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("nazvanie_dokumenta", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("postavwik_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("zagruzil", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE = "create table sapp.dokumenty_na_zajavku (dokumenty_na_zajavku_id LONG not null primary key,data_zagruzki DATE null,imja_fajla VARCHAR(75) null,izvewenie_id LONG,lot_id LONG,nazvanie_dokumenta VARCHAR(75) null,postavwik_id LONG,zagruzil LONG)";
	public static final String TABLE_SQL_DROP = "drop table sapp.dokumenty_na_zajavku";
	public static final String ORDER_BY_JPQL = " ORDER BY dokumenty_na_zajavku.dokumenty_na_zajavku_id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY sapp.dokumenty_na_zajavku.dokumenty_na_zajavku_id ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(tj.dokumenty.na.zajavku.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.tj.dokumenty.na.zajavku.model.dokumenty_na_zajavku"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(tj.dokumenty.na.zajavku.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.tj.dokumenty.na.zajavku.model.dokumenty_na_zajavku"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static dokumenty_na_zajavku toModel(
		dokumenty_na_zajavkuSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		dokumenty_na_zajavku model = new dokumenty_na_zajavkuImpl();

		model.setDokumenty_na_zajavku_id(soapModel.getDokumenty_na_zajavku_id());
		model.setData_zagruzki(soapModel.getData_zagruzki());
		model.setImja_fajla(soapModel.getImja_fajla());
		model.setIzvewenie_id(soapModel.getIzvewenie_id());
		model.setLot_id(soapModel.getLot_id());
		model.setNazvanie_dokumenta(soapModel.getNazvanie_dokumenta());
		model.setPostavwik_id(soapModel.getPostavwik_id());
		model.setZagruzil(soapModel.getZagruzil());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<dokumenty_na_zajavku> toModels(
		dokumenty_na_zajavkuSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<dokumenty_na_zajavku> models = new ArrayList<dokumenty_na_zajavku>(soapModels.length);

		for (dokumenty_na_zajavkuSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(tj.dokumenty.na.zajavku.service.util.ServiceProps.get(
				"lock.expiration.time.tj.dokumenty.na.zajavku.model.dokumenty_na_zajavku"));

	public dokumenty_na_zajavkuModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _dokumenty_na_zajavku_id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setDokumenty_na_zajavku_id(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _dokumenty_na_zajavku_id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return dokumenty_na_zajavku.class;
	}

	@Override
	public String getModelClassName() {
		return dokumenty_na_zajavku.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("dokumenty_na_zajavku_id", getDokumenty_na_zajavku_id());
		attributes.put("data_zagruzki", getData_zagruzki());
		attributes.put("imja_fajla", getImja_fajla());
		attributes.put("izvewenie_id", getIzvewenie_id());
		attributes.put("lot_id", getLot_id());
		attributes.put("nazvanie_dokumenta", getNazvanie_dokumenta());
		attributes.put("postavwik_id", getPostavwik_id());
		attributes.put("zagruzil", getZagruzil());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long dokumenty_na_zajavku_id = (Long)attributes.get(
				"dokumenty_na_zajavku_id");

		if (dokumenty_na_zajavku_id != null) {
			setDokumenty_na_zajavku_id(dokumenty_na_zajavku_id);
		}

		Date data_zagruzki = (Date)attributes.get("data_zagruzki");

		if (data_zagruzki != null) {
			setData_zagruzki(data_zagruzki);
		}

		String imja_fajla = (String)attributes.get("imja_fajla");

		if (imja_fajla != null) {
			setImja_fajla(imja_fajla);
		}

		Long izvewenie_id = (Long)attributes.get("izvewenie_id");

		if (izvewenie_id != null) {
			setIzvewenie_id(izvewenie_id);
		}

		Long lot_id = (Long)attributes.get("lot_id");

		if (lot_id != null) {
			setLot_id(lot_id);
		}

		String nazvanie_dokumenta = (String)attributes.get("nazvanie_dokumenta");

		if (nazvanie_dokumenta != null) {
			setNazvanie_dokumenta(nazvanie_dokumenta);
		}

		Long postavwik_id = (Long)attributes.get("postavwik_id");

		if (postavwik_id != null) {
			setPostavwik_id(postavwik_id);
		}

		Long zagruzil = (Long)attributes.get("zagruzil");

		if (zagruzil != null) {
			setZagruzil(zagruzil);
		}
	}

	@JSON
	@Override
	public long getDokumenty_na_zajavku_id() {
		return _dokumenty_na_zajavku_id;
	}

	@Override
	public void setDokumenty_na_zajavku_id(long dokumenty_na_zajavku_id) {
		_dokumenty_na_zajavku_id = dokumenty_na_zajavku_id;
	}

	@JSON
	@Override
	public Date getData_zagruzki() {
		return _data_zagruzki;
	}

	@Override
	public void setData_zagruzki(Date data_zagruzki) {
		_data_zagruzki = data_zagruzki;
	}

	@JSON
	@Override
	public String getImja_fajla() {
		if (_imja_fajla == null) {
			return StringPool.BLANK;
		}
		else {
			return _imja_fajla;
		}
	}

	@Override
	public void setImja_fajla(String imja_fajla) {
		_imja_fajla = imja_fajla;
	}

	@JSON
	@Override
	public long getIzvewenie_id() {
		return _izvewenie_id;
	}

	@Override
	public void setIzvewenie_id(long izvewenie_id) {
		_izvewenie_id = izvewenie_id;
	}

	@JSON
	@Override
	public long getLot_id() {
		return _lot_id;
	}

	@Override
	public void setLot_id(long lot_id) {
		_lot_id = lot_id;
	}

	@JSON
	@Override
	public String getNazvanie_dokumenta() {
		if (_nazvanie_dokumenta == null) {
			return StringPool.BLANK;
		}
		else {
			return _nazvanie_dokumenta;
		}
	}

	@Override
	public void setNazvanie_dokumenta(String nazvanie_dokumenta) {
		_nazvanie_dokumenta = nazvanie_dokumenta;
	}

	@JSON
	@Override
	public long getPostavwik_id() {
		return _postavwik_id;
	}

	@Override
	public void setPostavwik_id(long postavwik_id) {
		_postavwik_id = postavwik_id;
	}

	@JSON
	@Override
	public long getZagruzil() {
		return _zagruzil;
	}

	@Override
	public void setZagruzil(long zagruzil) {
		_zagruzil = zagruzil;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			dokumenty_na_zajavku.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public dokumenty_na_zajavku toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (dokumenty_na_zajavku)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		dokumenty_na_zajavkuImpl dokumenty_na_zajavkuImpl = new dokumenty_na_zajavkuImpl();

		dokumenty_na_zajavkuImpl.setDokumenty_na_zajavku_id(getDokumenty_na_zajavku_id());
		dokumenty_na_zajavkuImpl.setData_zagruzki(getData_zagruzki());
		dokumenty_na_zajavkuImpl.setImja_fajla(getImja_fajla());
		dokumenty_na_zajavkuImpl.setIzvewenie_id(getIzvewenie_id());
		dokumenty_na_zajavkuImpl.setLot_id(getLot_id());
		dokumenty_na_zajavkuImpl.setNazvanie_dokumenta(getNazvanie_dokumenta());
		dokumenty_na_zajavkuImpl.setPostavwik_id(getPostavwik_id());
		dokumenty_na_zajavkuImpl.setZagruzil(getZagruzil());

		dokumenty_na_zajavkuImpl.resetOriginalValues();

		return dokumenty_na_zajavkuImpl;
	}

	@Override
	public int compareTo(dokumenty_na_zajavku dokumenty_na_zajavku) {
		long primaryKey = dokumenty_na_zajavku.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof dokumenty_na_zajavku)) {
			return false;
		}

		dokumenty_na_zajavku dokumenty_na_zajavku = (dokumenty_na_zajavku)obj;

		long primaryKey = dokumenty_na_zajavku.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<dokumenty_na_zajavku> toCacheModel() {
		dokumenty_na_zajavkuCacheModel dokumenty_na_zajavkuCacheModel = new dokumenty_na_zajavkuCacheModel();

		dokumenty_na_zajavkuCacheModel.dokumenty_na_zajavku_id = getDokumenty_na_zajavku_id();

		Date data_zagruzki = getData_zagruzki();

		if (data_zagruzki != null) {
			dokumenty_na_zajavkuCacheModel.data_zagruzki = data_zagruzki.getTime();
		}
		else {
			dokumenty_na_zajavkuCacheModel.data_zagruzki = Long.MIN_VALUE;
		}

		dokumenty_na_zajavkuCacheModel.imja_fajla = getImja_fajla();

		String imja_fajla = dokumenty_na_zajavkuCacheModel.imja_fajla;

		if ((imja_fajla != null) && (imja_fajla.length() == 0)) {
			dokumenty_na_zajavkuCacheModel.imja_fajla = null;
		}

		dokumenty_na_zajavkuCacheModel.izvewenie_id = getIzvewenie_id();

		dokumenty_na_zajavkuCacheModel.lot_id = getLot_id();

		dokumenty_na_zajavkuCacheModel.nazvanie_dokumenta = getNazvanie_dokumenta();

		String nazvanie_dokumenta = dokumenty_na_zajavkuCacheModel.nazvanie_dokumenta;

		if ((nazvanie_dokumenta != null) && (nazvanie_dokumenta.length() == 0)) {
			dokumenty_na_zajavkuCacheModel.nazvanie_dokumenta = null;
		}

		dokumenty_na_zajavkuCacheModel.postavwik_id = getPostavwik_id();

		dokumenty_na_zajavkuCacheModel.zagruzil = getZagruzil();

		return dokumenty_na_zajavkuCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(17);

		sb.append("{dokumenty_na_zajavku_id=");
		sb.append(getDokumenty_na_zajavku_id());
		sb.append(", data_zagruzki=");
		sb.append(getData_zagruzki());
		sb.append(", imja_fajla=");
		sb.append(getImja_fajla());
		sb.append(", izvewenie_id=");
		sb.append(getIzvewenie_id());
		sb.append(", lot_id=");
		sb.append(getLot_id());
		sb.append(", nazvanie_dokumenta=");
		sb.append(getNazvanie_dokumenta());
		sb.append(", postavwik_id=");
		sb.append(getPostavwik_id());
		sb.append(", zagruzil=");
		sb.append(getZagruzil());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(28);

		sb.append("<model><model-name>");
		sb.append("tj.dokumenty.na.zajavku.model.dokumenty_na_zajavku");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>dokumenty_na_zajavku_id</column-name><column-value><![CDATA[");
		sb.append(getDokumenty_na_zajavku_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>data_zagruzki</column-name><column-value><![CDATA[");
		sb.append(getData_zagruzki());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>imja_fajla</column-name><column-value><![CDATA[");
		sb.append(getImja_fajla());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>izvewenie_id</column-name><column-value><![CDATA[");
		sb.append(getIzvewenie_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>lot_id</column-name><column-value><![CDATA[");
		sb.append(getLot_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nazvanie_dokumenta</column-name><column-value><![CDATA[");
		sb.append(getNazvanie_dokumenta());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>postavwik_id</column-name><column-value><![CDATA[");
		sb.append(getPostavwik_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>zagruzil</column-name><column-value><![CDATA[");
		sb.append(getZagruzil());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = dokumenty_na_zajavku.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			dokumenty_na_zajavku.class
		};
	private long _dokumenty_na_zajavku_id;
	private Date _data_zagruzki;
	private String _imja_fajla;
	private long _izvewenie_id;
	private long _lot_id;
	private String _nazvanie_dokumenta;
	private long _postavwik_id;
	private long _zagruzil;
	private dokumenty_na_zajavku _escapedModel;
}