/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.otozvannye.zajavki.service.base;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import tj.otozvannye.zajavki.model.otozvannye_zajavki;
import tj.otozvannye.zajavki.service.otozvannye_zajavkiLocalService;
import tj.otozvannye.zajavki.service.persistence.otozvannye_zajavkiPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the otozvannye_zajavki local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link tj.otozvannye.zajavki.service.impl.otozvannye_zajavkiLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see tj.otozvannye.zajavki.service.impl.otozvannye_zajavkiLocalServiceImpl
 * @see tj.otozvannye.zajavki.service.otozvannye_zajavkiLocalServiceUtil
 * @generated
 */
@ProviderType
public abstract class otozvannye_zajavkiLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements otozvannye_zajavkiLocalService,
		IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link tj.otozvannye.zajavki.service.otozvannye_zajavkiLocalServiceUtil} to access the otozvannye_zajavki local service.
	 */

	/**
	 * Adds the otozvannye_zajavki to the database. Also notifies the appropriate model listeners.
	 *
	 * @param otozvannye_zajavki the otozvannye_zajavki
	 * @return the otozvannye_zajavki that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public otozvannye_zajavki addotozvannye_zajavki(
		otozvannye_zajavki otozvannye_zajavki) {
		otozvannye_zajavki.setNew(true);

		return otozvannye_zajavkiPersistence.update(otozvannye_zajavki);
	}

	/**
	 * Creates a new otozvannye_zajavki with the primary key. Does not add the otozvannye_zajavki to the database.
	 *
	 * @param otozvannye_zajavki_id the primary key for the new otozvannye_zajavki
	 * @return the new otozvannye_zajavki
	 */
	@Override
	public otozvannye_zajavki createotozvannye_zajavki(
		long otozvannye_zajavki_id) {
		return otozvannye_zajavkiPersistence.create(otozvannye_zajavki_id);
	}

	/**
	 * Deletes the otozvannye_zajavki with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param otozvannye_zajavki_id the primary key of the otozvannye_zajavki
	 * @return the otozvannye_zajavki that was removed
	 * @throws PortalException if a otozvannye_zajavki with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public otozvannye_zajavki deleteotozvannye_zajavki(
		long otozvannye_zajavki_id) throws PortalException {
		return otozvannye_zajavkiPersistence.remove(otozvannye_zajavki_id);
	}

	/**
	 * Deletes the otozvannye_zajavki from the database. Also notifies the appropriate model listeners.
	 *
	 * @param otozvannye_zajavki the otozvannye_zajavki
	 * @return the otozvannye_zajavki that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public otozvannye_zajavki deleteotozvannye_zajavki(
		otozvannye_zajavki otozvannye_zajavki) {
		return otozvannye_zajavkiPersistence.remove(otozvannye_zajavki);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(otozvannye_zajavki.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return otozvannye_zajavkiPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link tj.otozvannye.zajavki.model.impl.otozvannye_zajavkiModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end) {
		return otozvannye_zajavkiPersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link tj.otozvannye.zajavki.model.impl.otozvannye_zajavkiModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end, OrderByComparator<T> orderByComparator) {
		return otozvannye_zajavkiPersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return otozvannye_zajavkiPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) {
		return otozvannye_zajavkiPersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public otozvannye_zajavki fetchotozvannye_zajavki(
		long otozvannye_zajavki_id) {
		return otozvannye_zajavkiPersistence.fetchByPrimaryKey(otozvannye_zajavki_id);
	}

	/**
	 * Returns the otozvannye_zajavki with the primary key.
	 *
	 * @param otozvannye_zajavki_id the primary key of the otozvannye_zajavki
	 * @return the otozvannye_zajavki
	 * @throws PortalException if a otozvannye_zajavki with the primary key could not be found
	 */
	@Override
	public otozvannye_zajavki getotozvannye_zajavki(long otozvannye_zajavki_id)
		throws PortalException {
		return otozvannye_zajavkiPersistence.findByPrimaryKey(otozvannye_zajavki_id);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery = new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(otozvannye_zajavkiLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(otozvannye_zajavki.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"otozvannye_zajavki_id");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery getIndexableActionableDynamicQuery() {
		IndexableActionableDynamicQuery indexableActionableDynamicQuery = new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(otozvannye_zajavkiLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(otozvannye_zajavki.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"otozvannye_zajavki_id");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {
		actionableDynamicQuery.setBaseLocalService(otozvannye_zajavkiLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(otozvannye_zajavki.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"otozvannye_zajavki_id");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {
		return otozvannye_zajavkiLocalService.deleteotozvannye_zajavki((otozvannye_zajavki)persistedModel);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {
		return otozvannye_zajavkiPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the otozvannye_zajavkis.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link tj.otozvannye.zajavki.model.impl.otozvannye_zajavkiModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of otozvannye_zajavkis
	 * @param end the upper bound of the range of otozvannye_zajavkis (not inclusive)
	 * @return the range of otozvannye_zajavkis
	 */
	@Override
	public List<otozvannye_zajavki> getotozvannye_zajavkis(int start, int end) {
		return otozvannye_zajavkiPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of otozvannye_zajavkis.
	 *
	 * @return the number of otozvannye_zajavkis
	 */
	@Override
	public int getotozvannye_zajavkisCount() {
		return otozvannye_zajavkiPersistence.countAll();
	}

	/**
	 * Updates the otozvannye_zajavki in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param otozvannye_zajavki the otozvannye_zajavki
	 * @return the otozvannye_zajavki that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public otozvannye_zajavki updateotozvannye_zajavki(
		otozvannye_zajavki otozvannye_zajavki) {
		return otozvannye_zajavkiPersistence.update(otozvannye_zajavki);
	}

	/**
	 * Returns the otozvannye_zajavki local service.
	 *
	 * @return the otozvannye_zajavki local service
	 */
	public otozvannye_zajavkiLocalService getotozvannye_zajavkiLocalService() {
		return otozvannye_zajavkiLocalService;
	}

	/**
	 * Sets the otozvannye_zajavki local service.
	 *
	 * @param otozvannye_zajavkiLocalService the otozvannye_zajavki local service
	 */
	public void setotozvannye_zajavkiLocalService(
		otozvannye_zajavkiLocalService otozvannye_zajavkiLocalService) {
		this.otozvannye_zajavkiLocalService = otozvannye_zajavkiLocalService;
	}

	/**
	 * Returns the otozvannye_zajavki persistence.
	 *
	 * @return the otozvannye_zajavki persistence
	 */
	public otozvannye_zajavkiPersistence getotozvannye_zajavkiPersistence() {
		return otozvannye_zajavkiPersistence;
	}

	/**
	 * Sets the otozvannye_zajavki persistence.
	 *
	 * @param otozvannye_zajavkiPersistence the otozvannye_zajavki persistence
	 */
	public void setotozvannye_zajavkiPersistence(
		otozvannye_zajavkiPersistence otozvannye_zajavkiPersistence) {
		this.otozvannye_zajavkiPersistence = otozvannye_zajavkiPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register("tj.otozvannye.zajavki.model.otozvannye_zajavki",
			otozvannye_zajavkiLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"tj.otozvannye.zajavki.model.otozvannye_zajavki");
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return otozvannye_zajavkiLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return otozvannye_zajavki.class;
	}

	protected String getModelClassName() {
		return otozvannye_zajavki.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = otozvannye_zajavkiPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = otozvannye_zajavkiLocalService.class)
	protected otozvannye_zajavkiLocalService otozvannye_zajavkiLocalService;
	@BeanReference(type = otozvannye_zajavkiPersistence.class)
	protected otozvannye_zajavkiPersistence otozvannye_zajavkiPersistence;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry persistedModelLocalServiceRegistry;
}