/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.pretenzii.ot.postavshhikov.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the pretenzii_ot_postavshhikov service. Represents a row in the &quot;pretenzii_ot_postavshhikov_pretenzii_ot_postavshhikov&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link tj.pretenzii.ot.postavshhikov.model.impl.pretenzii_ot_postavshhikovModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link tj.pretenzii.ot.postavshhikov.model.impl.pretenzii_ot_postavshhikovImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see pretenzii_ot_postavshhikov
 * @see tj.pretenzii.ot.postavshhikov.model.impl.pretenzii_ot_postavshhikovImpl
 * @see tj.pretenzii.ot.postavshhikov.model.impl.pretenzii_ot_postavshhikovModelImpl
 * @generated
 */
@ProviderType
public interface pretenzii_ot_postavshhikovModel extends BaseModel<pretenzii_ot_postavshhikov> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a pretenzii_ot_postavshhikov model instance should use the {@link pretenzii_ot_postavshhikov} interface instead.
	 */

	/**
	 * Returns the primary key of this pretenzii_ot_postavshhikov.
	 *
	 * @return the primary key of this pretenzii_ot_postavshhikov
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this pretenzii_ot_postavshhikov.
	 *
	 * @param primaryKey the primary key of this pretenzii_ot_postavshhikov
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the data_zagruzki of this pretenzii_ot_postavshhikov.
	 *
	 * @return the data_zagruzki of this pretenzii_ot_postavshhikov
	 */
	public Date getData_zagruzki();

	/**
	 * Sets the data_zagruzki of this pretenzii_ot_postavshhikov.
	 *
	 * @param data_zagruzki the data_zagruzki of this pretenzii_ot_postavshhikov
	 */
	public void setData_zagruzki(Date data_zagruzki);

	/**
	 * Returns the imja_fajla of this pretenzii_ot_postavshhikov.
	 *
	 * @return the imja_fajla of this pretenzii_ot_postavshhikov
	 */
	@AutoEscape
	public String getImja_fajla();

	/**
	 * Sets the imja_fajla of this pretenzii_ot_postavshhikov.
	 *
	 * @param imja_fajla the imja_fajla of this pretenzii_ot_postavshhikov
	 */
	public void setImja_fajla(String imja_fajla);

	/**
	 * Returns the izvewenie_id of this pretenzii_ot_postavshhikov.
	 *
	 * @return the izvewenie_id of this pretenzii_ot_postavshhikov
	 */
	public long getIzvewenie_id();

	/**
	 * Sets the izvewenie_id of this pretenzii_ot_postavshhikov.
	 *
	 * @param izvewenie_id the izvewenie_id of this pretenzii_ot_postavshhikov
	 */
	public void setIzvewenie_id(long izvewenie_id);

	/**
	 * Returns the lot_id of this pretenzii_ot_postavshhikov.
	 *
	 * @return the lot_id of this pretenzii_ot_postavshhikov
	 */
	public long getLot_id();

	/**
	 * Sets the lot_id of this pretenzii_ot_postavshhikov.
	 *
	 * @param lot_id the lot_id of this pretenzii_ot_postavshhikov
	 */
	public void setLot_id(long lot_id);

	/**
	 * Returns the nazvanie_dokumenta of this pretenzii_ot_postavshhikov.
	 *
	 * @return the nazvanie_dokumenta of this pretenzii_ot_postavshhikov
	 */
	@AutoEscape
	public String getNazvanie_dokumenta();

	/**
	 * Sets the nazvanie_dokumenta of this pretenzii_ot_postavshhikov.
	 *
	 * @param nazvanie_dokumenta the nazvanie_dokumenta of this pretenzii_ot_postavshhikov
	 */
	public void setNazvanie_dokumenta(String nazvanie_dokumenta);

	/**
	 * Returns the postavshik_id of this pretenzii_ot_postavshhikov.
	 *
	 * @return the postavshik_id of this pretenzii_ot_postavshhikov
	 */
	public long getPostavshik_id();

	/**
	 * Sets the postavshik_id of this pretenzii_ot_postavshhikov.
	 *
	 * @param postavshik_id the postavshik_id of this pretenzii_ot_postavshhikov
	 */
	public void setPostavshik_id(long postavshik_id);

	/**
	 * Returns the pretenzii_ot_postavshhikov_id of this pretenzii_ot_postavshhikov.
	 *
	 * @return the pretenzii_ot_postavshhikov_id of this pretenzii_ot_postavshhikov
	 */
	public long getPretenzii_ot_postavshhikov_id();

	/**
	 * Sets the pretenzii_ot_postavshhikov_id of this pretenzii_ot_postavshhikov.
	 *
	 * @param pretenzii_ot_postavshhikov_id the pretenzii_ot_postavshhikov_id of this pretenzii_ot_postavshhikov
	 */
	public void setPretenzii_ot_postavshhikov_id(
		long pretenzii_ot_postavshhikov_id);

	/**
	 * Returns the zagruzil of this pretenzii_ot_postavshhikov.
	 *
	 * @return the zagruzil of this pretenzii_ot_postavshhikov
	 */
	public long getZagruzil();

	/**
	 * Sets the zagruzil of this pretenzii_ot_postavshhikov.
	 *
	 * @param zagruzil the zagruzil of this pretenzii_ot_postavshhikov
	 */
	public void setZagruzil(long zagruzil);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		tj.pretenzii.ot.postavshhikov.model.pretenzii_ot_postavshhikov pretenzii_ot_postavshhikov);

	@Override
	public int hashCode();

	@Override
	public CacheModel<tj.pretenzii.ot.postavshhikov.model.pretenzii_ot_postavshhikov> toCacheModel();

	@Override
	public tj.pretenzii.ot.postavshhikov.model.pretenzii_ot_postavshhikov toEscapedModel();

	@Override
	public tj.pretenzii.ot.postavshhikov.model.pretenzii_ot_postavshhikov toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}