/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package naruwenija.v.izvewenii.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the naruwenija_v_izvewenii service. Represents a row in the &quot;sapp.naruwenija_v_izvewenii&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link naruwenija.v.izvewenii.model.impl.naruwenija_v_izveweniiModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link naruwenija.v.izvewenii.model.impl.naruwenija_v_izveweniiImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see naruwenija_v_izvewenii
 * @see naruwenija.v.izvewenii.model.impl.naruwenija_v_izveweniiImpl
 * @see naruwenija.v.izvewenii.model.impl.naruwenija_v_izveweniiModelImpl
 * @generated
 */
@ProviderType
public interface naruwenija_v_izveweniiModel extends BaseModel<naruwenija_v_izvewenii> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a naruwenija_v_izvewenii model instance should use the {@link naruwenija_v_izvewenii} interface instead.
	 */

	/**
	 * Returns the primary key of this naruwenija_v_izvewenii.
	 *
	 * @return the primary key of this naruwenija_v_izvewenii
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this naruwenija_v_izvewenii.
	 *
	 * @param primaryKey the primary key of this naruwenija_v_izvewenii
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the data_sozdanija of this naruwenija_v_izvewenii.
	 *
	 * @return the data_sozdanija of this naruwenija_v_izvewenii
	 */
	public Date getData_sozdanija();

	/**
	 * Sets the data_sozdanija of this naruwenija_v_izvewenii.
	 *
	 * @param data_sozdanija the data_sozdanija of this naruwenija_v_izvewenii
	 */
	public void setData_sozdanija(Date data_sozdanija);

	/**
	 * Returns the izvewenie_id of this naruwenija_v_izvewenii.
	 *
	 * @return the izvewenie_id of this naruwenija_v_izvewenii
	 */
	public long getIzvewenie_id();

	/**
	 * Sets the izvewenie_id of this naruwenija_v_izvewenii.
	 *
	 * @param izvewenie_id the izvewenie_id of this naruwenija_v_izvewenii
	 */
	public void setIzvewenie_id(long izvewenie_id);

	/**
	 * Returns the naruwenie of this naruwenija_v_izvewenii.
	 *
	 * @return the naruwenie of this naruwenija_v_izvewenii
	 */
	@AutoEscape
	public String getNaruwenie();

	/**
	 * Sets the naruwenie of this naruwenija_v_izvewenii.
	 *
	 * @param naruwenie the naruwenie of this naruwenija_v_izvewenii
	 */
	public void setNaruwenie(String naruwenie);

	/**
	 * Returns the naruwenija_v_izvewenii_id of this naruwenija_v_izvewenii.
	 *
	 * @return the naruwenija_v_izvewenii_id of this naruwenija_v_izvewenii
	 */
	public long getNaruwenija_v_izvewenii_id();

	/**
	 * Sets the naruwenija_v_izvewenii_id of this naruwenija_v_izvewenii.
	 *
	 * @param naruwenija_v_izvewenii_id the naruwenija_v_izvewenii_id of this naruwenija_v_izvewenii
	 */
	public void setNaruwenija_v_izvewenii_id(long naruwenija_v_izvewenii_id);

	/**
	 * Returns the nomer_razdela of this naruwenija_v_izvewenii.
	 *
	 * @return the nomer_razdela of this naruwenija_v_izvewenii
	 */
	public long getNomer_razdela();

	/**
	 * Sets the nomer_razdela of this naruwenija_v_izvewenii.
	 *
	 * @param nomer_razdela the nomer_razdela of this naruwenija_v_izvewenii
	 */
	public void setNomer_razdela(long nomer_razdela);

	/**
	 * Returns the sozdal of this naruwenija_v_izvewenii.
	 *
	 * @return the sozdal of this naruwenija_v_izvewenii
	 */
	public long getSozdal();

	/**
	 * Sets the sozdal of this naruwenija_v_izvewenii.
	 *
	 * @param sozdal the sozdal of this naruwenija_v_izvewenii
	 */
	public void setSozdal(long sozdal);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		naruwenija.v.izvewenii.model.naruwenija_v_izvewenii naruwenija_v_izvewenii);

	@Override
	public int hashCode();

	@Override
	public CacheModel<naruwenija.v.izvewenii.model.naruwenija_v_izvewenii> toCacheModel();

	@Override
	public naruwenija.v.izvewenii.model.naruwenija_v_izvewenii toEscapedModel();

	@Override
	public naruwenija.v.izvewenii.model.naruwenija_v_izvewenii toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}