/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.rezultat.opredelenija.sootvetstvija.model.impl;

import aQute.bnd.annotation.ProviderType;

import tj.rezultat.opredelenija.sootvetstvija.model.rezultat_opredelenija_sootvetstvija;
import tj.rezultat.opredelenija.sootvetstvija.service.rezultat_opredelenija_sootvetstvijaLocalServiceUtil;

/**
 * The extended model base implementation for the rezultat_opredelenija_sootvetstvija service. Represents a row in the &quot;rezultat_opredelenija_sootvetstvija_rezultat_opredelenija_sootvetstvija&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link rezultat_opredelenija_sootvetstvijaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see rezultat_opredelenija_sootvetstvijaImpl
 * @see rezultat_opredelenija_sootvetstvija
 * @generated
 */
@ProviderType
public abstract class rezultat_opredelenija_sootvetstvijaBaseImpl
	extends rezultat_opredelenija_sootvetstvijaModelImpl
	implements rezultat_opredelenija_sootvetstvija {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a rezultat_opredelenija_sootvetstvija model instance should use the {@link rezultat_opredelenija_sootvetstvija} interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			rezultat_opredelenija_sootvetstvijaLocalServiceUtil.addrezultat_opredelenija_sootvetstvija(this);
		}
		else {
			rezultat_opredelenija_sootvetstvijaLocalServiceUtil.updaterezultat_opredelenija_sootvetstvija(this);
		}
	}
}