/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.zajavki.ot.postavwikov.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import tj.zajavki.ot.postavwikov.model.zajavki_ot_postavwikov;
import tj.zajavki.ot.postavwikov.service.persistence.zajavki_ot_postavwikovPersistence;
import tj.zajavki.ot.postavwikov.service.zajavki_ot_postavwikovService;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the zajavki_ot_postavwikov remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link tj.zajavki.ot.postavwikov.service.impl.zajavki_ot_postavwikovServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see tj.zajavki.ot.postavwikov.service.impl.zajavki_ot_postavwikovServiceImpl
 * @see tj.zajavki.ot.postavwikov.service.zajavki_ot_postavwikovServiceUtil
 * @generated
 */
public abstract class zajavki_ot_postavwikovServiceBaseImpl
	extends BaseServiceImpl implements zajavki_ot_postavwikovService,
		IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link tj.zajavki.ot.postavwikov.service.zajavki_ot_postavwikovServiceUtil} to access the zajavki_ot_postavwikov remote service.
	 */

	/**
	 * Returns the zajavki_ot_postavwikov local service.
	 *
	 * @return the zajavki_ot_postavwikov local service
	 */
	public tj.zajavki.ot.postavwikov.service.zajavki_ot_postavwikovLocalService getzajavki_ot_postavwikovLocalService() {
		return zajavki_ot_postavwikovLocalService;
	}

	/**
	 * Sets the zajavki_ot_postavwikov local service.
	 *
	 * @param zajavki_ot_postavwikovLocalService the zajavki_ot_postavwikov local service
	 */
	public void setzajavki_ot_postavwikovLocalService(
		tj.zajavki.ot.postavwikov.service.zajavki_ot_postavwikovLocalService zajavki_ot_postavwikovLocalService) {
		this.zajavki_ot_postavwikovLocalService = zajavki_ot_postavwikovLocalService;
	}

	/**
	 * Returns the zajavki_ot_postavwikov remote service.
	 *
	 * @return the zajavki_ot_postavwikov remote service
	 */
	public zajavki_ot_postavwikovService getzajavki_ot_postavwikovService() {
		return zajavki_ot_postavwikovService;
	}

	/**
	 * Sets the zajavki_ot_postavwikov remote service.
	 *
	 * @param zajavki_ot_postavwikovService the zajavki_ot_postavwikov remote service
	 */
	public void setzajavki_ot_postavwikovService(
		zajavki_ot_postavwikovService zajavki_ot_postavwikovService) {
		this.zajavki_ot_postavwikovService = zajavki_ot_postavwikovService;
	}

	/**
	 * Returns the zajavki_ot_postavwikov persistence.
	 *
	 * @return the zajavki_ot_postavwikov persistence
	 */
	public zajavki_ot_postavwikovPersistence getzajavki_ot_postavwikovPersistence() {
		return zajavki_ot_postavwikovPersistence;
	}

	/**
	 * Sets the zajavki_ot_postavwikov persistence.
	 *
	 * @param zajavki_ot_postavwikovPersistence the zajavki_ot_postavwikov persistence
	 */
	public void setzajavki_ot_postavwikovPersistence(
		zajavki_ot_postavwikovPersistence zajavki_ot_postavwikovPersistence) {
		this.zajavki_ot_postavwikovPersistence = zajavki_ot_postavwikovPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name remote service.
	 *
	 * @return the class name remote service
	 */
	public com.liferay.portal.kernel.service.ClassNameService getClassNameService() {
		return classNameService;
	}

	/**
	 * Sets the class name remote service.
	 *
	 * @param classNameService the class name remote service
	 */
	public void setClassNameService(
		com.liferay.portal.kernel.service.ClassNameService classNameService) {
		this.classNameService = classNameService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.kernel.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.kernel.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
	}

	public void destroy() {
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return zajavki_ot_postavwikovService.class.getName();
	}

	protected Class<?> getModelClass() {
		return zajavki_ot_postavwikov.class;
	}

	protected String getModelClassName() {
		return zajavki_ot_postavwikov.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = zajavki_ot_postavwikovPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = tj.zajavki.ot.postavwikov.service.zajavki_ot_postavwikovLocalService.class)
	protected tj.zajavki.ot.postavwikov.service.zajavki_ot_postavwikovLocalService zajavki_ot_postavwikovLocalService;
	@BeanReference(type = zajavki_ot_postavwikovService.class)
	protected zajavki_ot_postavwikovService zajavki_ot_postavwikovService;
	@BeanReference(type = zajavki_ot_postavwikovPersistence.class)
	protected zajavki_ot_postavwikovPersistence zajavki_ot_postavwikovPersistence;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameService.class)
	protected com.liferay.portal.kernel.service.ClassNameService classNameService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserService.class)
	protected com.liferay.portal.kernel.service.UserService userService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
}