/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.podtverzhdenie.nalichija.sredstv.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the podtverzhdenie_nalichija_sredstv service. Represents a row in the &quot;sapp.podtverzhdenie_nalichija_sredstv&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link tj.podtverzhdenie.nalichija.sredstv.model.impl.podtverzhdenie_nalichija_sredstvModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link tj.podtverzhdenie.nalichija.sredstv.model.impl.podtverzhdenie_nalichija_sredstvImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see podtverzhdenie_nalichija_sredstv
 * @see tj.podtverzhdenie.nalichija.sredstv.model.impl.podtverzhdenie_nalichija_sredstvImpl
 * @see tj.podtverzhdenie.nalichija.sredstv.model.impl.podtverzhdenie_nalichija_sredstvModelImpl
 * @generated
 */
@ProviderType
public interface podtverzhdenie_nalichija_sredstvModel extends BaseModel<podtverzhdenie_nalichija_sredstv> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a podtverzhdenie_nalichija_sredstv model instance should use the {@link podtverzhdenie_nalichija_sredstv} interface instead.
	 */

	/**
	 * Returns the primary key of this podtverzhdenie_nalichija_sredstv.
	 *
	 * @return the primary key of this podtverzhdenie_nalichija_sredstv
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this podtverzhdenie_nalichija_sredstv.
	 *
	 * @param primaryKey the primary key of this podtverzhdenie_nalichija_sredstv
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the data_zagruzki of this podtverzhdenie_nalichija_sredstv.
	 *
	 * @return the data_zagruzki of this podtverzhdenie_nalichija_sredstv
	 */
	public Date getData_zagruzki();

	/**
	 * Sets the data_zagruzki of this podtverzhdenie_nalichija_sredstv.
	 *
	 * @param data_zagruzki the data_zagruzki of this podtverzhdenie_nalichija_sredstv
	 */
	public void setData_zagruzki(Date data_zagruzki);

	/**
	 * Returns the imja_fajla of this podtverzhdenie_nalichija_sredstv.
	 *
	 * @return the imja_fajla of this podtverzhdenie_nalichija_sredstv
	 */
	@AutoEscape
	public String getImja_fajla();

	/**
	 * Sets the imja_fajla of this podtverzhdenie_nalichija_sredstv.
	 *
	 * @param imja_fajla the imja_fajla of this podtverzhdenie_nalichija_sredstv
	 */
	public void setImja_fajla(String imja_fajla);

	/**
	 * Returns the izvewenie_id of this podtverzhdenie_nalichija_sredstv.
	 *
	 * @return the izvewenie_id of this podtverzhdenie_nalichija_sredstv
	 */
	public long getIzvewenie_id();

	/**
	 * Sets the izvewenie_id of this podtverzhdenie_nalichija_sredstv.
	 *
	 * @param izvewenie_id the izvewenie_id of this podtverzhdenie_nalichija_sredstv
	 */
	public void setIzvewenie_id(long izvewenie_id);

	/**
	 * Returns the lot_id of this podtverzhdenie_nalichija_sredstv.
	 *
	 * @return the lot_id of this podtverzhdenie_nalichija_sredstv
	 */
	public long getLot_id();

	/**
	 * Sets the lot_id of this podtverzhdenie_nalichija_sredstv.
	 *
	 * @param lot_id the lot_id of this podtverzhdenie_nalichija_sredstv
	 */
	public void setLot_id(long lot_id);

	/**
	 * Returns the nazvanie_dokumenta of this podtverzhdenie_nalichija_sredstv.
	 *
	 * @return the nazvanie_dokumenta of this podtverzhdenie_nalichija_sredstv
	 */
	@AutoEscape
	public String getNazvanie_dokumenta();

	/**
	 * Sets the nazvanie_dokumenta of this podtverzhdenie_nalichija_sredstv.
	 *
	 * @param nazvanie_dokumenta the nazvanie_dokumenta of this podtverzhdenie_nalichija_sredstv
	 */
	public void setNazvanie_dokumenta(String nazvanie_dokumenta);

	/**
	 * Returns the podtverzhdenie_nalichija_sredstv_id of this podtverzhdenie_nalichija_sredstv.
	 *
	 * @return the podtverzhdenie_nalichija_sredstv_id of this podtverzhdenie_nalichija_sredstv
	 */
	public long getPodtverzhdenie_nalichija_sredstv_id();

	/**
	 * Sets the podtverzhdenie_nalichija_sredstv_id of this podtverzhdenie_nalichija_sredstv.
	 *
	 * @param podtverzhdenie_nalichija_sredstv_id the podtverzhdenie_nalichija_sredstv_id of this podtverzhdenie_nalichija_sredstv
	 */
	public void setPodtverzhdenie_nalichija_sredstv_id(
		long podtverzhdenie_nalichija_sredstv_id);

	/**
	 * Returns the zagruzil of this podtverzhdenie_nalichija_sredstv.
	 *
	 * @return the zagruzil of this podtverzhdenie_nalichija_sredstv
	 */
	public long getZagruzil();

	/**
	 * Sets the zagruzil of this podtverzhdenie_nalichija_sredstv.
	 *
	 * @param zagruzil the zagruzil of this podtverzhdenie_nalichija_sredstv
	 */
	public void setZagruzil(long zagruzil);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		tj.podtverzhdenie.nalichija.sredstv.model.podtverzhdenie_nalichija_sredstv podtverzhdenie_nalichija_sredstv);

	@Override
	public int hashCode();

	@Override
	public CacheModel<tj.podtverzhdenie.nalichija.sredstv.model.podtverzhdenie_nalichija_sredstv> toCacheModel();

	@Override
	public tj.podtverzhdenie.nalichija.sredstv.model.podtverzhdenie_nalichija_sredstv toEscapedModel();

	@Override
	public tj.podtverzhdenie.nalichija.sredstv.model.podtverzhdenie_nalichija_sredstv toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}