/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.rezultat.opredelenija.sootvetstvija.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import tj.rezultat.opredelenija.sootvetstvija.model.rezultat_opredelenija_sootvetstvija;
import tj.rezultat.opredelenija.sootvetstvija.service.persistence.rezultat_opredelenija_sootvetstvijaPersistence;
import tj.rezultat.opredelenija.sootvetstvija.service.rezultat_opredelenija_sootvetstvijaService;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the rezultat_opredelenija_sootvetstvija remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link tj.rezultat.opredelenija.sootvetstvija.service.impl.rezultat_opredelenija_sootvetstvijaServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see tj.rezultat.opredelenija.sootvetstvija.service.impl.rezultat_opredelenija_sootvetstvijaServiceImpl
 * @see tj.rezultat.opredelenija.sootvetstvija.service.rezultat_opredelenija_sootvetstvijaServiceUtil
 * @generated
 */
public abstract class rezultat_opredelenija_sootvetstvijaServiceBaseImpl
	extends BaseServiceImpl
	implements rezultat_opredelenija_sootvetstvijaService,
		IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link tj.rezultat.opredelenija.sootvetstvija.service.rezultat_opredelenija_sootvetstvijaServiceUtil} to access the rezultat_opredelenija_sootvetstvija remote service.
	 */

	/**
	 * Returns the rezultat_opredelenija_sootvetstvija local service.
	 *
	 * @return the rezultat_opredelenija_sootvetstvija local service
	 */
	public tj.rezultat.opredelenija.sootvetstvija.service.rezultat_opredelenija_sootvetstvijaLocalService getrezultat_opredelenija_sootvetstvijaLocalService() {
		return rezultat_opredelenija_sootvetstvijaLocalService;
	}

	/**
	 * Sets the rezultat_opredelenija_sootvetstvija local service.
	 *
	 * @param rezultat_opredelenija_sootvetstvijaLocalService the rezultat_opredelenija_sootvetstvija local service
	 */
	public void setrezultat_opredelenija_sootvetstvijaLocalService(
		tj.rezultat.opredelenija.sootvetstvija.service.rezultat_opredelenija_sootvetstvijaLocalService rezultat_opredelenija_sootvetstvijaLocalService) {
		this.rezultat_opredelenija_sootvetstvijaLocalService = rezultat_opredelenija_sootvetstvijaLocalService;
	}

	/**
	 * Returns the rezultat_opredelenija_sootvetstvija remote service.
	 *
	 * @return the rezultat_opredelenija_sootvetstvija remote service
	 */
	public rezultat_opredelenija_sootvetstvijaService getrezultat_opredelenija_sootvetstvijaService() {
		return rezultat_opredelenija_sootvetstvijaService;
	}

	/**
	 * Sets the rezultat_opredelenija_sootvetstvija remote service.
	 *
	 * @param rezultat_opredelenija_sootvetstvijaService the rezultat_opredelenija_sootvetstvija remote service
	 */
	public void setrezultat_opredelenija_sootvetstvijaService(
		rezultat_opredelenija_sootvetstvijaService rezultat_opredelenija_sootvetstvijaService) {
		this.rezultat_opredelenija_sootvetstvijaService = rezultat_opredelenija_sootvetstvijaService;
	}

	/**
	 * Returns the rezultat_opredelenija_sootvetstvija persistence.
	 *
	 * @return the rezultat_opredelenija_sootvetstvija persistence
	 */
	public rezultat_opredelenija_sootvetstvijaPersistence getrezultat_opredelenija_sootvetstvijaPersistence() {
		return rezultat_opredelenija_sootvetstvijaPersistence;
	}

	/**
	 * Sets the rezultat_opredelenija_sootvetstvija persistence.
	 *
	 * @param rezultat_opredelenija_sootvetstvijaPersistence the rezultat_opredelenija_sootvetstvija persistence
	 */
	public void setrezultat_opredelenija_sootvetstvijaPersistence(
		rezultat_opredelenija_sootvetstvijaPersistence rezultat_opredelenija_sootvetstvijaPersistence) {
		this.rezultat_opredelenija_sootvetstvijaPersistence = rezultat_opredelenija_sootvetstvijaPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name remote service.
	 *
	 * @return the class name remote service
	 */
	public com.liferay.portal.kernel.service.ClassNameService getClassNameService() {
		return classNameService;
	}

	/**
	 * Sets the class name remote service.
	 *
	 * @param classNameService the class name remote service
	 */
	public void setClassNameService(
		com.liferay.portal.kernel.service.ClassNameService classNameService) {
		this.classNameService = classNameService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.kernel.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.kernel.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
	}

	public void destroy() {
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return rezultat_opredelenija_sootvetstvijaService.class.getName();
	}

	protected Class<?> getModelClass() {
		return rezultat_opredelenija_sootvetstvija.class;
	}

	protected String getModelClassName() {
		return rezultat_opredelenija_sootvetstvija.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = rezultat_opredelenija_sootvetstvijaPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = tj.rezultat.opredelenija.sootvetstvija.service.rezultat_opredelenija_sootvetstvijaLocalService.class)
	protected tj.rezultat.opredelenija.sootvetstvija.service.rezultat_opredelenija_sootvetstvijaLocalService rezultat_opredelenija_sootvetstvijaLocalService;
	@BeanReference(type = rezultat_opredelenija_sootvetstvijaService.class)
	protected rezultat_opredelenija_sootvetstvijaService rezultat_opredelenija_sootvetstvijaService;
	@BeanReference(type = rezultat_opredelenija_sootvetstvijaPersistence.class)
	protected rezultat_opredelenija_sootvetstvijaPersistence rezultat_opredelenija_sootvetstvijaPersistence;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameService.class)
	protected com.liferay.portal.kernel.service.ClassNameService classNameService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserService.class)
	protected com.liferay.portal.kernel.service.UserService userService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
}