/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.zajavki.ot.postavwikov.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import tj.zajavki.ot.postavwikov.model.zajavki_ot_postavwikov;
import tj.zajavki.ot.postavwikov.model.zajavki_ot_postavwikovModel;
import tj.zajavki.ot.postavwikov.model.zajavki_ot_postavwikovSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the zajavki_ot_postavwikov service. Represents a row in the &quot;sapp.zajavki_ot_postavwikov&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link zajavki_ot_postavwikovModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link zajavki_ot_postavwikovImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see zajavki_ot_postavwikovImpl
 * @see zajavki_ot_postavwikov
 * @see zajavki_ot_postavwikovModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class zajavki_ot_postavwikovModelImpl extends BaseModelImpl<zajavki_ot_postavwikov>
	implements zajavki_ot_postavwikovModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a zajavki_ot_postavwikov model instance should use the {@link zajavki_ot_postavwikov} interface instead.
	 */
	public static final String TABLE_NAME = "sapp.zajavki_ot_postavwikov";
	public static final Object[][] TABLE_COLUMNS = {
			{ "data_izmenenija", Types.TIMESTAMP },
			{ "data_sozdanija", Types.TIMESTAMP },
			{ "itogo_za_tovar", Types.DOUBLE },
			{ "izmenil", Types.BIGINT },
			{ "izvewenie_id", Types.BIGINT },
			{ "kod_po_obshhemu_klassifikatoru", Types.BIGINT },
			{ "kod_strany_proizvoditelja", Types.BIGINT },
			{ "kolichestvo", Types.BIGINT },
			{ "lot_id", Types.BIGINT },
			{ "opisanie_tovara", Types.VARCHAR },
			{ "postavwik_id", Types.BIGINT },
			{ "predlozhenie_postavwika", Types.VARCHAR },
			{ "sozdal", Types.BIGINT },
			{ "summa_za_edinicu_tovara", Types.DOUBLE },
			{ "tovar_id", Types.BIGINT },
			{ "zajavki_ot_postavwikov_id", Types.BIGINT }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("data_izmenenija", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("data_sozdanija", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("itogo_za_tovar", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("izmenil", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("izvewenie_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("kod_po_obshhemu_klassifikatoru", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("kod_strany_proizvoditelja", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("kolichestvo", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("lot_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("opisanie_tovara", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("postavwik_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("predlozhenie_postavwika", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("sozdal", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("summa_za_edinicu_tovara", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("tovar_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("zajavki_ot_postavwikov_id", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE = "create table sapp.zajavki_ot_postavwikov (data_izmenenija DATE null,data_sozdanija DATE null,itogo_za_tovar DOUBLE,izmenil LONG,izvewenie_id LONG,kod_po_obshhemu_klassifikatoru LONG,kod_strany_proizvoditelja LONG,kolichestvo LONG,lot_id LONG,opisanie_tovara VARCHAR(75) null,postavwik_id LONG,predlozhenie_postavwika VARCHAR(75) null,sozdal LONG,summa_za_edinicu_tovara DOUBLE,tovar_id LONG,zajavki_ot_postavwikov_id LONG not null primary key)";
	public static final String TABLE_SQL_DROP = "drop table sapp.zajavki_ot_postavwikov";
	public static final String ORDER_BY_JPQL = " ORDER BY zajavki_ot_postavwikov.zajavki_ot_postavwikov_id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY sapp.zajavki_ot_postavwikov.zajavki_ot_postavwikov_id ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(tj.zajavki.ot.postavwikov.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.tj.zajavki.ot.postavwikov.model.zajavki_ot_postavwikov"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(tj.zajavki.ot.postavwikov.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.tj.zajavki.ot.postavwikov.model.zajavki_ot_postavwikov"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static zajavki_ot_postavwikov toModel(
		zajavki_ot_postavwikovSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		zajavki_ot_postavwikov model = new zajavki_ot_postavwikovImpl();

		model.setData_izmenenija(soapModel.getData_izmenenija());
		model.setData_sozdanija(soapModel.getData_sozdanija());
		model.setItogo_za_tovar(soapModel.getItogo_za_tovar());
		model.setIzmenil(soapModel.getIzmenil());
		model.setIzvewenie_id(soapModel.getIzvewenie_id());
		model.setKod_po_obshhemu_klassifikatoru(soapModel.getKod_po_obshhemu_klassifikatoru());
		model.setKod_strany_proizvoditelja(soapModel.getKod_strany_proizvoditelja());
		model.setKolichestvo(soapModel.getKolichestvo());
		model.setLot_id(soapModel.getLot_id());
		model.setOpisanie_tovara(soapModel.getOpisanie_tovara());
		model.setPostavwik_id(soapModel.getPostavwik_id());
		model.setPredlozhenie_postavwika(soapModel.getPredlozhenie_postavwika());
		model.setSozdal(soapModel.getSozdal());
		model.setSumma_za_edinicu_tovara(soapModel.getSumma_za_edinicu_tovara());
		model.setTovar_id(soapModel.getTovar_id());
		model.setZajavki_ot_postavwikov_id(soapModel.getZajavki_ot_postavwikov_id());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<zajavki_ot_postavwikov> toModels(
		zajavki_ot_postavwikovSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<zajavki_ot_postavwikov> models = new ArrayList<zajavki_ot_postavwikov>(soapModels.length);

		for (zajavki_ot_postavwikovSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(tj.zajavki.ot.postavwikov.service.util.ServiceProps.get(
				"lock.expiration.time.tj.zajavki.ot.postavwikov.model.zajavki_ot_postavwikov"));

	public zajavki_ot_postavwikovModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _zajavki_ot_postavwikov_id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setZajavki_ot_postavwikov_id(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _zajavki_ot_postavwikov_id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return zajavki_ot_postavwikov.class;
	}

	@Override
	public String getModelClassName() {
		return zajavki_ot_postavwikov.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("data_izmenenija", getData_izmenenija());
		attributes.put("data_sozdanija", getData_sozdanija());
		attributes.put("itogo_za_tovar", getItogo_za_tovar());
		attributes.put("izmenil", getIzmenil());
		attributes.put("izvewenie_id", getIzvewenie_id());
		attributes.put("kod_po_obshhemu_klassifikatoru",
			getKod_po_obshhemu_klassifikatoru());
		attributes.put("kod_strany_proizvoditelja",
			getKod_strany_proizvoditelja());
		attributes.put("kolichestvo", getKolichestvo());
		attributes.put("lot_id", getLot_id());
		attributes.put("opisanie_tovara", getOpisanie_tovara());
		attributes.put("postavwik_id", getPostavwik_id());
		attributes.put("predlozhenie_postavwika", getPredlozhenie_postavwika());
		attributes.put("sozdal", getSozdal());
		attributes.put("summa_za_edinicu_tovara", getSumma_za_edinicu_tovara());
		attributes.put("tovar_id", getTovar_id());
		attributes.put("zajavki_ot_postavwikov_id",
			getZajavki_ot_postavwikov_id());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Date data_izmenenija = (Date)attributes.get("data_izmenenija");

		if (data_izmenenija != null) {
			setData_izmenenija(data_izmenenija);
		}

		Date data_sozdanija = (Date)attributes.get("data_sozdanija");

		if (data_sozdanija != null) {
			setData_sozdanija(data_sozdanija);
		}

		Double itogo_za_tovar = (Double)attributes.get("itogo_za_tovar");

		if (itogo_za_tovar != null) {
			setItogo_za_tovar(itogo_za_tovar);
		}

		Long izmenil = (Long)attributes.get("izmenil");

		if (izmenil != null) {
			setIzmenil(izmenil);
		}

		Long izvewenie_id = (Long)attributes.get("izvewenie_id");

		if (izvewenie_id != null) {
			setIzvewenie_id(izvewenie_id);
		}

		Long kod_po_obshhemu_klassifikatoru = (Long)attributes.get(
				"kod_po_obshhemu_klassifikatoru");

		if (kod_po_obshhemu_klassifikatoru != null) {
			setKod_po_obshhemu_klassifikatoru(kod_po_obshhemu_klassifikatoru);
		}

		Long kod_strany_proizvoditelja = (Long)attributes.get(
				"kod_strany_proizvoditelja");

		if (kod_strany_proizvoditelja != null) {
			setKod_strany_proizvoditelja(kod_strany_proizvoditelja);
		}

		Long kolichestvo = (Long)attributes.get("kolichestvo");

		if (kolichestvo != null) {
			setKolichestvo(kolichestvo);
		}

		Long lot_id = (Long)attributes.get("lot_id");

		if (lot_id != null) {
			setLot_id(lot_id);
		}

		String opisanie_tovara = (String)attributes.get("opisanie_tovara");

		if (opisanie_tovara != null) {
			setOpisanie_tovara(opisanie_tovara);
		}

		Long postavwik_id = (Long)attributes.get("postavwik_id");

		if (postavwik_id != null) {
			setPostavwik_id(postavwik_id);
		}

		String predlozhenie_postavwika = (String)attributes.get(
				"predlozhenie_postavwika");

		if (predlozhenie_postavwika != null) {
			setPredlozhenie_postavwika(predlozhenie_postavwika);
		}

		Long sozdal = (Long)attributes.get("sozdal");

		if (sozdal != null) {
			setSozdal(sozdal);
		}

		Double summa_za_edinicu_tovara = (Double)attributes.get(
				"summa_za_edinicu_tovara");

		if (summa_za_edinicu_tovara != null) {
			setSumma_za_edinicu_tovara(summa_za_edinicu_tovara);
		}

		Long tovar_id = (Long)attributes.get("tovar_id");

		if (tovar_id != null) {
			setTovar_id(tovar_id);
		}

		Long zajavki_ot_postavwikov_id = (Long)attributes.get(
				"zajavki_ot_postavwikov_id");

		if (zajavki_ot_postavwikov_id != null) {
			setZajavki_ot_postavwikov_id(zajavki_ot_postavwikov_id);
		}
	}

	@JSON
	@Override
	public Date getData_izmenenija() {
		return _data_izmenenija;
	}

	@Override
	public void setData_izmenenija(Date data_izmenenija) {
		_data_izmenenija = data_izmenenija;
	}

	@JSON
	@Override
	public Date getData_sozdanija() {
		return _data_sozdanija;
	}

	@Override
	public void setData_sozdanija(Date data_sozdanija) {
		_data_sozdanija = data_sozdanija;
	}

	@JSON
	@Override
	public double getItogo_za_tovar() {
		return _itogo_za_tovar;
	}

	@Override
	public void setItogo_za_tovar(double itogo_za_tovar) {
		_itogo_za_tovar = itogo_za_tovar;
	}

	@JSON
	@Override
	public long getIzmenil() {
		return _izmenil;
	}

	@Override
	public void setIzmenil(long izmenil) {
		_izmenil = izmenil;
	}

	@JSON
	@Override
	public long getIzvewenie_id() {
		return _izvewenie_id;
	}

	@Override
	public void setIzvewenie_id(long izvewenie_id) {
		_izvewenie_id = izvewenie_id;
	}

	@JSON
	@Override
	public long getKod_po_obshhemu_klassifikatoru() {
		return _kod_po_obshhemu_klassifikatoru;
	}

	@Override
	public void setKod_po_obshhemu_klassifikatoru(
		long kod_po_obshhemu_klassifikatoru) {
		_kod_po_obshhemu_klassifikatoru = kod_po_obshhemu_klassifikatoru;
	}

	@JSON
	@Override
	public long getKod_strany_proizvoditelja() {
		return _kod_strany_proizvoditelja;
	}

	@Override
	public void setKod_strany_proizvoditelja(long kod_strany_proizvoditelja) {
		_kod_strany_proizvoditelja = kod_strany_proizvoditelja;
	}

	@JSON
	@Override
	public long getKolichestvo() {
		return _kolichestvo;
	}

	@Override
	public void setKolichestvo(long kolichestvo) {
		_kolichestvo = kolichestvo;
	}

	@JSON
	@Override
	public long getLot_id() {
		return _lot_id;
	}

	@Override
	public void setLot_id(long lot_id) {
		_lot_id = lot_id;
	}

	@JSON
	@Override
	public String getOpisanie_tovara() {
		if (_opisanie_tovara == null) {
			return StringPool.BLANK;
		}
		else {
			return _opisanie_tovara;
		}
	}

	@Override
	public void setOpisanie_tovara(String opisanie_tovara) {
		_opisanie_tovara = opisanie_tovara;
	}

	@JSON
	@Override
	public long getPostavwik_id() {
		return _postavwik_id;
	}

	@Override
	public void setPostavwik_id(long postavwik_id) {
		_postavwik_id = postavwik_id;
	}

	@JSON
	@Override
	public String getPredlozhenie_postavwika() {
		if (_predlozhenie_postavwika == null) {
			return StringPool.BLANK;
		}
		else {
			return _predlozhenie_postavwika;
		}
	}

	@Override
	public void setPredlozhenie_postavwika(String predlozhenie_postavwika) {
		_predlozhenie_postavwika = predlozhenie_postavwika;
	}

	@JSON
	@Override
	public long getSozdal() {
		return _sozdal;
	}

	@Override
	public void setSozdal(long sozdal) {
		_sozdal = sozdal;
	}

	@JSON
	@Override
	public double getSumma_za_edinicu_tovara() {
		return _summa_za_edinicu_tovara;
	}

	@Override
	public void setSumma_za_edinicu_tovara(double summa_za_edinicu_tovara) {
		_summa_za_edinicu_tovara = summa_za_edinicu_tovara;
	}

	@JSON
	@Override
	public long getTovar_id() {
		return _tovar_id;
	}

	@Override
	public void setTovar_id(long tovar_id) {
		_tovar_id = tovar_id;
	}

	@JSON
	@Override
	public long getZajavki_ot_postavwikov_id() {
		return _zajavki_ot_postavwikov_id;
	}

	@Override
	public void setZajavki_ot_postavwikov_id(long zajavki_ot_postavwikov_id) {
		_zajavki_ot_postavwikov_id = zajavki_ot_postavwikov_id;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			zajavki_ot_postavwikov.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public zajavki_ot_postavwikov toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (zajavki_ot_postavwikov)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		zajavki_ot_postavwikovImpl zajavki_ot_postavwikovImpl = new zajavki_ot_postavwikovImpl();

		zajavki_ot_postavwikovImpl.setData_izmenenija(getData_izmenenija());
		zajavki_ot_postavwikovImpl.setData_sozdanija(getData_sozdanija());
		zajavki_ot_postavwikovImpl.setItogo_za_tovar(getItogo_za_tovar());
		zajavki_ot_postavwikovImpl.setIzmenil(getIzmenil());
		zajavki_ot_postavwikovImpl.setIzvewenie_id(getIzvewenie_id());
		zajavki_ot_postavwikovImpl.setKod_po_obshhemu_klassifikatoru(getKod_po_obshhemu_klassifikatoru());
		zajavki_ot_postavwikovImpl.setKod_strany_proizvoditelja(getKod_strany_proizvoditelja());
		zajavki_ot_postavwikovImpl.setKolichestvo(getKolichestvo());
		zajavki_ot_postavwikovImpl.setLot_id(getLot_id());
		zajavki_ot_postavwikovImpl.setOpisanie_tovara(getOpisanie_tovara());
		zajavki_ot_postavwikovImpl.setPostavwik_id(getPostavwik_id());
		zajavki_ot_postavwikovImpl.setPredlozhenie_postavwika(getPredlozhenie_postavwika());
		zajavki_ot_postavwikovImpl.setSozdal(getSozdal());
		zajavki_ot_postavwikovImpl.setSumma_za_edinicu_tovara(getSumma_za_edinicu_tovara());
		zajavki_ot_postavwikovImpl.setTovar_id(getTovar_id());
		zajavki_ot_postavwikovImpl.setZajavki_ot_postavwikov_id(getZajavki_ot_postavwikov_id());

		zajavki_ot_postavwikovImpl.resetOriginalValues();

		return zajavki_ot_postavwikovImpl;
	}

	@Override
	public int compareTo(zajavki_ot_postavwikov zajavki_ot_postavwikov) {
		long primaryKey = zajavki_ot_postavwikov.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof zajavki_ot_postavwikov)) {
			return false;
		}

		zajavki_ot_postavwikov zajavki_ot_postavwikov = (zajavki_ot_postavwikov)obj;

		long primaryKey = zajavki_ot_postavwikov.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<zajavki_ot_postavwikov> toCacheModel() {
		zajavki_ot_postavwikovCacheModel zajavki_ot_postavwikovCacheModel = new zajavki_ot_postavwikovCacheModel();

		Date data_izmenenija = getData_izmenenija();

		if (data_izmenenija != null) {
			zajavki_ot_postavwikovCacheModel.data_izmenenija = data_izmenenija.getTime();
		}
		else {
			zajavki_ot_postavwikovCacheModel.data_izmenenija = Long.MIN_VALUE;
		}

		Date data_sozdanija = getData_sozdanija();

		if (data_sozdanija != null) {
			zajavki_ot_postavwikovCacheModel.data_sozdanija = data_sozdanija.getTime();
		}
		else {
			zajavki_ot_postavwikovCacheModel.data_sozdanija = Long.MIN_VALUE;
		}

		zajavki_ot_postavwikovCacheModel.itogo_za_tovar = getItogo_za_tovar();

		zajavki_ot_postavwikovCacheModel.izmenil = getIzmenil();

		zajavki_ot_postavwikovCacheModel.izvewenie_id = getIzvewenie_id();

		zajavki_ot_postavwikovCacheModel.kod_po_obshhemu_klassifikatoru = getKod_po_obshhemu_klassifikatoru();

		zajavki_ot_postavwikovCacheModel.kod_strany_proizvoditelja = getKod_strany_proizvoditelja();

		zajavki_ot_postavwikovCacheModel.kolichestvo = getKolichestvo();

		zajavki_ot_postavwikovCacheModel.lot_id = getLot_id();

		zajavki_ot_postavwikovCacheModel.opisanie_tovara = getOpisanie_tovara();

		String opisanie_tovara = zajavki_ot_postavwikovCacheModel.opisanie_tovara;

		if ((opisanie_tovara != null) && (opisanie_tovara.length() == 0)) {
			zajavki_ot_postavwikovCacheModel.opisanie_tovara = null;
		}

		zajavki_ot_postavwikovCacheModel.postavwik_id = getPostavwik_id();

		zajavki_ot_postavwikovCacheModel.predlozhenie_postavwika = getPredlozhenie_postavwika();

		String predlozhenie_postavwika = zajavki_ot_postavwikovCacheModel.predlozhenie_postavwika;

		if ((predlozhenie_postavwika != null) &&
				(predlozhenie_postavwika.length() == 0)) {
			zajavki_ot_postavwikovCacheModel.predlozhenie_postavwika = null;
		}

		zajavki_ot_postavwikovCacheModel.sozdal = getSozdal();

		zajavki_ot_postavwikovCacheModel.summa_za_edinicu_tovara = getSumma_za_edinicu_tovara();

		zajavki_ot_postavwikovCacheModel.tovar_id = getTovar_id();

		zajavki_ot_postavwikovCacheModel.zajavki_ot_postavwikov_id = getZajavki_ot_postavwikov_id();

		return zajavki_ot_postavwikovCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(33);

		sb.append("{data_izmenenija=");
		sb.append(getData_izmenenija());
		sb.append(", data_sozdanija=");
		sb.append(getData_sozdanija());
		sb.append(", itogo_za_tovar=");
		sb.append(getItogo_za_tovar());
		sb.append(", izmenil=");
		sb.append(getIzmenil());
		sb.append(", izvewenie_id=");
		sb.append(getIzvewenie_id());
		sb.append(", kod_po_obshhemu_klassifikatoru=");
		sb.append(getKod_po_obshhemu_klassifikatoru());
		sb.append(", kod_strany_proizvoditelja=");
		sb.append(getKod_strany_proizvoditelja());
		sb.append(", kolichestvo=");
		sb.append(getKolichestvo());
		sb.append(", lot_id=");
		sb.append(getLot_id());
		sb.append(", opisanie_tovara=");
		sb.append(getOpisanie_tovara());
		sb.append(", postavwik_id=");
		sb.append(getPostavwik_id());
		sb.append(", predlozhenie_postavwika=");
		sb.append(getPredlozhenie_postavwika());
		sb.append(", sozdal=");
		sb.append(getSozdal());
		sb.append(", summa_za_edinicu_tovara=");
		sb.append(getSumma_za_edinicu_tovara());
		sb.append(", tovar_id=");
		sb.append(getTovar_id());
		sb.append(", zajavki_ot_postavwikov_id=");
		sb.append(getZajavki_ot_postavwikov_id());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(52);

		sb.append("<model><model-name>");
		sb.append("tj.zajavki.ot.postavwikov.model.zajavki_ot_postavwikov");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>data_izmenenija</column-name><column-value><![CDATA[");
		sb.append(getData_izmenenija());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>data_sozdanija</column-name><column-value><![CDATA[");
		sb.append(getData_sozdanija());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>itogo_za_tovar</column-name><column-value><![CDATA[");
		sb.append(getItogo_za_tovar());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>izmenil</column-name><column-value><![CDATA[");
		sb.append(getIzmenil());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>izvewenie_id</column-name><column-value><![CDATA[");
		sb.append(getIzvewenie_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>kod_po_obshhemu_klassifikatoru</column-name><column-value><![CDATA[");
		sb.append(getKod_po_obshhemu_klassifikatoru());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>kod_strany_proizvoditelja</column-name><column-value><![CDATA[");
		sb.append(getKod_strany_proizvoditelja());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>kolichestvo</column-name><column-value><![CDATA[");
		sb.append(getKolichestvo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>lot_id</column-name><column-value><![CDATA[");
		sb.append(getLot_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>opisanie_tovara</column-name><column-value><![CDATA[");
		sb.append(getOpisanie_tovara());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>postavwik_id</column-name><column-value><![CDATA[");
		sb.append(getPostavwik_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>predlozhenie_postavwika</column-name><column-value><![CDATA[");
		sb.append(getPredlozhenie_postavwika());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sozdal</column-name><column-value><![CDATA[");
		sb.append(getSozdal());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>summa_za_edinicu_tovara</column-name><column-value><![CDATA[");
		sb.append(getSumma_za_edinicu_tovara());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tovar_id</column-name><column-value><![CDATA[");
		sb.append(getTovar_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>zajavki_ot_postavwikov_id</column-name><column-value><![CDATA[");
		sb.append(getZajavki_ot_postavwikov_id());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = zajavki_ot_postavwikov.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			zajavki_ot_postavwikov.class
		};
	private Date _data_izmenenija;
	private Date _data_sozdanija;
	private double _itogo_za_tovar;
	private long _izmenil;
	private long _izvewenie_id;
	private long _kod_po_obshhemu_klassifikatoru;
	private long _kod_strany_proizvoditelja;
	private long _kolichestvo;
	private long _lot_id;
	private String _opisanie_tovara;
	private long _postavwik_id;
	private String _predlozhenie_postavwika;
	private long _sozdal;
	private double _summa_za_edinicu_tovara;
	private long _tovar_id;
	private long _zajavki_ot_postavwikov_id;
	private zajavki_ot_postavwikov _escapedModel;
}