/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.revision.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the revision service. Represents a row in the &quot;sapp.revision&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link tj.revision.model.impl.revisionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link tj.revision.model.impl.revisionImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see revision
 * @see tj.revision.model.impl.revisionImpl
 * @see tj.revision.model.impl.revisionModelImpl
 * @generated
 */
@ProviderType
public interface revisionModel extends BaseModel<revision> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a revision model instance should use the {@link revision} interface instead.
	 */

	/**
	 * Returns the primary key of this revision.
	 *
	 * @return the primary key of this revision
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this revision.
	 *
	 * @param primaryKey the primary key of this revision
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the date of this revision.
	 *
	 * @return the date of this revision
	 */
	public Date getDate();

	/**
	 * Sets the date of this revision.
	 *
	 * @param date the date of this revision
	 */
	public void setDate(Date date);

	/**
	 * Returns the revision_id of this revision.
	 *
	 * @return the revision_id of this revision
	 */
	public long getRevision_id();

	/**
	 * Sets the revision_id of this revision.
	 *
	 * @param revision_id the revision_id of this revision
	 */
	public void setRevision_id(long revision_id);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(tj.revision.model.revision revision);

	@Override
	public int hashCode();

	@Override
	public CacheModel<tj.revision.model.revision> toCacheModel();

	@Override
	public tj.revision.model.revision toEscapedModel();

	@Override
	public tj.revision.model.revision toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}