/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.rajony.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import tj.rajony.model.rajony;
import tj.rajony.model.rajonyModel;
import tj.rajony.model.rajonySoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the rajony service. Represents a row in the &quot;sapp.rajony&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link rajonyModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link rajonyImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see rajonyImpl
 * @see rajony
 * @see rajonyModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class rajonyModelImpl extends BaseModelImpl<rajony>
	implements rajonyModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a rajony model instance should use the {@link rajony} interface instead.
	 */
	public static final String TABLE_NAME = "sapp.rajony";
	public static final Object[][] TABLE_COLUMNS = {
			{ "kod_vbk", Types.BIGINT },
			{ "nazvanie", Types.VARCHAR },
			{ "oblast_id", Types.BIGINT },
			{ "rajony_id", Types.BIGINT }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("kod_vbk", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("nazvanie", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("oblast_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("rajony_id", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE = "create table sapp.rajony (kod_vbk LONG,nazvanie VARCHAR(75) null,oblast_id LONG,rajony_id LONG not null primary key)";
	public static final String TABLE_SQL_DROP = "drop table sapp.rajony";
	public static final String ORDER_BY_JPQL = " ORDER BY rajony.rajony_id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY sapp.rajony.rajony_id ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(tj.rajony.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.tj.rajony.model.rajony"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(tj.rajony.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.tj.rajony.model.rajony"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static rajony toModel(rajonySoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		rajony model = new rajonyImpl();

		model.setKod_vbk(soapModel.getKod_vbk());
		model.setNazvanie(soapModel.getNazvanie());
		model.setOblast_id(soapModel.getOblast_id());
		model.setRajony_id(soapModel.getRajony_id());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<rajony> toModels(rajonySoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<rajony> models = new ArrayList<rajony>(soapModels.length);

		for (rajonySoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(tj.rajony.service.util.ServiceProps.get(
				"lock.expiration.time.tj.rajony.model.rajony"));

	public rajonyModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _rajony_id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setRajony_id(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _rajony_id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return rajony.class;
	}

	@Override
	public String getModelClassName() {
		return rajony.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("kod_vbk", getKod_vbk());
		attributes.put("nazvanie", getNazvanie());
		attributes.put("oblast_id", getOblast_id());
		attributes.put("rajony_id", getRajony_id());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long kod_vbk = (Long)attributes.get("kod_vbk");

		if (kod_vbk != null) {
			setKod_vbk(kod_vbk);
		}

		String nazvanie = (String)attributes.get("nazvanie");

		if (nazvanie != null) {
			setNazvanie(nazvanie);
		}

		Long oblast_id = (Long)attributes.get("oblast_id");

		if (oblast_id != null) {
			setOblast_id(oblast_id);
		}

		Long rajony_id = (Long)attributes.get("rajony_id");

		if (rajony_id != null) {
			setRajony_id(rajony_id);
		}
	}

	@JSON
	@Override
	public long getKod_vbk() {
		return _kod_vbk;
	}

	@Override
	public void setKod_vbk(long kod_vbk) {
		_kod_vbk = kod_vbk;
	}

	@JSON
	@Override
	public String getNazvanie() {
		if (_nazvanie == null) {
			return StringPool.BLANK;
		}
		else {
			return _nazvanie;
		}
	}

	@Override
	public void setNazvanie(String nazvanie) {
		_nazvanie = nazvanie;
	}

	@JSON
	@Override
	public long getOblast_id() {
		return _oblast_id;
	}

	@Override
	public void setOblast_id(long oblast_id) {
		_oblast_id = oblast_id;
	}

	@JSON
	@Override
	public long getRajony_id() {
		return _rajony_id;
	}

	@Override
	public void setRajony_id(long rajony_id) {
		_rajony_id = rajony_id;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			rajony.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public rajony toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (rajony)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		rajonyImpl rajonyImpl = new rajonyImpl();

		rajonyImpl.setKod_vbk(getKod_vbk());
		rajonyImpl.setNazvanie(getNazvanie());
		rajonyImpl.setOblast_id(getOblast_id());
		rajonyImpl.setRajony_id(getRajony_id());

		rajonyImpl.resetOriginalValues();

		return rajonyImpl;
	}

	@Override
	public int compareTo(rajony rajony) {
		long primaryKey = rajony.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof rajony)) {
			return false;
		}

		rajony rajony = (rajony)obj;

		long primaryKey = rajony.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<rajony> toCacheModel() {
		rajonyCacheModel rajonyCacheModel = new rajonyCacheModel();

		rajonyCacheModel.kod_vbk = getKod_vbk();

		rajonyCacheModel.nazvanie = getNazvanie();

		String nazvanie = rajonyCacheModel.nazvanie;

		if ((nazvanie != null) && (nazvanie.length() == 0)) {
			rajonyCacheModel.nazvanie = null;
		}

		rajonyCacheModel.oblast_id = getOblast_id();

		rajonyCacheModel.rajony_id = getRajony_id();

		return rajonyCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(9);

		sb.append("{kod_vbk=");
		sb.append(getKod_vbk());
		sb.append(", nazvanie=");
		sb.append(getNazvanie());
		sb.append(", oblast_id=");
		sb.append(getOblast_id());
		sb.append(", rajony_id=");
		sb.append(getRajony_id());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(16);

		sb.append("<model><model-name>");
		sb.append("tj.rajony.model.rajony");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>kod_vbk</column-name><column-value><![CDATA[");
		sb.append(getKod_vbk());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nazvanie</column-name><column-value><![CDATA[");
		sb.append(getNazvanie());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>oblast_id</column-name><column-value><![CDATA[");
		sb.append(getOblast_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>rajony_id</column-name><column-value><![CDATA[");
		sb.append(getRajony_id());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = rajony.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			rajony.class
		};
	private long _kod_vbk;
	private String _nazvanie;
	private long _oblast_id;
	private long _rajony_id;
	private rajony _escapedModel;
}