/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.dokumenty.postavwika.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import tj.dokumenty.postavwika.model.dokumenty_postavwika;
import tj.dokumenty.postavwika.model.dokumenty_postavwikaModel;
import tj.dokumenty.postavwika.model.dokumenty_postavwikaSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the dokumenty_postavwika service. Represents a row in the &quot;sapp.dokumenty_postavwika&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link dokumenty_postavwikaModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link dokumenty_postavwikaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see dokumenty_postavwikaImpl
 * @see dokumenty_postavwika
 * @see dokumenty_postavwikaModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class dokumenty_postavwikaModelImpl extends BaseModelImpl<dokumenty_postavwika>
	implements dokumenty_postavwikaModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a dokumenty_postavwika model instance should use the {@link dokumenty_postavwika} interface instead.
	 */
	public static final String TABLE_NAME = "sapp.dokumenty_postavwika";
	public static final Object[][] TABLE_COLUMNS = {
			{ "data_zagruzki", Types.TIMESTAMP },
			{ "dokumenty_postavwika_id", Types.BIGINT },
			{ "imja_fajla", Types.VARCHAR },
			{ "nazvanie_dokumenta", Types.VARCHAR },
			{ "postavwik_id", Types.BIGINT },
			{ "tip_dokumenta", Types.INTEGER },
			{ "zagruzil", Types.BIGINT }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("data_zagruzki", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("dokumenty_postavwika_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("imja_fajla", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("nazvanie_dokumenta", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("postavwik_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("tip_dokumenta", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("zagruzil", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE = "create table sapp.dokumenty_postavwika (data_zagruzki DATE null,dokumenty_postavwika_id LONG not null primary key,imja_fajla VARCHAR(75) null,nazvanie_dokumenta VARCHAR(75) null,postavwik_id LONG,tip_dokumenta INTEGER,zagruzil LONG)";
	public static final String TABLE_SQL_DROP = "drop table sapp.dokumenty_postavwika";
	public static final String ORDER_BY_JPQL = " ORDER BY dokumenty_postavwika.dokumenty_postavwika_id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY sapp.dokumenty_postavwika.dokumenty_postavwika_id ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(tj.dokumenty.postavwika.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.tj.dokumenty.postavwika.model.dokumenty_postavwika"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(tj.dokumenty.postavwika.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.tj.dokumenty.postavwika.model.dokumenty_postavwika"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static dokumenty_postavwika toModel(
		dokumenty_postavwikaSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		dokumenty_postavwika model = new dokumenty_postavwikaImpl();

		model.setData_zagruzki(soapModel.getData_zagruzki());
		model.setDokumenty_postavwika_id(soapModel.getDokumenty_postavwika_id());
		model.setImja_fajla(soapModel.getImja_fajla());
		model.setNazvanie_dokumenta(soapModel.getNazvanie_dokumenta());
		model.setPostavwik_id(soapModel.getPostavwik_id());
		model.setTip_dokumenta(soapModel.getTip_dokumenta());
		model.setZagruzil(soapModel.getZagruzil());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<dokumenty_postavwika> toModels(
		dokumenty_postavwikaSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<dokumenty_postavwika> models = new ArrayList<dokumenty_postavwika>(soapModels.length);

		for (dokumenty_postavwikaSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(tj.dokumenty.postavwika.service.util.ServiceProps.get(
				"lock.expiration.time.tj.dokumenty.postavwika.model.dokumenty_postavwika"));

	public dokumenty_postavwikaModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _dokumenty_postavwika_id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setDokumenty_postavwika_id(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _dokumenty_postavwika_id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return dokumenty_postavwika.class;
	}

	@Override
	public String getModelClassName() {
		return dokumenty_postavwika.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("data_zagruzki", getData_zagruzki());
		attributes.put("dokumenty_postavwika_id", getDokumenty_postavwika_id());
		attributes.put("imja_fajla", getImja_fajla());
		attributes.put("nazvanie_dokumenta", getNazvanie_dokumenta());
		attributes.put("postavwik_id", getPostavwik_id());
		attributes.put("tip_dokumenta", getTip_dokumenta());
		attributes.put("zagruzil", getZagruzil());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Date data_zagruzki = (Date)attributes.get("data_zagruzki");

		if (data_zagruzki != null) {
			setData_zagruzki(data_zagruzki);
		}

		Long dokumenty_postavwika_id = (Long)attributes.get(
				"dokumenty_postavwika_id");

		if (dokumenty_postavwika_id != null) {
			setDokumenty_postavwika_id(dokumenty_postavwika_id);
		}

		String imja_fajla = (String)attributes.get("imja_fajla");

		if (imja_fajla != null) {
			setImja_fajla(imja_fajla);
		}

		String nazvanie_dokumenta = (String)attributes.get("nazvanie_dokumenta");

		if (nazvanie_dokumenta != null) {
			setNazvanie_dokumenta(nazvanie_dokumenta);
		}

		Long postavwik_id = (Long)attributes.get("postavwik_id");

		if (postavwik_id != null) {
			setPostavwik_id(postavwik_id);
		}

		Integer tip_dokumenta = (Integer)attributes.get("tip_dokumenta");

		if (tip_dokumenta != null) {
			setTip_dokumenta(tip_dokumenta);
		}

		Long zagruzil = (Long)attributes.get("zagruzil");

		if (zagruzil != null) {
			setZagruzil(zagruzil);
		}
	}

	@JSON
	@Override
	public Date getData_zagruzki() {
		return _data_zagruzki;
	}

	@Override
	public void setData_zagruzki(Date data_zagruzki) {
		_data_zagruzki = data_zagruzki;
	}

	@JSON
	@Override
	public long getDokumenty_postavwika_id() {
		return _dokumenty_postavwika_id;
	}

	@Override
	public void setDokumenty_postavwika_id(long dokumenty_postavwika_id) {
		_dokumenty_postavwika_id = dokumenty_postavwika_id;
	}

	@JSON
	@Override
	public String getImja_fajla() {
		if (_imja_fajla == null) {
			return StringPool.BLANK;
		}
		else {
			return _imja_fajla;
		}
	}

	@Override
	public void setImja_fajla(String imja_fajla) {
		_imja_fajla = imja_fajla;
	}

	@JSON
	@Override
	public String getNazvanie_dokumenta() {
		if (_nazvanie_dokumenta == null) {
			return StringPool.BLANK;
		}
		else {
			return _nazvanie_dokumenta;
		}
	}

	@Override
	public void setNazvanie_dokumenta(String nazvanie_dokumenta) {
		_nazvanie_dokumenta = nazvanie_dokumenta;
	}

	@JSON
	@Override
	public long getPostavwik_id() {
		return _postavwik_id;
	}

	@Override
	public void setPostavwik_id(long postavwik_id) {
		_postavwik_id = postavwik_id;
	}

	@JSON
	@Override
	public int getTip_dokumenta() {
		return _tip_dokumenta;
	}

	@Override
	public void setTip_dokumenta(int tip_dokumenta) {
		_tip_dokumenta = tip_dokumenta;
	}

	@JSON
	@Override
	public long getZagruzil() {
		return _zagruzil;
	}

	@Override
	public void setZagruzil(long zagruzil) {
		_zagruzil = zagruzil;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			dokumenty_postavwika.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public dokumenty_postavwika toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (dokumenty_postavwika)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		dokumenty_postavwikaImpl dokumenty_postavwikaImpl = new dokumenty_postavwikaImpl();

		dokumenty_postavwikaImpl.setData_zagruzki(getData_zagruzki());
		dokumenty_postavwikaImpl.setDokumenty_postavwika_id(getDokumenty_postavwika_id());
		dokumenty_postavwikaImpl.setImja_fajla(getImja_fajla());
		dokumenty_postavwikaImpl.setNazvanie_dokumenta(getNazvanie_dokumenta());
		dokumenty_postavwikaImpl.setPostavwik_id(getPostavwik_id());
		dokumenty_postavwikaImpl.setTip_dokumenta(getTip_dokumenta());
		dokumenty_postavwikaImpl.setZagruzil(getZagruzil());

		dokumenty_postavwikaImpl.resetOriginalValues();

		return dokumenty_postavwikaImpl;
	}

	@Override
	public int compareTo(dokumenty_postavwika dokumenty_postavwika) {
		long primaryKey = dokumenty_postavwika.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof dokumenty_postavwika)) {
			return false;
		}

		dokumenty_postavwika dokumenty_postavwika = (dokumenty_postavwika)obj;

		long primaryKey = dokumenty_postavwika.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<dokumenty_postavwika> toCacheModel() {
		dokumenty_postavwikaCacheModel dokumenty_postavwikaCacheModel = new dokumenty_postavwikaCacheModel();

		Date data_zagruzki = getData_zagruzki();

		if (data_zagruzki != null) {
			dokumenty_postavwikaCacheModel.data_zagruzki = data_zagruzki.getTime();
		}
		else {
			dokumenty_postavwikaCacheModel.data_zagruzki = Long.MIN_VALUE;
		}

		dokumenty_postavwikaCacheModel.dokumenty_postavwika_id = getDokumenty_postavwika_id();

		dokumenty_postavwikaCacheModel.imja_fajla = getImja_fajla();

		String imja_fajla = dokumenty_postavwikaCacheModel.imja_fajla;

		if ((imja_fajla != null) && (imja_fajla.length() == 0)) {
			dokumenty_postavwikaCacheModel.imja_fajla = null;
		}

		dokumenty_postavwikaCacheModel.nazvanie_dokumenta = getNazvanie_dokumenta();

		String nazvanie_dokumenta = dokumenty_postavwikaCacheModel.nazvanie_dokumenta;

		if ((nazvanie_dokumenta != null) && (nazvanie_dokumenta.length() == 0)) {
			dokumenty_postavwikaCacheModel.nazvanie_dokumenta = null;
		}

		dokumenty_postavwikaCacheModel.postavwik_id = getPostavwik_id();

		dokumenty_postavwikaCacheModel.tip_dokumenta = getTip_dokumenta();

		dokumenty_postavwikaCacheModel.zagruzil = getZagruzil();

		return dokumenty_postavwikaCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(15);

		sb.append("{data_zagruzki=");
		sb.append(getData_zagruzki());
		sb.append(", dokumenty_postavwika_id=");
		sb.append(getDokumenty_postavwika_id());
		sb.append(", imja_fajla=");
		sb.append(getImja_fajla());
		sb.append(", nazvanie_dokumenta=");
		sb.append(getNazvanie_dokumenta());
		sb.append(", postavwik_id=");
		sb.append(getPostavwik_id());
		sb.append(", tip_dokumenta=");
		sb.append(getTip_dokumenta());
		sb.append(", zagruzil=");
		sb.append(getZagruzil());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(25);

		sb.append("<model><model-name>");
		sb.append("tj.dokumenty.postavwika.model.dokumenty_postavwika");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>data_zagruzki</column-name><column-value><![CDATA[");
		sb.append(getData_zagruzki());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dokumenty_postavwika_id</column-name><column-value><![CDATA[");
		sb.append(getDokumenty_postavwika_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>imja_fajla</column-name><column-value><![CDATA[");
		sb.append(getImja_fajla());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nazvanie_dokumenta</column-name><column-value><![CDATA[");
		sb.append(getNazvanie_dokumenta());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>postavwik_id</column-name><column-value><![CDATA[");
		sb.append(getPostavwik_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tip_dokumenta</column-name><column-value><![CDATA[");
		sb.append(getTip_dokumenta());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>zagruzil</column-name><column-value><![CDATA[");
		sb.append(getZagruzil());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = dokumenty_postavwika.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			dokumenty_postavwika.class
		};
	private Date _data_zagruzki;
	private long _dokumenty_postavwika_id;
	private String _imja_fajla;
	private String _nazvanie_dokumenta;
	private long _postavwik_id;
	private int _tip_dokumenta;
	private long _zagruzil;
	private dokumenty_postavwika _escapedModel;
}