/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.oblasti.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the oblasti service. Represents a row in the &quot;sapp.oblasti&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link tj.oblasti.model.impl.oblastiModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link tj.oblasti.model.impl.oblastiImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see oblasti
 * @see tj.oblasti.model.impl.oblastiImpl
 * @see tj.oblasti.model.impl.oblastiModelImpl
 * @generated
 */
@ProviderType
public interface oblastiModel extends BaseModel<oblasti> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a oblasti model instance should use the {@link oblasti} interface instead.
	 */

	/**
	 * Returns the primary key of this oblasti.
	 *
	 * @return the primary key of this oblasti
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this oblasti.
	 *
	 * @param primaryKey the primary key of this oblasti
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the oblasti_id of this oblasti.
	 *
	 * @return the oblasti_id of this oblasti
	 */
	public long getOblasti_id();

	/**
	 * Sets the oblasti_id of this oblasti.
	 *
	 * @param oblasti_id the oblasti_id of this oblasti
	 */
	public void setOblasti_id(long oblasti_id);

	/**
	 * Returns the nazvanie of this oblasti.
	 *
	 * @return the nazvanie of this oblasti
	 */
	@AutoEscape
	public String getNazvanie();

	/**
	 * Sets the nazvanie of this oblasti.
	 *
	 * @param nazvanie the nazvanie of this oblasti
	 */
	public void setNazvanie(String nazvanie);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(tj.oblasti.model.oblasti oblasti);

	@Override
	public int hashCode();

	@Override
	public CacheModel<tj.oblasti.model.oblasti> toCacheModel();

	@Override
	public tj.oblasti.model.oblasti toEscapedModel();

	@Override
	public tj.oblasti.model.oblasti toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}