/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.prichiny.otmeny.service.base;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import tj.prichiny.otmeny.model.prichiny_otmeny;
import tj.prichiny.otmeny.service.persistence.prichiny_otmenyPersistence;
import tj.prichiny.otmeny.service.prichiny_otmenyLocalService;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the prichiny_otmeny local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link tj.prichiny.otmeny.service.impl.prichiny_otmenyLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see tj.prichiny.otmeny.service.impl.prichiny_otmenyLocalServiceImpl
 * @see tj.prichiny.otmeny.service.prichiny_otmenyLocalServiceUtil
 * @generated
 */
@ProviderType
public abstract class prichiny_otmenyLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements prichiny_otmenyLocalService,
		IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link tj.prichiny.otmeny.service.prichiny_otmenyLocalServiceUtil} to access the prichiny_otmeny local service.
	 */

	/**
	 * Adds the prichiny_otmeny to the database. Also notifies the appropriate model listeners.
	 *
	 * @param prichiny_otmeny the prichiny_otmeny
	 * @return the prichiny_otmeny that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public prichiny_otmeny addprichiny_otmeny(prichiny_otmeny prichiny_otmeny) {
		prichiny_otmeny.setNew(true);

		return prichiny_otmenyPersistence.update(prichiny_otmeny);
	}

	/**
	 * Creates a new prichiny_otmeny with the primary key. Does not add the prichiny_otmeny to the database.
	 *
	 * @param prichiny_otmeny_id the primary key for the new prichiny_otmeny
	 * @return the new prichiny_otmeny
	 */
	@Override
	public prichiny_otmeny createprichiny_otmeny(long prichiny_otmeny_id) {
		return prichiny_otmenyPersistence.create(prichiny_otmeny_id);
	}

	/**
	 * Deletes the prichiny_otmeny with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param prichiny_otmeny_id the primary key of the prichiny_otmeny
	 * @return the prichiny_otmeny that was removed
	 * @throws PortalException if a prichiny_otmeny with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public prichiny_otmeny deleteprichiny_otmeny(long prichiny_otmeny_id)
		throws PortalException {
		return prichiny_otmenyPersistence.remove(prichiny_otmeny_id);
	}

	/**
	 * Deletes the prichiny_otmeny from the database. Also notifies the appropriate model listeners.
	 *
	 * @param prichiny_otmeny the prichiny_otmeny
	 * @return the prichiny_otmeny that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public prichiny_otmeny deleteprichiny_otmeny(
		prichiny_otmeny prichiny_otmeny) {
		return prichiny_otmenyPersistence.remove(prichiny_otmeny);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(prichiny_otmeny.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return prichiny_otmenyPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link tj.prichiny.otmeny.model.impl.prichiny_otmenyModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end) {
		return prichiny_otmenyPersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link tj.prichiny.otmeny.model.impl.prichiny_otmenyModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end, OrderByComparator<T> orderByComparator) {
		return prichiny_otmenyPersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return prichiny_otmenyPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) {
		return prichiny_otmenyPersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public prichiny_otmeny fetchprichiny_otmeny(long prichiny_otmeny_id) {
		return prichiny_otmenyPersistence.fetchByPrimaryKey(prichiny_otmeny_id);
	}

	/**
	 * Returns the prichiny_otmeny with the primary key.
	 *
	 * @param prichiny_otmeny_id the primary key of the prichiny_otmeny
	 * @return the prichiny_otmeny
	 * @throws PortalException if a prichiny_otmeny with the primary key could not be found
	 */
	@Override
	public prichiny_otmeny getprichiny_otmeny(long prichiny_otmeny_id)
		throws PortalException {
		return prichiny_otmenyPersistence.findByPrimaryKey(prichiny_otmeny_id);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery = new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(prichiny_otmenyLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(prichiny_otmeny.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("prichiny_otmeny_id");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery getIndexableActionableDynamicQuery() {
		IndexableActionableDynamicQuery indexableActionableDynamicQuery = new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(prichiny_otmenyLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(prichiny_otmeny.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"prichiny_otmeny_id");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {
		actionableDynamicQuery.setBaseLocalService(prichiny_otmenyLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(prichiny_otmeny.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("prichiny_otmeny_id");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {
		return prichiny_otmenyLocalService.deleteprichiny_otmeny((prichiny_otmeny)persistedModel);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {
		return prichiny_otmenyPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the prichiny_otmenies.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link tj.prichiny.otmeny.model.impl.prichiny_otmenyModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of prichiny_otmenies
	 * @param end the upper bound of the range of prichiny_otmenies (not inclusive)
	 * @return the range of prichiny_otmenies
	 */
	@Override
	public List<prichiny_otmeny> getprichiny_otmenies(int start, int end) {
		return prichiny_otmenyPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of prichiny_otmenies.
	 *
	 * @return the number of prichiny_otmenies
	 */
	@Override
	public int getprichiny_otmeniesCount() {
		return prichiny_otmenyPersistence.countAll();
	}

	/**
	 * Updates the prichiny_otmeny in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param prichiny_otmeny the prichiny_otmeny
	 * @return the prichiny_otmeny that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public prichiny_otmeny updateprichiny_otmeny(
		prichiny_otmeny prichiny_otmeny) {
		return prichiny_otmenyPersistence.update(prichiny_otmeny);
	}

	/**
	 * Returns the prichiny_otmeny local service.
	 *
	 * @return the prichiny_otmeny local service
	 */
	public prichiny_otmenyLocalService getprichiny_otmenyLocalService() {
		return prichiny_otmenyLocalService;
	}

	/**
	 * Sets the prichiny_otmeny local service.
	 *
	 * @param prichiny_otmenyLocalService the prichiny_otmeny local service
	 */
	public void setprichiny_otmenyLocalService(
		prichiny_otmenyLocalService prichiny_otmenyLocalService) {
		this.prichiny_otmenyLocalService = prichiny_otmenyLocalService;
	}

	/**
	 * Returns the prichiny_otmeny persistence.
	 *
	 * @return the prichiny_otmeny persistence
	 */
	public prichiny_otmenyPersistence getprichiny_otmenyPersistence() {
		return prichiny_otmenyPersistence;
	}

	/**
	 * Sets the prichiny_otmeny persistence.
	 *
	 * @param prichiny_otmenyPersistence the prichiny_otmeny persistence
	 */
	public void setprichiny_otmenyPersistence(
		prichiny_otmenyPersistence prichiny_otmenyPersistence) {
		this.prichiny_otmenyPersistence = prichiny_otmenyPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register("tj.prichiny.otmeny.model.prichiny_otmeny",
			prichiny_otmenyLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"tj.prichiny.otmeny.model.prichiny_otmeny");
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return prichiny_otmenyLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return prichiny_otmeny.class;
	}

	protected String getModelClassName() {
		return prichiny_otmeny.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = prichiny_otmenyPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = prichiny_otmenyLocalService.class)
	protected prichiny_otmenyLocalService prichiny_otmenyLocalService;
	@BeanReference(type = prichiny_otmenyPersistence.class)
	protected prichiny_otmenyPersistence prichiny_otmenyPersistence;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry persistedModelLocalServiceRegistry;
}