/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.prichiny.otmeny.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import tj.prichiny.otmeny.model.prichiny_otmeny;
import tj.prichiny.otmeny.service.persistence.prichiny_otmenyPersistence;
import tj.prichiny.otmeny.service.prichiny_otmenyService;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the prichiny_otmeny remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link tj.prichiny.otmeny.service.impl.prichiny_otmenyServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see tj.prichiny.otmeny.service.impl.prichiny_otmenyServiceImpl
 * @see tj.prichiny.otmeny.service.prichiny_otmenyServiceUtil
 * @generated
 */
public abstract class prichiny_otmenyServiceBaseImpl extends BaseServiceImpl
	implements prichiny_otmenyService, IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link tj.prichiny.otmeny.service.prichiny_otmenyServiceUtil} to access the prichiny_otmeny remote service.
	 */

	/**
	 * Returns the prichiny_otmeny local service.
	 *
	 * @return the prichiny_otmeny local service
	 */
	public tj.prichiny.otmeny.service.prichiny_otmenyLocalService getprichiny_otmenyLocalService() {
		return prichiny_otmenyLocalService;
	}

	/**
	 * Sets the prichiny_otmeny local service.
	 *
	 * @param prichiny_otmenyLocalService the prichiny_otmeny local service
	 */
	public void setprichiny_otmenyLocalService(
		tj.prichiny.otmeny.service.prichiny_otmenyLocalService prichiny_otmenyLocalService) {
		this.prichiny_otmenyLocalService = prichiny_otmenyLocalService;
	}

	/**
	 * Returns the prichiny_otmeny remote service.
	 *
	 * @return the prichiny_otmeny remote service
	 */
	public prichiny_otmenyService getprichiny_otmenyService() {
		return prichiny_otmenyService;
	}

	/**
	 * Sets the prichiny_otmeny remote service.
	 *
	 * @param prichiny_otmenyService the prichiny_otmeny remote service
	 */
	public void setprichiny_otmenyService(
		prichiny_otmenyService prichiny_otmenyService) {
		this.prichiny_otmenyService = prichiny_otmenyService;
	}

	/**
	 * Returns the prichiny_otmeny persistence.
	 *
	 * @return the prichiny_otmeny persistence
	 */
	public prichiny_otmenyPersistence getprichiny_otmenyPersistence() {
		return prichiny_otmenyPersistence;
	}

	/**
	 * Sets the prichiny_otmeny persistence.
	 *
	 * @param prichiny_otmenyPersistence the prichiny_otmeny persistence
	 */
	public void setprichiny_otmenyPersistence(
		prichiny_otmenyPersistence prichiny_otmenyPersistence) {
		this.prichiny_otmenyPersistence = prichiny_otmenyPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name remote service.
	 *
	 * @return the class name remote service
	 */
	public com.liferay.portal.kernel.service.ClassNameService getClassNameService() {
		return classNameService;
	}

	/**
	 * Sets the class name remote service.
	 *
	 * @param classNameService the class name remote service
	 */
	public void setClassNameService(
		com.liferay.portal.kernel.service.ClassNameService classNameService) {
		this.classNameService = classNameService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.kernel.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.kernel.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
	}

	public void destroy() {
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return prichiny_otmenyService.class.getName();
	}

	protected Class<?> getModelClass() {
		return prichiny_otmeny.class;
	}

	protected String getModelClassName() {
		return prichiny_otmeny.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = prichiny_otmenyPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = tj.prichiny.otmeny.service.prichiny_otmenyLocalService.class)
	protected tj.prichiny.otmeny.service.prichiny_otmenyLocalService prichiny_otmenyLocalService;
	@BeanReference(type = prichiny_otmenyService.class)
	protected prichiny_otmenyService prichiny_otmenyService;
	@BeanReference(type = prichiny_otmenyPersistence.class)
	protected prichiny_otmenyPersistence prichiny_otmenyPersistence;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameService.class)
	protected com.liferay.portal.kernel.service.ClassNameService classNameService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserService.class)
	protected com.liferay.portal.kernel.service.UserService userService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
}