/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.bjudzhetnoe.polnomochie.model.impl;

import aQute.bnd.annotation.ProviderType;

import tj.bjudzhetnoe.polnomochie.model.bjudzhetnoe_polnomochie;
import tj.bjudzhetnoe.polnomochie.service.bjudzhetnoe_polnomochieLocalServiceUtil;

/**
 * The extended model base implementation for the bjudzhetnoe_polnomochie service. Represents a row in the &quot;sapp.bjudzhetnoe_polnomochie&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link bjudzhetnoe_polnomochieImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see bjudzhetnoe_polnomochieImpl
 * @see bjudzhetnoe_polnomochie
 * @generated
 */
@ProviderType
public abstract class bjudzhetnoe_polnomochieBaseImpl
	extends bjudzhetnoe_polnomochieModelImpl implements bjudzhetnoe_polnomochie {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a bjudzhetnoe_polnomochie model instance should use the {@link bjudzhetnoe_polnomochie} interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			bjudzhetnoe_polnomochieLocalServiceUtil.addbjudzhetnoe_polnomochie(this);
		}
		else {
			bjudzhetnoe_polnomochieLocalServiceUtil.updatebjudzhetnoe_polnomochie(this);
		}
	}
}