/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.profil.polzovatelej.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import tj.profil.polzovatelej.model.profil_polzovatelej;
import tj.profil.polzovatelej.service.persistence.profil_polzovatelejPersistence;
import tj.profil.polzovatelej.service.profil_polzovatelejService;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the profil_polzovatelej remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link tj.profil.polzovatelej.service.impl.profil_polzovatelejServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see tj.profil.polzovatelej.service.impl.profil_polzovatelejServiceImpl
 * @see tj.profil.polzovatelej.service.profil_polzovatelejServiceUtil
 * @generated
 */
public abstract class profil_polzovatelejServiceBaseImpl extends BaseServiceImpl
	implements profil_polzovatelejService, IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link tj.profil.polzovatelej.service.profil_polzovatelejServiceUtil} to access the profil_polzovatelej remote service.
	 */

	/**
	 * Returns the profil_polzovatelej local service.
	 *
	 * @return the profil_polzovatelej local service
	 */
	public tj.profil.polzovatelej.service.profil_polzovatelejLocalService getprofil_polzovatelejLocalService() {
		return profil_polzovatelejLocalService;
	}

	/**
	 * Sets the profil_polzovatelej local service.
	 *
	 * @param profil_polzovatelejLocalService the profil_polzovatelej local service
	 */
	public void setprofil_polzovatelejLocalService(
		tj.profil.polzovatelej.service.profil_polzovatelejLocalService profil_polzovatelejLocalService) {
		this.profil_polzovatelejLocalService = profil_polzovatelejLocalService;
	}

	/**
	 * Returns the profil_polzovatelej remote service.
	 *
	 * @return the profil_polzovatelej remote service
	 */
	public profil_polzovatelejService getprofil_polzovatelejService() {
		return profil_polzovatelejService;
	}

	/**
	 * Sets the profil_polzovatelej remote service.
	 *
	 * @param profil_polzovatelejService the profil_polzovatelej remote service
	 */
	public void setprofil_polzovatelejService(
		profil_polzovatelejService profil_polzovatelejService) {
		this.profil_polzovatelejService = profil_polzovatelejService;
	}

	/**
	 * Returns the profil_polzovatelej persistence.
	 *
	 * @return the profil_polzovatelej persistence
	 */
	public profil_polzovatelejPersistence getprofil_polzovatelejPersistence() {
		return profil_polzovatelejPersistence;
	}

	/**
	 * Sets the profil_polzovatelej persistence.
	 *
	 * @param profil_polzovatelejPersistence the profil_polzovatelej persistence
	 */
	public void setprofil_polzovatelejPersistence(
		profil_polzovatelejPersistence profil_polzovatelejPersistence) {
		this.profil_polzovatelejPersistence = profil_polzovatelejPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name remote service.
	 *
	 * @return the class name remote service
	 */
	public com.liferay.portal.kernel.service.ClassNameService getClassNameService() {
		return classNameService;
	}

	/**
	 * Sets the class name remote service.
	 *
	 * @param classNameService the class name remote service
	 */
	public void setClassNameService(
		com.liferay.portal.kernel.service.ClassNameService classNameService) {
		this.classNameService = classNameService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.kernel.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.kernel.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
	}

	public void destroy() {
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return profil_polzovatelejService.class.getName();
	}

	protected Class<?> getModelClass() {
		return profil_polzovatelej.class;
	}

	protected String getModelClassName() {
		return profil_polzovatelej.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = profil_polzovatelejPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = tj.profil.polzovatelej.service.profil_polzovatelejLocalService.class)
	protected tj.profil.polzovatelej.service.profil_polzovatelejLocalService profil_polzovatelejLocalService;
	@BeanReference(type = profil_polzovatelejService.class)
	protected profil_polzovatelejService profil_polzovatelejService;
	@BeanReference(type = profil_polzovatelejPersistence.class)
	protected profil_polzovatelejPersistence profil_polzovatelejPersistence;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameService.class)
	protected com.liferay.portal.kernel.service.ClassNameService classNameService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserService.class)
	protected com.liferay.portal.kernel.service.UserService userService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
}