/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.prichiny.otmeny.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the prichiny_otmeny service. Represents a row in the &quot;sapp.prichiny_otmeny&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link tj.prichiny.otmeny.model.impl.prichiny_otmenyModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link tj.prichiny.otmeny.model.impl.prichiny_otmenyImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see prichiny_otmeny
 * @see tj.prichiny.otmeny.model.impl.prichiny_otmenyImpl
 * @see tj.prichiny.otmeny.model.impl.prichiny_otmenyModelImpl
 * @generated
 */
@ProviderType
public interface prichiny_otmenyModel extends BaseModel<prichiny_otmeny> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a prichiny_otmeny model instance should use the {@link prichiny_otmeny} interface instead.
	 */

	/**
	 * Returns the primary key of this prichiny_otmeny.
	 *
	 * @return the primary key of this prichiny_otmeny
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this prichiny_otmeny.
	 *
	 * @param primaryKey the primary key of this prichiny_otmeny
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the data_izmenenija of this prichiny_otmeny.
	 *
	 * @return the data_izmenenija of this prichiny_otmeny
	 */
	public Date getData_izmenenija();

	/**
	 * Sets the data_izmenenija of this prichiny_otmeny.
	 *
	 * @param data_izmenenija the data_izmenenija of this prichiny_otmeny
	 */
	public void setData_izmenenija(Date data_izmenenija);

	/**
	 * Returns the data_sozdanija of this prichiny_otmeny.
	 *
	 * @return the data_sozdanija of this prichiny_otmeny
	 */
	public Date getData_sozdanija();

	/**
	 * Sets the data_sozdanija of this prichiny_otmeny.
	 *
	 * @param data_sozdanija the data_sozdanija of this prichiny_otmeny
	 */
	public void setData_sozdanija(Date data_sozdanija);

	/**
	 * Returns the izmenil of this prichiny_otmeny.
	 *
	 * @return the izmenil of this prichiny_otmeny
	 */
	public long getIzmenil();

	/**
	 * Sets the izmenil of this prichiny_otmeny.
	 *
	 * @param izmenil the izmenil of this prichiny_otmeny
	 */
	public void setIzmenil(long izmenil);

	/**
	 * Returns the izvewenie_id of this prichiny_otmeny.
	 *
	 * @return the izvewenie_id of this prichiny_otmeny
	 */
	public long getIzvewenie_id();

	/**
	 * Sets the izvewenie_id of this prichiny_otmeny.
	 *
	 * @param izvewenie_id the izvewenie_id of this prichiny_otmeny
	 */
	public void setIzvewenie_id(long izvewenie_id);

	/**
	 * Returns the prichina of this prichiny_otmeny.
	 *
	 * @return the prichina of this prichiny_otmeny
	 */
	@AutoEscape
	public String getPrichina();

	/**
	 * Sets the prichina of this prichiny_otmeny.
	 *
	 * @param prichina the prichina of this prichiny_otmeny
	 */
	public void setPrichina(String prichina);

	/**
	 * Returns the prichiny_otmeny_id of this prichiny_otmeny.
	 *
	 * @return the prichiny_otmeny_id of this prichiny_otmeny
	 */
	public long getPrichiny_otmeny_id();

	/**
	 * Sets the prichiny_otmeny_id of this prichiny_otmeny.
	 *
	 * @param prichiny_otmeny_id the prichiny_otmeny_id of this prichiny_otmeny
	 */
	public void setPrichiny_otmeny_id(long prichiny_otmeny_id);

	/**
	 * Returns the sozdal of this prichiny_otmeny.
	 *
	 * @return the sozdal of this prichiny_otmeny
	 */
	public long getSozdal();

	/**
	 * Sets the sozdal of this prichiny_otmeny.
	 *
	 * @param sozdal the sozdal of this prichiny_otmeny
	 */
	public void setSozdal(long sozdal);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		tj.prichiny.otmeny.model.prichiny_otmeny prichiny_otmeny);

	@Override
	public int hashCode();

	@Override
	public CacheModel<tj.prichiny.otmeny.model.prichiny_otmeny> toCacheModel();

	@Override
	public tj.prichiny.otmeny.model.prichiny_otmeny toEscapedModel();

	@Override
	public tj.prichiny.otmeny.model.prichiny_otmeny toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}