/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.izvewenie.put.service.base;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import tj.izvewenie.put.model.izvewenie_put;
import tj.izvewenie.put.service.izvewenie_putLocalService;
import tj.izvewenie.put.service.persistence.izvewenie_putPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the izvewenie_put local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link tj.izvewenie.put.service.impl.izvewenie_putLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see tj.izvewenie.put.service.impl.izvewenie_putLocalServiceImpl
 * @see tj.izvewenie.put.service.izvewenie_putLocalServiceUtil
 * @generated
 */
@ProviderType
public abstract class izvewenie_putLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements izvewenie_putLocalService,
		IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link tj.izvewenie.put.service.izvewenie_putLocalServiceUtil} to access the izvewenie_put local service.
	 */

	/**
	 * Adds the izvewenie_put to the database. Also notifies the appropriate model listeners.
	 *
	 * @param izvewenie_put the izvewenie_put
	 * @return the izvewenie_put that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public izvewenie_put addizvewenie_put(izvewenie_put izvewenie_put) {
		izvewenie_put.setNew(true);

		return izvewenie_putPersistence.update(izvewenie_put);
	}

	/**
	 * Creates a new izvewenie_put with the primary key. Does not add the izvewenie_put to the database.
	 *
	 * @param izvewenie_put_id the primary key for the new izvewenie_put
	 * @return the new izvewenie_put
	 */
	@Override
	public izvewenie_put createizvewenie_put(long izvewenie_put_id) {
		return izvewenie_putPersistence.create(izvewenie_put_id);
	}

	/**
	 * Deletes the izvewenie_put with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param izvewenie_put_id the primary key of the izvewenie_put
	 * @return the izvewenie_put that was removed
	 * @throws PortalException if a izvewenie_put with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public izvewenie_put deleteizvewenie_put(long izvewenie_put_id)
		throws PortalException {
		return izvewenie_putPersistence.remove(izvewenie_put_id);
	}

	/**
	 * Deletes the izvewenie_put from the database. Also notifies the appropriate model listeners.
	 *
	 * @param izvewenie_put the izvewenie_put
	 * @return the izvewenie_put that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public izvewenie_put deleteizvewenie_put(izvewenie_put izvewenie_put) {
		return izvewenie_putPersistence.remove(izvewenie_put);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(izvewenie_put.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return izvewenie_putPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link tj.izvewenie.put.model.impl.izvewenie_putModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end) {
		return izvewenie_putPersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link tj.izvewenie.put.model.impl.izvewenie_putModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end, OrderByComparator<T> orderByComparator) {
		return izvewenie_putPersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return izvewenie_putPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) {
		return izvewenie_putPersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public izvewenie_put fetchizvewenie_put(long izvewenie_put_id) {
		return izvewenie_putPersistence.fetchByPrimaryKey(izvewenie_put_id);
	}

	/**
	 * Returns the izvewenie_put with the primary key.
	 *
	 * @param izvewenie_put_id the primary key of the izvewenie_put
	 * @return the izvewenie_put
	 * @throws PortalException if a izvewenie_put with the primary key could not be found
	 */
	@Override
	public izvewenie_put getizvewenie_put(long izvewenie_put_id)
		throws PortalException {
		return izvewenie_putPersistence.findByPrimaryKey(izvewenie_put_id);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery = new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(izvewenie_putLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(izvewenie_put.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("izvewenie_put_id");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery getIndexableActionableDynamicQuery() {
		IndexableActionableDynamicQuery indexableActionableDynamicQuery = new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(izvewenie_putLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(izvewenie_put.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"izvewenie_put_id");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {
		actionableDynamicQuery.setBaseLocalService(izvewenie_putLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(izvewenie_put.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("izvewenie_put_id");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {
		return izvewenie_putLocalService.deleteizvewenie_put((izvewenie_put)persistedModel);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {
		return izvewenie_putPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the izvewenie_puts.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link tj.izvewenie.put.model.impl.izvewenie_putModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of izvewenie_puts
	 * @param end the upper bound of the range of izvewenie_puts (not inclusive)
	 * @return the range of izvewenie_puts
	 */
	@Override
	public List<izvewenie_put> getizvewenie_puts(int start, int end) {
		return izvewenie_putPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of izvewenie_puts.
	 *
	 * @return the number of izvewenie_puts
	 */
	@Override
	public int getizvewenie_putsCount() {
		return izvewenie_putPersistence.countAll();
	}

	/**
	 * Updates the izvewenie_put in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param izvewenie_put the izvewenie_put
	 * @return the izvewenie_put that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public izvewenie_put updateizvewenie_put(izvewenie_put izvewenie_put) {
		return izvewenie_putPersistence.update(izvewenie_put);
	}

	/**
	 * Returns the izvewenie_put local service.
	 *
	 * @return the izvewenie_put local service
	 */
	public izvewenie_putLocalService getizvewenie_putLocalService() {
		return izvewenie_putLocalService;
	}

	/**
	 * Sets the izvewenie_put local service.
	 *
	 * @param izvewenie_putLocalService the izvewenie_put local service
	 */
	public void setizvewenie_putLocalService(
		izvewenie_putLocalService izvewenie_putLocalService) {
		this.izvewenie_putLocalService = izvewenie_putLocalService;
	}

	/**
	 * Returns the izvewenie_put persistence.
	 *
	 * @return the izvewenie_put persistence
	 */
	public izvewenie_putPersistence getizvewenie_putPersistence() {
		return izvewenie_putPersistence;
	}

	/**
	 * Sets the izvewenie_put persistence.
	 *
	 * @param izvewenie_putPersistence the izvewenie_put persistence
	 */
	public void setizvewenie_putPersistence(
		izvewenie_putPersistence izvewenie_putPersistence) {
		this.izvewenie_putPersistence = izvewenie_putPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register("tj.izvewenie.put.model.izvewenie_put",
			izvewenie_putLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"tj.izvewenie.put.model.izvewenie_put");
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return izvewenie_putLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return izvewenie_put.class;
	}

	protected String getModelClassName() {
		return izvewenie_put.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = izvewenie_putPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = izvewenie_putLocalService.class)
	protected izvewenie_putLocalService izvewenie_putLocalService;
	@BeanReference(type = izvewenie_putPersistence.class)
	protected izvewenie_putPersistence izvewenie_putPersistence;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry persistedModelLocalServiceRegistry;
}