/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.roli.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import tj.roli.model.roli;
import tj.roli.model.roliModel;
import tj.roli.model.roliSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the roli service. Represents a row in the &quot;sapp.roli&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link roliModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link roliImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see roliImpl
 * @see roli
 * @see roliModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class roliModelImpl extends BaseModelImpl<roli> implements roliModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a roli model instance should use the {@link roli} interface instead.
	 */
	public static final String TABLE_NAME = "sapp.roli";
	public static final Object[][] TABLE_COLUMNS = {
			{ "rol", Types.VARCHAR },
			{ "roli_id", Types.BIGINT }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("rol", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("roli_id", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE = "create table sapp.roli (rol VARCHAR(75) null,roli_id LONG not null primary key)";
	public static final String TABLE_SQL_DROP = "drop table sapp.roli";
	public static final String ORDER_BY_JPQL = " ORDER BY roli.roli_id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY sapp.roli.roli_id ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(tj.roli.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.tj.roli.model.roli"), true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(tj.roli.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.tj.roli.model.roli"), true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static roli toModel(roliSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		roli model = new roliImpl();

		model.setRol(soapModel.getRol());
		model.setRoli_id(soapModel.getRoli_id());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<roli> toModels(roliSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<roli> models = new ArrayList<roli>(soapModels.length);

		for (roliSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(tj.roli.service.util.ServiceProps.get(
				"lock.expiration.time.tj.roli.model.roli"));

	public roliModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _roli_id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setRoli_id(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _roli_id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return roli.class;
	}

	@Override
	public String getModelClassName() {
		return roli.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("rol", getRol());
		attributes.put("roli_id", getRoli_id());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String rol = (String)attributes.get("rol");

		if (rol != null) {
			setRol(rol);
		}

		Long roli_id = (Long)attributes.get("roli_id");

		if (roli_id != null) {
			setRoli_id(roli_id);
		}
	}

	@JSON
	@Override
	public String getRol() {
		if (_rol == null) {
			return StringPool.BLANK;
		}
		else {
			return _rol;
		}
	}

	@Override
	public void setRol(String rol) {
		_rol = rol;
	}

	@JSON
	@Override
	public long getRoli_id() {
		return _roli_id;
	}

	@Override
	public void setRoli_id(long roli_id) {
		_roli_id = roli_id;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			roli.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public roli toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (roli)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		roliImpl roliImpl = new roliImpl();

		roliImpl.setRol(getRol());
		roliImpl.setRoli_id(getRoli_id());

		roliImpl.resetOriginalValues();

		return roliImpl;
	}

	@Override
	public int compareTo(roli roli) {
		long primaryKey = roli.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof roli)) {
			return false;
		}

		roli roli = (roli)obj;

		long primaryKey = roli.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<roli> toCacheModel() {
		roliCacheModel roliCacheModel = new roliCacheModel();

		roliCacheModel.rol = getRol();

		String rol = roliCacheModel.rol;

		if ((rol != null) && (rol.length() == 0)) {
			roliCacheModel.rol = null;
		}

		roliCacheModel.roli_id = getRoli_id();

		return roliCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(5);

		sb.append("{rol=");
		sb.append(getRol());
		sb.append(", roli_id=");
		sb.append(getRoli_id());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(10);

		sb.append("<model><model-name>");
		sb.append("tj.roli.model.roli");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>rol</column-name><column-value><![CDATA[");
		sb.append(getRol());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>roli_id</column-name><column-value><![CDATA[");
		sb.append(getRoli_id());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = roli.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			roli.class
		};
	private String _rol;
	private long _roli_id;
	private roli _escapedModel;
}